### ISSUE TITLE
Browser: DOM Inspector crash on empty page

### ISSUE THREAD

**Issue by TobyAsE** [SerenityOS/serenity#10047]
When right-clicking and "Inspect element" on a page that is empty (has an empty <body> tag), the opening DOM inspector crashes.

**Comment by AtkinsSJ** [comment]
Not sure if this is the same issue but it's similar: doing "Inspect element" on a part of the page that doesn't have elements also crashes. I guess we're grabbing the  currently-hovered element from the Document, without checking if it's null or not. (By which I mean, **I'm** doing that, because I assumed there'd always be a hovered element if you're mousing over the page.)
