### ISSUE TITLE
Lagom: macOS Build does not work with -DBUILD_LAGOM=ON

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#10055]
Doing the standard Lagom build steps does not produce workable binaries in macOS

```
cmake -GNinja  -S Meta/Lagom -B Build/lagom -DBUILD_LAGOM=ON
ninja -C Build/lagom install
```

```
error: /Library/Developer/CommandLineTools/usr/bin/install_name_tool: for: /Users/mustafa/git/serenity/Build/superbuild-i686/../lagom-install/lib/liblagom-core.0.0.0.dylib (for architecture x86_64) option "-add_rpath @loader_path/../lib" would duplicate path, file already has LC_RPATH for: @loader_path/../lib
```

This is absoutely related to rpath handling, which is a super mystery to me (on macOS at least).

This resource: https://matthew-brett.github.io/docosx/mac_runtime_link.html
And the cmake reference: https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling

 don't make it immediately obvious how to get the `$ORIGIN:$ORIGIN/../${CMAKE_INSTALL_LIBDIR}"` behavior we want for parity with Linux given we're using GNUInstallDirs.

**Comment by friendlyanon** [comment]
This is why I mentioned in an earlier PR comment that someone with a Mac and knowledge should look at this. I have zero knowledge on dyld RPATH handling.

What I could suggest trying however is the [`export(EXPORT)`](https://cmake.org/cmake/help/latest/command/export.html) command. _In retrospect, maybe this should have been used instead of installing?_  
Changes to be made:
- Rip out all RPATH related code from the lists files of host tools.
- Add an `export(EXPORT LagomTargets NAMESPACE Lagom:: FILE LagomConfig.cmake)` call somewhere. `FILE` is relative to the current binary directory at the time of calling.
- Disable install in the superbuild lists file by adding `INSTALL_COMMAND ""` to host tools.
- Make the OS build depend on `lagom-build` instead and point the prefix path to the binary firectory where the `export(EXPORT)` commanf created the config file.

**Comment by ADKaster** [comment]
Another thing that might "work" would be to skip rpath entirely on macOS and force static libraries?

On discord Mustafa was saying that on rebuilds (e.g. after the host tools have been installed once) even with the mode that only builds the one shared library and the code generator tools it always tries to install the binaries, fails to adjust the rpath, and then the dependency management decides it wants to rerun all the code generators for all ~750 steps. 

He also found that setting CMAKE_BUILD_WITH_INSTALL_RPATH to TRUE fixes that behavior (of trying and failing to adjust the rpath of files that already had it adjusted??). But iirc that setting would likely make `ninja test` not work so great when the unit tests are executed from the build directory?

**Comment by friendlyanon** [comment]
CMake will ensure that things can be run in the binary directories on platforms that support RPATH, so using them as-is from the build directory is fine, since binary directories cannot be relocated anyway. You could build and link statically, but that wouldn't change much, unless you plan to enable their use on platforms without RPATH (like Windows) in the future.

Did Mustafa try with the suggested changes? There are no files to install when the step is a noop. [Docs](https://cmake.org/cmake/help/latest/module/ExternalProject.html):
> Passing an empty string as the `<cmd>` makes the install step do nothing.

**Comment by friendlyanon** [comment]
I have updated my guinea-pig test project to use `export(EXPORT)` for its superbuild. https://github.com/friendlyanon/cmake-init-gif-engine/commit/4b423b19ce85d14088936c58ea34baf1be6e28e5  
The commit that follows also adds multi-config generator support if that's of interest to you.
