### ISSUE TITLE
Question about the implementation of AK/Try.h

### ISSUE THREAD

**Issue by stefanos82** [SerenityOS/serenity#10303]
I am watching the SerenityOS update (September 2021) and what caught my attention was the use of `TRY()`.

My question is the following: isn't the implementation of `TRY()`

```c++
#define TRY(expression)                               \
    ({                                                \
        auto _temporary_result = (expression);        \
        if (_temporary_result.is_error())             \
            return _temporary_result.release_error(); \
        _temporary_result.release_value();            \
    })
```

more or less the same as following `do / while()` code?

```c++
#define TRY(expression)                             \
    do {                                            \
    auto _temporary_result = (expression);          \
    if (_temporary_result.is_error())               \
        return _temporary_result.release_error();   \
    _temporary_result.release_value();              \
} while (0)
```

Please advice, thank you.

**Comment by ADKaster** [comment]
It's not the same because the use is 

```
auto x = TRY(get_some_x());
```

It's not valid C++ to assign a value to the result of a do-while expression. 


The macro expansion of the working TRY is 

```
auto x = ({  auto _temporary_result = (expression);        \
        if (_temporary_result.is_error())             \
            return _temporary_result.release_error(); \
        _temporary_result.release_value();  });
```
Which means that if the result has a value, it's released and move-constructed as `x`. But if it doesn't have value, we return from the enclosing function. that's also why it' can't be a constexpr function and has to be a macro.
