### ISSUE TITLE
Inconsistent handling of (uid_t)-1 in the setuid group of syscalls

### ISSUE THREAD

**Issue by sohomdatta1** [SerenityOS/serenity#10370]
Among the setuid group of syscalls (calling them so ), `seteuid()`, `setgid()`, `seteuid()`, `setegid()` allow the user to set their UID (or GID) to `(uid_t)-1` whereas `setreuid()`, `setresuid()`, `setresgid()` explicitly disallow setting the UID (or GID) values to -1 rather opting use use it as value implying that the UID and GID should be restored to their old value.

Given that most other places that explicitly deal with UID/GID values inside Serenity mostly seem to disallow the use of -1 as a UID/GID value, I think all the syscalls in the setuid group should explicitly disallow setting the UID/GID values to -1 and instead use it as a value that implies that the UID/GID must be restored to their old value.

**Comment by supercomputer7** [comment]
Looking at [setreuid(2)](https://man7.org/linux/man-pages/man2/setreuid.2.html) manual page, it explicitly forbids UID to be set to -1, same thing for `setregid(2)`. However, for example, [setuid(2)](https://linux.die.net/man/2/setuid) manual page doesn't say the same thing. Does POSIX say otherwise for this problem? If not, we could do what you suggested, however, it'd be wise to see what other implementations do here.

**Comment by supercomputer7** [comment]
So it seems like Linux returns EINVAL if `uid_valid()` is returning false. That function ensures that the UID is not -1.
Now the interesting question, should we even consider negative values at all?
