### ISSUE TITLE
SoundPlayer: Looping without command-line arguments is bad

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#10751]
Steps to reproduce:
1. Open SoundPlayer without arguments
2. Open a file through the menu
3. Click either "Loop File" (produces the bug in the screenshot) or "Loop Playlist" (crashes SoundPlayer)
4. Click Play
5. Wait until it's finished (I recommend a short music file)

![Bildschirmfoto_2021-11-01_17-47-21](https://user-images.githubusercontent.com/2690845/139730448-c5bb653b-f211-4cfd-8cb0-31910a25d2d0.png)

**Comment by kleinesfilmroellchen** [comment]
Looks like an out of bounds index for the filename

**Comment by lpereira** [comment]
That's most certainly my fault; might be a bad rebase or cherry-pick from the winamp branch.

I suspect the issue has to do with the fact that if you don't load a playlist, the playlist model is empty, and thus https://github.com/SerenityOS/serenity/blob/314b8a374ba82152bb092d9c6ff0c2b5d5c21005/Userland/Applications/SoundPlayer/Playlist.cpp#L74 returns garbage when the player needs the next file to play (see the [callback here](https://github.com/SerenityOS/serenity/blob/314b8a374ba82152bb092d9c6ff0c2b5d5c21005/Userland/Applications/SoundPlayer/Player.cpp#L25)).

Maybe it's a good idea to modify `Playlist::next()` to return `{}` if the model is empty (which will avoid the crash).

Now, for the garbage output, I don't really know what's happening. `m_loaded_filename` is updated every time the player changes which file is playing, so it shouldn't contain arbitrary stuff there. Need to debug this to understand what's going on.

(Unfortunately, I can't work on this for a good while, as I'm in the process of moving to a new place and free time is scarce.)

**Comment by alimpfard** [comment]
That bit of code is almost always a use-after-free (that `next` is a copy of the String in the m3uentry)

https://github.com/SerenityOS/serenity/blob/314b8a374ba82152bb092d9c6ff0c2b5d5c21005/Userland/Applications/SoundPlayer/Playlist.cpp#L74-L78

I'm not sure I follow how there can be an entry there if no playlist exists.

Regardless, that function should either take extra care not to return views to deleted strings, or to just return a `String`.

**Comment by alimpfard** [comment]
That bit of code is almost always a use-after-free (that `next` is a copy of the String in the m3uentry)

https://github.com/SerenityOS/serenity/blob/314b8a374ba82152bb092d9c6ff0c2b5d5c21005/Userland/Applications/SoundPlayer/Playlist.cpp#L74-L78

I'm not sure I follow how there can be an entry there if no playlist exists.

Regardless, that function should either take extra care not to return views to deleted strings, or to just return a `String`.

**Comment by elyse0** [comment]
I've debugged the 'File loop' case and the bug is somewhere inside PlaybackManger.on_update(), where we're modifying 'm_loaded_filename'.

Both, the 'argv[1]' and the 'get_open_filepath' return a String but the result of 'Player::play_file_path' is different

https://github.com/SerenityOS/serenity/blob/314b8a374ba82152bb092d9c6ff0c2b5d5c21005/Userland/Applications/SoundPlayer/main.cpp#L45-L58

If we pass the filename as argument, this is the output:

![image](https://user-images.githubusercontent.com/26639800/139918032-63f8e5c7-2f9f-4be1-b40b-aac538d3656b.png)

If we select the file from the FilePicker, this is the ouput:

![image](https://user-images.githubusercontent.com/26639800/139917993-bf15e00c-4bf3-46f6-a9e8-a3540333906e.png)
)

'Player::play_file_path' receives the 'path' as a StringView and the only ones that use it are 'm_loaded_filename' and 'loader'. So I think the loader is modifying it because it also takes a StringView of path.

https://github.com/SerenityOS/serenity/blob/314b8a374ba82152bb092d9c6ff0c2b5d5c21005/Userland/Applications/SoundPlayer/Player.cpp#L41-L63

I fixed it passing a String to 'Player::play_file_path' instead of a StringView and using an isolated copy for 'm_loaded_filename' https://github.com/elyse0/serenity/commit/6f884d04d9aa42ede1f0a46120ef10ada62c7b73  but I think the real bug is inside the 'loader'.

Tbh I still don't know the difference between String&, StringView and StringView &path, but I think this could be useful for someone that does and could fix the main bug.

**Comment by elyse0** [comment]
A simpler way to fix the 'file loop' bug, is taking the filename from the loader. 

https://github.com/elyse0/serenity/commit/60c84e4bd6350f6a884010986a8226fbc14a1c35

````diff
    NonnullRefPtr<Audio::Loader> loader = Audio::Loader::create(path);
    if (loader->has_error()) {
        audio_load_error(path, loader->error_string());
        return;
    }

-   m_loaded_filename = path;
+   m_loaded_filename = loader->file()->filename().view();
````

I still don't know why '**m_loaded_filename**' gets filled with garbage in the first place... 🤔

**Comment by kleinesfilmroellchen** [comment]
So, is the bug still in the loader? Because I'm confident that right here we're always loading from file, but both audio loader plugins can also load from memory, meaning that loader->file() will be null. I'm not sure if that's worth fixing, maybe just put a VERIFY() around it.

**Comment by elyse0** [comment]
I think so, it's the only one that keeps a reference to it and could modify it.

Yeah, it would be null if we load from memory but I don't think SoundPlayer (at this moment) can do it.

I just tried VERIFY() but didn't help because when we assign it, it really has a path. Still looking... 🐞

**Comment by swoertz** [comment]
I think the problem here is that the path is stored on the stack and the `Player` stores a `StringView` to it. When the `m_loaded_filename` is accessed again to play it in loop mode the `StringView` points to an object that has been destroyed when the callback returned.
Taking ownership of the `path` should solve the problem (see 08f6619c4797dfc5e036431911ba7dd6cb0999e1).

**Comment by elyse0** [comment]
That makes sense!
