### ISSUE TITLE
WindowServer: Tool windows shouldn't be above *other* applications

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#10970]
How goofy!

![Bildschirmfoto_2021-11-19_23-17-34](https://user-images.githubusercontent.com/2690845/142698628-e66579b4-7513-44c6-829d-d38dc18a7473.png)

**Comment by tomuta** [comment]
Yeah I started working on a fix for this a long time ago in #8900, maybe I can revive it. Basically, I removed the ToolWindow type and instead made tool windows merely a window style. Then, in order to make it stay on top of the "owner" or "parent" it would merely need to be made an accessory window...
