### ISSUE TITLE
this

### ISSUE THREAD

**Issue by PaxtonPenguin** [SerenityOS/serenity#11069]
when rebuilding the toolchain I got this error:
![Capture2](https://user-images.githubusercontent.com/84253355/143325194-a8feb2a3-0b17-41b1-920e-62e81820aa7c.PNG)
(I know its a build error but I cant have a discord)

**Comment by Quaker762** [comment]
Please refrain from clogging up the issue tracker with issues such as these.

If you require support on building, please visit the Discord instead and post in the channel related to building the software.

**Comment by PaxtonPenguin** [comment]
but discord is banned from my ip

**Comment by bgianfo** [comment]
Hey Paxton! 

I think you just need to move your "serenity" folder to a path that doesn't have spaces in it.
The SerenityOS build scripts do not support that at the moment.

I can see you are using WSL from the error message. So I think you need to do the following steps:

```
$ mv "/mnt/c/Users/CJ/Desktop/Paxton's Stuff/serenity" ~/serenity
$ cd ~/serenity/serenity-master
$ git clean -fdx . 
```

This will put you back in a clean state, and you can start following the build directions again.

**Comment by Quaker762** [comment]
@PaxtonPenguin 

Hi Paxton, 

The issue your seeing, as Brian's stated, is because a lot of UNIX tools don't like spaces in paths, unlike what you might be used to on Windows.

If you're having anymore build issues, instead of opening a new issue on Github (which is for development only related issues because as you can see, there are a lot already!), feel free to email me at jooster669@gmail.com and I'll help get you set up :)
