### ISSUE TITLE
Scheduler: Mouse lag when opening multiple applications

### ISSUE THREAD

**Issue by sveilleux1** [SerenityOS/serenity#1113]
The more we open FileManagers and/or Process Explorer the more the mouse input become laggy.

I don't know much about how mouse handling should be implemented inside an Operating System but should it be using it's own "high priority" thread? This way the mouse is always fluid even if the operation system is super busy.

**Comment by bugaevc** [comment]
> I don't know much about how mouse handling should be implemented inside an Operating System but should it be using it's own "high priority" thread? This way the mouse is always fluid even if the operation system is super busy.

That is the case already:

https://github.com/SerenityOS/serenity/blob/d66bbc21ce2b7369d70109c0ce2ce41c01241079/Base/etc/SystemServer.ini#L23-L27

Moreover, opening more apps (that do nothing) should only consume more memory, not more CPU time.

**Comment by bugaevc** [comment]
Yeah I can reproduce this too. The issue, at least with opening tons of SystemMonitor's (that's what its called :smile:) is that each one becomes runnable each second, and since there are so many of them they eat up all of CPU time. But that also means that all the SystemMonitors other than the one that gets this timeslice get their dynamic priority incremented, so they quickly overtake WindowServer.

I'd say SystemMonitor should at least do its polling on a background, low-priority thread. That wouldn't fix that much, since it needs to update the GUI on the main thread anyway.

In general, the scheduler is not optimized for handling a large number of processes w/ different priorities.

**Comment by awesomekling** [comment]
Some other ideas for making SystemMonitor handle this better:

* Disallow multiple instances of SystemMonitor (boring but kinda reasonable.)
* Improve file system locking. All those processes will be racing to grab various fs locks while trying to re-open `/proc/all`. It would be good if you could have multiple simultaneous readers instead of being completely exclusive.
* Don't do the regular updates when the window is occluded. This could be done trivially by making the refresh `CTimer` be a child of the `GWindow`. However, I think that would break CPU usage graph data accumulation.

**Comment by bugaevc** [comment]
There are all mitigations, not fixes (doesn't mean we shouldn't do that).

The fix would be to add some_const/num_threads extra priority to threads we cannot run instead of 1 on each tick, to make the balance between the amount of extra priority you gain between two of your time slices (currently, num_threads) and base priority diffs (think 10) independent of the number of threads.

**Comment by bugaevc** [comment]
And we should also give that extra priority to every thread that did not get to run this timeslice, even if it's not runnable (sleeping or blocking). This way, when you block for a long time waiting for I/O, you react to it sooner -> less latency.

AFAIK Linux does both of these.

**Comment by awesomekling** [comment]
Yeah, fair points @bugaevc those sound like good strategies. We can't use floating point in the kernel but we can just scale up the integer values a bit :)

**Comment by bugaevc** [comment]
> I'd say SystemMonitor should at least do its polling on a background, low-priority thread. That wouldn't fix that much, since it needs to update the GUI on the main thread anyway.

> Don't do the regular updates when the window is occluded. This could be done trivially by making the refresh `CTimer` be a child of the `GWindow`. However, I think that would break CPU usage graph data accumulation.

How about: do collect data in a low-priority thread and unless visible, don't update the UI?

**Comment by bugaevc** [comment]
> All those processes will be racing to grab various fs locks while trying to re-open `/proc/all`.

`CProcessStatisticsReader` could actually skip looking up `/proc` each time if it pre-opened `/proc` and then used `openat("all")`.

Which makes me wonder, is there any way at all in Unix to somehow get some sort of inode handle and then (repeatedly) open it by that handle, without using any paths on the second step. `O_PATH` comes close, but unless the inode is a directory, you cannot use it in a subsequent `openat()`. Any ideas? Guess we could always add our own extension...

**Comment by kleinesfilmroellchen** [comment]
This now seems to be a WindowServer issue, since it only happens if all windows are actually visible and therefore painting. If you put a large window in front of them, the lag disappears although the system load remains rather high.
