### ISSUE TITLE
FileManager: Crash when deleting multiple shift-selected files

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [SerenityOS/serenity#11342]
To replicate:
* Open FM
* Select several files via clicking the first file and then shift-clicking the last file
* Delete the files
* Observe the files being deleted correctly, but FM crashing directly afterwards

This appears to be a LibGUI issue.

Backtrace (my console broke so here's a screenshot)

![image](https://user-images.githubusercontent.com/28656157/146930214-804a4d30-d03a-4937-aa10-a44e74b6deff.png)

**Comment by blishko** [comment]
It looks like this happens when force-deleting files (`Shift+Delete`) and not with simple `Delete` with confirmation dialog.

**Comment by blishko** [comment]
The culprit seems to be access to index out of bounds [here](https://github.com/SerenityOS/serenity/blob/1d08b671ea2dd3186443b19232ec2d5215ebed59/Userland/Libraries/LibGUI/SortingProxyModel.cpp#L212).

**Comment by DemosKadi** [comment]
I did a bit of digging and it seems that the core of the problem is that the selection of the files does not get removed after they get force deleted.
They're supposed to be deselected [here](https://github.com/SerenityOS/serenity/blob/105d55892247c306880d55a550842bd1d05c823a/Userland/Libraries/LibGUI/FileSystemModel.cpp#L425) but the `DirectoryView` is not registered as a view for `FileSystemModel` and so nothing happens. If `DirectoryView` would be an actual view `FileSystemModel` could just be registered as model for this view but it is a `ModelClient`.

**Comment by stefanos82** [comment]
I can reproduce this by simply `shift+delete` on a single file; it crashes immediately.

```
511.593 CrashReporter(82:83): Generating backtrace took 897 ms
511.593 CrashReporter(82:83): --- Backtrace for thread #0 (TID 80) ---
511.593 CrashReporter(82:83): 0x3727402e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
511.593 CrashReporter(82:83): 0x148ec8a4: [libc.so] raise +0x24 (syscall.h:35 => signal.cpp:22 => signal.cpp:37)
511.597 CrashReporter(82:83): 0x148d7a69: [libc.so] abort +0x29 (stdlib.cpp:221)
511.597 CrashReporter(82:83): 0x148d84fc: [libc.so] __assertion_failed +0x6c (assert.cpp:33)
511.597 CrashReporter(82:83): 0x33f18c1c: [libgui.so.serenity] AK::Function<void (GUI::AbstractView&)>::CallableWrapper<GUI::SortingProxyModel::sort_mapping(GUI::SortingProxyModel::Mapping&, int, GUI::SortOrder)::{lambda(GUI::AbstractView&)#2}>::call(GUI::AbstractView&) +0x1ec (Vector.h:139 => Vector.h:147 => Iterator.h:56 => ModelSelection.h:50 => SortingProxyModel.cpp:197)
511.601 CrashReporter(82:83): 0x33ef08b6: [libgui.so.serenity] GUI::Model::for_each_view(AK::Function<void (GUI::AbstractView&)>) +0x76 (Function.h:91)
511.601 CrashReporter(82:83): 0x33f18648: [libgui.so.serenity] GUI::SortingProxyModel::sort_mapping(GUI::SortingProxyModel::Mapping&, int, GUI::SortOrder) [clone .localalias] +0x158 (SortingProxyModel.cpp:192)
511.601 CrashReporter(82:83): 0x33f18916: [libgui.so.serenity] GUI::SortingProxyModel::sort(int, GUI::SortOrder) +0x56 (SortingProxyModel.cpp:229)
511.601 CrashReporter(82:83): 0x33f17d2e: [libgui.so.serenity] GUI::SortingProxyModel::update_sort(unsigned int) [clone .localalias] +0x3e (SortingProxyModel.cpp:34)
511.605 CrashReporter(82:83): 0x33ef0a26: [libgui.so.serenity] GUI::Model::for_each_client(AK::Function<void (GUI::ModelClient&)>) +0x76 (Function.h:91)
511.605 CrashReporter(82:83): 0x33ef0b80: [libgui.so.serenity] GUI::Model::did_update(unsigned int) [clone .localalias] +0x60 (Model.cpp:54)
511.605 CrashReporter(82:83): 0x33eb4e45: [libgui.so.serenity] GUI::FileSystemModel::handle_file_event(Core::FileWatcherEvent const&) [clone .part.0] +0x55 (FileSystemModel.cpp:446)
511.605 CrashReporter(82:83): 0x98eb0d06: [libcore.so.serenity] AK::Function<void ()>::CallableWrapper<Core::FileWatcher::FileWatcher(int, AK::NonnullRefPtr<Core::Notifier>)::{lambda()#1}>::call() +0xd6 (Function.h:91)
511.610 CrashReporter(82:83): 0x98ebe129: [libcore.so.serenity] Core::Notifier::event(Core::Event&) +0x99 (Function.h:91)
511.610 CrashReporter(82:83): 0x98ebf460: [libcore.so.serenity] Core::Object::dispatch_event(Core::Event&, Core::Object*) +0xb0 (Object.cpp:219)
511.610 CrashReporter(82:83): 0x98ea9a4e: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x17e (EventLoop.cpp:415)
511.613 CrashReporter(82:83): 0x98eaa5fa: [libcore.so.serenity] Core::EventLoop::exec() +0x6a (EventLoop.cpp:372)
511.613 CrashReporter(82:83): 0x33e61ae7: [libgui.so.serenity] GUI::Application::exec() +0x27 (Application.cpp:119)
511.613 CrashReporter(82:83): 0x83e40e6a: [/bin/FileManager] run_in_windowed_mode(AK::String const&, AK::String const&) +0x5b2a (main.cpp:1319)
511.613 CrashReporter(82:83): 0x83e42230: [/bin/FileManager] serenity_main(Main::Arguments) +0x840 (main.cpp:128)
511.613 CrashReporter(82:83): 0xaf7331d2: [libmain.so.serenity] main +0x72 (Main.cpp:20)
511.613 CrashReporter(82:83): 0x83e1a32c: [/bin/FileManager] _entry +0x5c (crt0.cpp:46)
512.534 [#0 SyncTask(3:3)]: Ext2FS: Flushed 2 blocks to disk
```

**Comment by sin-ack** [comment]
The problem here has to do with how Serenity's models currently works. Right now, when a change in the data source happens, we end up completely invalidating all indices. `FileSystemModel` is the first model which uses `FileWatcher` to figure out _exactly_ what changed, and emits granular updates instead of a full invalidation. The problem is that, to do this and not break stuff in i.e. HackStudio, a hack was added to reach into the views and manually invalidate indices, but that doesn't work when `FileSystemModel` is behind a `SortingProxyModel`; there, `FileSystemModel` has no views because `SortingProxyModel` does instead. `SortingProxyModel` currently does not handle granular updates from the model it's subscribed to and assumes that either the indices are exactly where they are or that everything changed. This is what causes this bug to happen. For this to be properly fixed, we need to evaluate all the models and views in the system and use the `PersistentModelIndex` class where appropriate, and start using granular updates whereever we can.

**Comment by stefanos82** [comment]
> The problem here has to do with how Serenity's models currently work. Right now, when a change in the data source happens, we end up completely invalidating all indices. `FileSystemModel` is the first model which uses `FileWatcher` to figure out _exactly_ what changed, and emits granular updates instead of a full invalidation. The problem is that, to do this and not break stuff in i.e. HackStudio, a hack was added to reach into the views and manually invalidate indices, but that doesn't work when `FileSystemModel` is behind a `SortingProxyModel`; there, `FileSystemModel` has no views because `SortingProxyModel` does instead. `SortingProxyModel` currently does not handle granular updates from the model it's subscribed to and assumes that either the indices are exactly where they are or that everything changed. This is what causes this bug to happen. For this to be properly fixed, we need to evaluate all the models and views in the system and use the `PersistentModelIndex` class where appropriate, and start using granular updates whereever we can.

Oh wow, it goes deeper than I originally thought.

Thank you @sin-ack for the detailed answer, I appreciate it :+1:

**Comment by AtkinsSJ** [comment]
I can't get it to crash with shift-deleting files so I think this is fixed.
