### ISSUE TITLE
LibRegex: Negative lookaheads seem to only consider the last alternative (if not duplicated)

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#11350]
For example:
```js
/:(?!\^\)|1)/.exec(":^)") // [":"]
```
And doesn't match:
```js
/:(?!\^\)|1)/.exec(":1") // null
```
If you swap `^)` and `1`, it doesn't match:
```js
/:(?!1|\^\))/.exec(":^)") // null
```
If you duplicate the `1` alternative, it matches:
```js
/:(?!\^\)|1|1)/.exec(":1") // [":"]
```
Same for duplicating `^)`:
```js
/:(?!1|\^\)|\^\))/.exec(":^)") // [":"]
```

**Comment by alimpfard** [comment]
After a bit of thinking, banging my head on the table, and a lot of water, I think I've found the problem (no nice solution yet).
negative lookaheads work by saving the current state, executing the thing that _shouldn't_ be there, and then immediately running a `FailForks 2`.

That works fine if the lookahead is nested only one level deep (i.e. it's one fork away from the toplevel of the group that would fail if it matches), but if it's nested any deeper like in your example, it will still only fail two forks, giving us the wrong result.

One possible solution is to fail 1 + as many forks as we've taken since the last `Save` opcode, but that's even more state in `MatchState`, which is already quite large...

**Comment by alimpfard** [comment]
For reference, https://github.com/alimpfard/serenity/tree/11350 implements that.
Tests pass, but I'm not sure what the allocation footprint on large patterns is. yet.

**Comment by alimpfard** [comment]
Memory footprint is reasonable, I'll make a PR.
