### ISSUE TITLE
Filemanager: Select all selects way more than expected.

### ISSUE THREAD

**Issue by DAlperin** [SerenityOS/serenity#1149]
Ctrl+A in any file manager view selects way more than the files in the current view. Selecting all with Ctrl+A in the home directory selects 81 items.
![Screenshot from 2020-01-29 19-59-10](https://user-images.githubusercontent.com/16063713/73411068-16204380-42d2-11ea-86a8-72ed05c37e7f.png)

**Comment by bugaevc** [comment]
This is because `select_all()` implementation is wrong:

https://github.com/SerenityOS/serenity/blob/831ff2d0ac8d2d19d4ab3c6b870fc3ffa9da1c5c/Libraries/LibGUI/GAbstractView.cpp#L126-L136

It shouldn't loop over columns. Since `GAbstractView` doesn't know which column it displays (maybe multiple), perhaps this method's implementation should be moved down to subclasses.

**Comment by DAlperin** [comment]
Maybe each view should be responsible for implementing its own select all? I think this actually makes the most sense because it allows for more complex select all behaviors in things like a GAbstractTableView where the selected column changes the select all behavior. I can take a crack at this.

**Comment by bugaevc** [comment]
That's what I've said, yeah.

**Comment by DAlperin** [comment]
My bad, I was very tired when I read that initially. Thanks for the idea.

**Comment by DAlperin** [comment]
Closed by #1201
