### ISSUE TITLE
TelnetServer(+TTY?): Pressing Enter (<CR><NUL>) doesn't work

### ISSUE THREAD

**Issue by aatosmajava** [SerenityOS/serenity#11569]
### Steps to reproduce

Start the server inside Serenity:
```sh
TelnetServer -p 8000
```

Connect to it on the host:
```sh
telnet 127.0.0.1 8000
```

Type a command e.g. `ls` and press Enter. The command doesn't run.

The interesting output is the following. (I have `TTY_DEBUG` turned on.)
```sh
[#0 TelnetServer(50:50)]: /dev/pts/1: VINFO pressed!
[#0 TelnetServer(50:50)]: /dev/pts/1: Send signal 30 to everyone in pgrp 51
[#0 TelnetServer(50:50)]: /dev/pts/1: Send signal 30 to Shell(51)
```

My host is Ubuntu and by default `telnet` sends `<CR><NUL>` when pressing Enter.

I have a hunch that the problem might be in `Parser.cpp` around line 27:
```c++
default:
    if (on_data)
        on_data(StringView(&ch, 1));
    break;
```

I think this creates a `StringView` with length 1 and a null character as the contents, which is then forwared to:
```cpp
void Client::handle_data(StringView data)
{
    write(m_ptm_fd, data.characters_without_null_termination(), data.length());
}
```

One hack to fix it, is to just ignore the character:
```cpp
case '\0':
    break;
default:
    if (on_data)
        on_data(StringView(&ch, 1));
    break;
```

But this can't be correct, right?

**Comment by mikolysz** [comment]
> One hack to fix it, is to just ignore the character:
> But this can't be correct, right?

It actually is correct. To accommodate old terminals, which might handle <CR><LF> differently than a single <CR>, the [Telnet RFC](https://datatracker.ietf.org/doc/html/rfc854) requires that a <CR> be followed either by an <LF> or a <NULL>. This is done so that, if the <CR> is the last character we send, the receiving side is able to decide whether to use the <CR> logic or the <CR><LF> logic without waiting for further input from our side. The RFC explicitly says that the receiving side should strip those nulls when it sees them.

**Comment by aatosmajava** [comment]
Thank you for the input, @mikolysz.

Github's Markdown seems to have eaten the special characters from your comment, but I think I got it:

> Telnet RFC requires that a `<CR>` be followed either by `<LF>` an or a `<NUL>`. 

I also noticed, when using `<CR><LR>` as the Enter sequence, we get one too many linebreaks:
```bash
telnet 127.0.0.1 8000
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
courage:~ $ 
telnet> toggle crlf
Will send carriage returns as telnet <CR><LF>.
courage:~ $ true
courage:~ $ 
courage:~ $ true
courage:~ $ 
courage:~ $ 

```
I'll see if I can open a PR for one solution the problem later.
