### ISSUE TITLE
Userland: passwd utility

### ISSUE THREAD

**Issue by JonArcherII** [SerenityOS/serenity#1168]
Now that we have a `useradd` utility, it would be nice to have a matching `passwd`!

**Comment by bugaevc** [comment]
@Quaker762

**Comment by JustBeYou** [comment]
I am willing to start contributing to some open source projects and SerenityOS looks really cool. 
If no one is working on this, could I be assigned?

**Comment by Quaker762** [comment]
@JustBeYou Go for it mate!

**Comment by JustBeYou** [comment]
As I see, user passwords are not handled in any way until now. There is a field in `struct passwd` named `pw_passwd`, but it is never used. [see struct here](https://github.com/SerenityOS/serenity/blob/master/Libraries/LibC/pwd.h#L37)

Writing `passwd` utility would also require:
* to modify `pwd.cpp` in order to handle password writing to `/etc/shadow`
* to modify `su` program to ask for a password

**Comment by JustBeYou** [comment]
As I see, Serenity has no crypto built-in library. I need hashing functions in order to store passwords securely. As OpenSSL is already ported I could use that, but I don't think it's ok to rely on an external package for a default program of the system.

Should we add a small `LibCrypto` to the project or use  `OpenSSL`?

**Comment by JonArcherII** [comment]
I would get @awesomekling's opinion, he would probably want Serenity to have its own `LibCrypto`, but he probably has insight on how it should be made.

**Comment by jcs** [comment]
A password hashing algorithm needs to be chosen as well.  I vote for scrypt.

**Comment by awesomekling** [comment]
The base system should not have any 3rd party dependencies other than a compiler. So a `LibCrypto` would indeed be the right thing here :)

**Comment by JustBeYou** [comment]
@jcs There are 5 default hashing algorithms that must be supported as I know. 
```
    $1$ is MD5
    $2a$ is Blowfish
    $2y$ is Blowfish
    $5$ is SHA-256
    $6$ is SHA-512
```
Choosing a default one from those I think it's good enough as those are cryptographically secure. 

@awesomekling should I open a new issue regarding `LibCrypto` to talk about design and implementation? Then this issue will be mostly done too.

**Comment by jcs** [comment]
@JustBeYou not all of them need to be supported, just the one that the OS uses (I've never seen an OS have multiple types of hashes in its password file).  For example, OpenBSD's `crypt()` function:

````
char *
crypt(const char *key, const char *setting)
{
        if (setting[0] == '$') {
                switch (setting[1]) {
                case '2':
                        return bcrypt(key, setting);
                default:
                        errno = EINVAL;
                        return (NULL);
                }
        }
        errno = EINVAL;
        return (NULL);
}
````
