### ISSUE TITLE
GMLPlayground: "Format GML" action incorrectly marks the file as unchanged

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#11810]
## Steps to reproduce:
1. Open GML Playground.
2. Save the file somewhere.
3. Make some random changes.
4. Notice that the window title and close button indicate that the changes are unsaved.
5. Use `Edit > Format GML`.
6. Notice that the unsaved-changes indicators in the window title and close button are gone.
7. Exit GML Playground.
8. Re-open your saved file, to see that your modifications are not there.

## What should happen:
The `Edit > Format GML` action should mark the file as *changed*, not *unchanged*.

**Comment by SimonFJ20** [comment]
I think the underlying issue is the `m_undo_stack.clear();` in /Userland/Libraries/LibGUI/TextDocument.cpp just before the last return.

https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibGUI/TextDocument.cpp#L41-L99

By clicking Format GML, the hanlder calls `TextEditor::set_text()`, which calls `TextDocument::set_text()`, which runs `m_undo_stack.clear()`. My understanding of this is that, when loading new files into the text editor document, we dont want to be able to undo to the previous file.

I dont know what the right action is here, either a boolean argument `bool clear_state` to `TextDocument::set_text()` and `TextEditor::set_text()`, or new methods called `::modify_text()` inwhich we dont clear the undo stack.
