### ISSUE TITLE
No rule to make target clean

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#1192]
This is 6a9cc66b976653bf5f0440a6071b736d6d41c183 on macOS 10.14.

```
./makeall.sh
Password:
uid=0(root) gid=0(wheel) groups=0(wheel),1(daemon),2(kmem),3(sys),4(tty),5(operator),8(procview),9(procmod),12(everyone),20(staff),29(certusers),61(localaccounts),80(admin),333(piavpn),33(_appstore),98(_lpadmin),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),701(com.apple.sharepoint.group.1)
LibAudio: CLEAN
LibC: CLEAN
LibCore: CLEAN
make[2]: *** No rule to make target `clean'.  Stop.
make[1]: *** [LibDraw/..clean] Error 2
make: *** [Libraries.clean] Error 2
```

Also usually `makeall.sh` script asks for root password twice - at the beginning and almost at the very end. Any idea how to suppress it?

**Comment by awesomekling** [comment]
You can fix the build by doing `rm -r Libraries/LibDraw`

The `makeall.sh` thing is a separate issue. It asks for the root password up front since most people have `sudo` configured to cache the permissions for a while after a successful access. I'm not sure how to solve that as I'm not using macOS.

**Comment by diversys** [comment]
That did the trick, thanks :)
