### ISSUE TITLE
Keyboard control and the GUI lib

### ISSUE THREAD

**Issue by faissaloo** [SerenityOS/serenity#122]
In my browser I have a plugin called SurfingKeys, this makes it extremely easy to navigate the internet with just my keyboard and I think is a great way to navigate GUIs in most cases as opposed to mice.
![image](https://user-images.githubusercontent.com/8840681/58420691-e3a8b180-8085-11e9-8dc0-1bfd62592aee.png)  
  
I propose that some sort of system be added whereby keybinds will be bound to widgets automatically without the need for developer intervention (but of course a developer should be able to customise the keybinds if they wish). This would provide the system with extremely good ergonomics and I think one of the great advantages of having these sorts of unifying libraries is that you can provide this sort of universal functionality.

**Comment by christopherdumas** [comment]
Huh, this could be really interesting. The only issue is that if a developer rebound certain keys, all the other ones would probably have to shift. Also we'd definitely need to do some sort of overlay, but that doesn't seem so hard at first glance.

Would you want to take a crack at it yourself? LibGUI is pretty much where all of this will need to happen.

**Comment by faissaloo** [comment]
I was intending to do so, just wanted confirmation this is inline with the project vision, it just depends when I have free time.

**Comment by christopherdumas** [comment]
I dont really have any say in project vision at the moment, being a latecomer and all. If I had to guess what Kling will say, probably not? I have no idea.

Also I asked if you wanted to work on it because I kind of want to work on it too. (:

**Comment by faissaloo** [comment]
Well it'll probably be a bit big so if you want to get started on it and Kling wants this then feel free, just make sure you put up a draft pull request so I can see where you're at and chip in.

**Comment by christopherdumas** [comment]
Ok. I'm currently working on a large PR myself at the moment (for configuration options) so it might be a bit until I can work on this. (:

**Comment by awesomekling** [comment]
I'm not a huge fan of auto-generated user interfaces, but I think we can find a way to adapt this idea to the Serenity concept. :)

So I do agree that we should have per-widget keyboard shortcuts, however I think they should be defined manually rather than auto-generated. Auto-generation makes sense in a web browser where you have very little control over the content, but here we have 100% control so we should be able to make sensible decisions (in theory at least :)

Surfacing the shortcuts visually with a keyboard gesture seems like a cool feature. Perhaps if you double tap "Alt", every widget would automatically get a little label that tells you what shortcut would activate that widget.

Code-wise, I think each GWidget should have a GShortcut. Currently GShortcuts are tied to GActions, and actions are registered either per-window or per-application. A better design would be having shortcuts registered per-widget, per-window and per-application (depending on their "shortcut scope")

I'm not sure how to distinguish between intents when activating a widget, how do we know if the user wants to focus a button, or "click" the button?

**Comment by christopherdumas** [comment]
I was thinking that each button gets an identifier (a letter or number), and then Alt+the id focuses it, and Super+the id clicks it? Honestly though, it only really makes sense to do one of those at a time. Like, a textbox we always want to focus, and buttons always want to be clicked.

**Comment by faissaloo** [comment]
>however I think they should be defined manually rather than auto-generated  
  
Manual definition means that either:
 - Developers won't implement it out of laziness  
 - Developers are going to have to be forced to do it and it will become a thorn in their side  

I think both these options are considerably worse compared to automatic definitions that can be overridden.  

>I'm not a huge fan of auto-generated user interfaces  
  
I don't believe this is really that much more autogenerated than the UI itself.  
  
>Perhaps if you double tap "Alt"  
  
Double tapping a key is one keystroke too many, SurfingKeys uses escape similar to Vim and I think this works well.  
  
>I'm not sure how to distinguish between intents when activating a widget, how do we know if the user wants to focus a button, or "click" the button?  
  
Focusing of widgets becomes redundant when keyboard control exists, focusing exists to indicate that the user can interact with a widget, here a user already knows the widget can be interacted with because the shortcut for will be visible.  

Here's a mockup I made of what I'm imagining:
![image](https://user-images.githubusercontent.com/8840681/58432868-81af7280-80ac-11e9-97c9-427590c340d0.png)

**Comment by awesomekling** [comment]
All right, well this is not a feature I would likely use, but I'm not gonna stop you from implementing it. :)

If you write it cleanly and design it in a way that integrates with LibGUI in a non-invasive way then I don't see why we couldn't have this. (By non-invasive I mean that the popups are all drawn at the same level (probably after paint in GWindow), using information provided through some virtual interface that all GWidgets can implement.)
