### ISSUE TITLE
LibWeb: SVG images are often the wrong size

### ISSUE THREAD

**Issue by AtkinsSJ** [SerenityOS/serenity#12243]
`<svg>` elements can have a `viewBox` attribute as well as a `width` and `height`. This defines a coordinate system that is then used for rendering. (See https://svgwg.org/svg2-draft/coords.html)

It looks like while we do _parse_ the `viewBox`, we don't use it! `SVGSVGElement::view_box()` is never called. I believe what needs to be done is to modify `SVGPathBox::paint()` so that it maps the coordinates (which are relative to the view_box) to screen coordinates (relative to the size of the `<svg>` element).

For example, here is the icon for https://getbootstrap.com in Firefox:
![image](https://user-images.githubusercontent.com/222642/151997968-1156191d-d575-446f-aca0-db42e638761e.png)

And here it is in Browser:
![image](https://user-images.githubusercontent.com/222642/151997849-4e31f46e-fc31-40f2-9d38-d138113a68f8.png)
Note that it's 118px by 94px, which is exactly the viewBox size:
```
<svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="d-block my-1" viewBox="0 0 118 94" role="img">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="... stuff here ..." fill="currentColor"/></svg>
```

**Comment by ben-abraham** [comment]
Looked at this a bit, the FIXME in `SVGFormattingContext.cpp` is almost certainly the culprit here, since it just sets the context bounds to the bounding box of what's drawn in the SVG.
Also not sure if this is related to the problem, but when I inspect an element in the inspector it seems to not have the width/height properties defined, despite them being directly on the element.
I couldn't find an element this did work for however, so it might just be a broken feature. (Same thing under styles tab)
![image](https://user-images.githubusercontent.com/793454/154211237-b462ed0e-2558-4a15-a24f-3e001e809831.png)

**Comment by AtkinsSJ** [comment]
#12578 fixes the non-viewbox part of this.
