### ISSUE TITLE
LibWeb: HTMLParser crash in handle_in_select

### ISSUE THREAD

**Issue by nbvdkamp** [SerenityOS/serenity#12658]
The snippet `<select><option></select>` crashes the HTML parser with this stacktrace:
```
ASSERTION FAILED: m_parsing_fragment
../../Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp:2535

0x0a92502e: [libsystem.so] syscall2 +0xe (syscall.cpp:25 => syscall.cpp:24)
0x0d198b24: [libc.so] raise +0x24 (syscall.h:35 => signal.cpp:22 => signal.cpp:37)
0x0d17db59: [libc.so] abort +0x29 (stdlib.cpp:220)
0x0d18468c: [libc.so] __assertion_failed +0x6c (assert.cpp:33)
0x41c75dd5: [libweb.so.serenity] Web::HTML::HTMLParser::handle_in_select(Web::HTML::HTMLToken&) [clone .localalias] +0x805 (HTMLParser.cpp:2535)
0x41c7730b: [libweb.so.serenity] Web::HTML::HTMLParser::run(AK::URL const&) [clone .localalias] +0x58b (HTMLParser.cpp:174)
0x41ce4f6d: [libweb.so.serenity] Web::FrameLoader::load_html(AK::StringView, AK::URL const&) +0xbd (FrameLoader.cpp:230)
0x41d1043d: [libweb.so.serenity] Web::Page::load_html(AK::StringView, AK::URL const&) +0x2d (Page.cpp:46)
0x26ada858: [/bin/WebContent] .L4475 +0x68 (ClientConnection.cpp:97 => WebContentServerEndpoint.h:2523)
0xa4a4a532: [libipc.so.serenity] IPC::ConnectionBase::handle_messages() +0x102 (Connection.cpp:95)
0xa4ae1165: [libcore.so.serenity] AK::Function<void ()>::CallableWrapper<Core::Object::deferred_invoke(AK::Function<void ()>)::{lambda()#1}>::call() +0x245 (Function.h:91)
0xa4aca778: [libcore.so.serenity] Core::EventLoop::pump(Core::EventLoop::WaitMode) [clone .localalias] +0x2a8 (Function.h:91)
0xa4acafaa: [libcore.so.serenity] Core::EventLoop::exec() +0x11a (EventLoop.cpp:428)
0x26add6af: [/bin/WebContent] serenity_main(Main::Arguments) +0x1ef (main.cpp:26)
0x1daff1e7: [libmain.so.serenity] main +0x77 (Main.cpp:23)
0x26ac4c55: [/bin/WebContent] _entry +0x65 (crt0.cpp:49)
```
It seems like this
https://github.com/SerenityOS/serenity/blob/eca8208a345858ef2e132623af08b885a43c7ad4/Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp#L3135
 is the only place where `m_parsing_fragment` is set to true. I am not sure why this is the expected state for that [`VERIFY`](https://github.com/SerenityOS/serenity/blob/eca8208a345858ef2e132623af08b885a43c7ad4/Userland/Libraries/LibWeb/HTML/Parser/HTMLParser.cpp#L2535) or how this should work exactly.

**Comment by paulwratt** [comment]
> it seems like Line 3135 is the only place where m_parsing_fragment is set to true. I am not sure why this is the expected state for that VERIFY or how this should work exactly.

Thats in `HTMLParser::parse_html_fragment(DOM::Element& context_element, StringView markup)`, which is why it is set TRUE.

However the VERIFY at Line 2535 in `HTMLParser::handle_in_select(HTMLToken& token)`, and if you scroll down there are some messy (IMO) SELECT "pop"s inside various other elements (INPU, KEYGEN and TEXTAREA). It also appears that VERIFY is in a check for the /SELECT end tag, and that is also positioned _before_ the start check (this might be irrelavant).

What was the original context of the test HTML page?

If its was literally `<select><option></select>` then its possible that /OPTION was never set because there is also no VALUE set for that OPTION. (The OPTION and GROUP OPTION checks are further up at 2491 - 2531 )
