### ISSUE TITLE
unicode.org downloads?

### ISSUE THREAD

**Issue by srl295** [SerenityOS/serenity#13531]
download questions:

in https://github.com/SerenityOS/serenity/blob/66e7ac19546b1158c7fd3ce8e088b0ad5f385a33/Meta/CMake/unicode_data.cmake and in trying to build I notice that each .txt file is downloaded separately from unicode.org…  couldn't you download UCD.zip instead?

also `41.0.0` is now tagged for cldr-json, it is not released yet formally, but would you be able to test?

**Comment by linusg** [comment]
cc @trflynn89

**Comment by trflynn89** [comment]
Hey Steven - yeah, in the beginning, we were only using UnicodeData.txt for a while, so it made sense to download the single file instead of the whole .zip. Additional files were added individually over time, to the point that now we should switch it to download the zip instead.

A PR to switch to CLDR 41 is here: https://github.com/SerenityOS/serenity/pull/13537
All of our own tests pass with it, and there weren't any [test262 Intl](https://github.com/tc39/test262/tree/main/test/intl402) regressions, so it looks good from our end :)

**Comment by srl295** [comment]
Wow great to hear! Wait till it’s released though as CLDR if you could.

**Comment by trflynn89** [comment]
Sure thing!

**Comment by archanox** [comment]
Fixed in https://github.com/SerenityOS/serenity/pull/13545
