### ISSUE TITLE
FontEditor: Verify if glyph U+FFFD exists in loaded font file

### ISSUE THREAD

**Issue by djwisdom** [SerenityOS/serenity#13672]
This feature will aid in ensuring that **mandatory glyph** exists as recommended on http://wiki.serenityos.net/fonts.html under section Creating a font.

Font Editor can display dialog box informing user of the situation. Font Editor can also add the  words *MISSING U+FFFD GLYPH" on the application status bar or title bar wherever which location makes sense.

**Comment by Xexxa** [comment]
U+FFFD `�` falls back on U+003F `?` if it does not exist.

Because it's our primary .notdef glyph I consider it "mandatory". That's why it's in the wiki and clearly labeled on https://fonts.serenityos.net/LizaBlack10, I draw that conclusion from the [source code](https://github.com/SerenityOS/serenity/blob/4cbbb72ce8fb32f0fec5ae45719d48432da6d68e/Userland/Libraries/LibGfx/Font/BitmapFont.cpp#L253)

IIRC there has been talk in our community about replacing the replacement character with something else, couldn't find the discussion after a quick look. But the replacement character is primary used for encoding errors nowadays according to [wikipedia](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character).

So, until we know if FFFD has a future I'm not sure if it's worth implementing. ¯\_(ツ)_/¯

**Comment by djwisdom** [comment]
Sounds good to me.  Closing issue.
