### ISSUE TITLE
Ports: Some utilities don't work in the GNU core utilities package

### ISSUE THREAD

**Issue by supercomputer7** [SerenityOS/serenity#13690]
After #13333 was merged, I tested the package and found that some utilities are not working.
The ones are (for now) `df`, `who` and `users`. For `who` and `users` it seems like we don't have `/etc/utmp` file. `df` is obviously expecting a procfs node in a certain format (i.e. not JSON-formatted output). So it might be that some utils will never function correctly on SerenityOS from the GNU core utils package.

cc @timschumi

**Comment by timschumi** [comment]
Except for things that are mandated by POSIX, are we even going to do something to make those utilities work? As mentioned in the initial PR, I consider this more of a POSIX-benchmark rather than a full set of utilities that should be used productively.

That said, we should probably remove non-working utilities just in case someone tries to work with this productively.

**Comment by supercomputer7** [comment]
> Except for things that are mandated by POSIX, are we even going to do something to make those utilities work? As mentioned in the initial PR, I consider this more of a POSIX-benchmark rather than a full set of utilities that should be used productively.
> 
> That said, we should probably remove non-working utilities just in case someone tries to work with this productively.

When I opened this issue, I thought the same thing - are we going to fix these utils? probably not. Should we remove them from the package? probably yes. I'm not too much familiar with the port package, so one of us can take this as a task to improve this specific port.
