### ISSUE TITLE
LibRegex: `[\S\s]` doesn't match first character of string

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#13755]
```js
> /[\S\s]/.exec("hello")
// expected: [ "h" ]
// actual: null
```

`url-parse` uses this to get the protocol of a URL in the first group and the rest of the URL in the last group:
```
> regex = /^([a-z][a-z0-9.+-]*:)?(\/\/)?([\S\s]*)/i;
> url = "https://pixel.vkoskiv.com/sockjs-node"
> regex.exec(url)
// expected: [ "https://pixel.vkoskiv.com/sockjs-node", "https:", "//", "pixel.vkoskiv.com/sockjs-node" ]
// actual: [ "https://", "https:", "//", "" ]
```

Note that flipping them makes it work:
```
> /[\s\S]/.exec("hello")
[ "h" ]
```

**Comment by damienfir** [comment]
Some notes I gathered while debugging this issue.

It matches the space if it follows the word:
```
> /[\S\s]/.exec("hello ")
[ " " ]
> /[\s\S]/.exec("hello ")
[ "h" ]
```

Same issue with another CharClass, for example digits:
```
> /[\D\d]/.exec("a")
null
> /[\d\D]/.exec("a")
[ "a" ]
```

The issue can be fixed by putting the following statement inside the previous loop:
https://github.com/SerenityOS/serenity/blob/612dbdc671ac62cc3ddaf2277d29bf715f1edff3/Userland/Libraries/LibRegex/RegexByteCode.cpp#L603-L604
But it breaks some other tests in `ECMA262_property_match`:
https://github.com/SerenityOS/serenity/blob/612dbdc671ac62cc3ddaf2277d29bf715f1edff3/Tests/LibRegex/Regex.cpp#L767

**Comment by alimpfard** [comment]
Yep, @damienfir you were pretty damn close, just need to skip the check for the Inverse and TemporaryInverse ops themselves and to make sure that we don't eat two characters at the end :^)

**Comment by damienfir** [comment]
Indeed, pretty close !
Thanks for the credit.
