### ISSUE TITLE
Help: Application icons are misaligned

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#13910]
Might be an issue with the generated HTML / styles, or a rendering bug in LibWeb.

![image](https://user-images.githubusercontent.com/19366641/166746340-a7c27328-469b-4ae8-a2ce-40b8a16f2ec5.png)

vs man.serenityos.org:

![image](https://user-images.githubusercontent.com/19366641/166746426-0f056877-d409-4fbb-bd9e-a2f2b52cb385.png)

**Comment by JsFlo** [comment]
fwiw it looks like this generates the same html for that line (same on my browser and the serenity rendered one) 
```
<p><img src="[../icons/16x16/ladyball.png](view-source:http://man.serenityos.org/icons/16x16/ladyball.png)" alt="Icon" /> About - About SerenityOS</p>
```
and functions the same way if you scale this image up on  man.serenityos.org (the icon will be larger than the text and text is aligned at the bottom).  So I guess this rules out the generated html

Could this just be due to the default text size differences ? (could still be an issue, maybe there's some standard that the text should be a certain height and/or we're not rendering one of the components correctly)

**Comment by premek** [comment]
I think it looks OK in Help currently.

I took screenshots in Help, man.serenityos.org in Browser and in Chrome

In Chrome the text is larger but in all three the bottom is aligned the same with the text. There is 1px between the bottom of the icon and the text base line (see the blue line that I added in the screenshots below)

![helpicons](https://user-images.githubusercontent.com/1145361/198846127-13a8ebd5-e5e1-4661-9636-a57d53007c4e.png)

**Comment by linusg** [comment]
We could use some flexbox shenanigans to achieve universal centered vertical alignment, but this seems ok. Thanks for checking!
