### ISSUE TITLE
Desktop background artifacts/distortion when opening the context menu

### ISSUE THREAD

**Issue by diath** [SerenityOS/serenity#14106]
Steps to reproduce:
* Boot SerenityOS
* Change the wallpaper to `sunset-retro.png`
* Change the resolution to anything other than `1024x768`
* Right and left click around the desktop to open and close the desktop context menu repeatedly

What I'm observing as a result is the pixels randomly shifting and distorting around the desktop when opening the context menu, and shifting back into their place when closing the menu. This does not happen with the default resolution.

https://user-images.githubusercontent.com/1154021/170528848-08c0ce20-9e53-4cfa-bb2f-4003c7673de5.mp4

**Comment by tomuta** [comment]
That's because scaled blits changed some time ago and isn't very consistent when portions adjacent are blit together.

There's also a hack in WindowServer that used to mask a similar effect before the scaled blit algorithm was changed, which now doesn't seem to make much of a difference anymore, and as part of a fix for this issue this hack (this one line) should be removed as well:

https://github.com/SerenityOS/serenity/blob/d1c9089fcde5d249bf15308503d3556d9a1dd22f/Userland/Services/WindowServer/Compositor.cpp#L306
