### ISSUE TITLE
DisplaySettings: Screen name contains rogue '@@@' on bare metal

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#14139]
Likely related:

```
DisplaySettings(74:74): EDID checksum mismatch, data may be corrupted!
```

![IMG_20220529_232200](https://user-images.githubusercontent.com/19366641/170893701-8e32aaa6-b15b-412e-bfd2-6d2745e117fc.jpg)

**Comment by linusg** [comment]
cc @supercomputer7

**Comment by supercomputer7** [comment]
This EDID is "fake", because you have no real driver to actually fetch the real EDID for you, so the kernel puts a mock EDID just to keep everything consistent. As for the weird `@@@` string, we can probably just remove it, but it's not a bug (it doesn't indicate the kernel did something wrong anyway).
