### ISSUE TITLE
Applications: Window title format

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#1444]
Applications currently use two kinds of window title formats when an opened document/resource is present:

* "Document - AppName" (HackStudio, Browser, ...)
* "AppName: Document" (TextEditor, FileManager, ...)

Would be nice to choose a single format for consistency. Both of them are okay choices, so the question is which one to standardize on.

**Comment by oriko1010** [comment]
I'd suggest the former because the most significant part comes first in case you have a really tiny window for some reason.

I would also like to change HackStudio to use "Document - ProjectName - AppName" which to me looks way better than "AppName: ProjectName: Document" (assuming that is a desired change).

**Comment by awesomekling** [comment]
Totally agree with @oriko1010. It will also look better in the taskbar. :)
