### ISSUE TITLE
Commiting memory pages to processes which might never be used.

### ISSUE THREAD

**Issue by Domkeykong** [SerenityOS/serenity#14915]
From the lowmem kernel exploration video Kling explained that when a process asks for memory the kernel will commit the required pages to the process. But this has a huge issue, especially then when a process requests a large amount of memory and never uses it, as it will starve the system for available memory and in the worst case OOMing the system.
An idea on how to fix this potential issue is to only commit pages the process has written to.
Note that reading from uninitialized memory is undefined in most if not all programming languages thus the system does not need to commit those pages.

**Comment by awesomekling** [comment]
I don't understand this issue. Committing memory to an allocator means that we *can't* just give it to someone else just because it hasn't been written yet. That would violate the commitment.

Lying to processes and saying "don't worry, there is infinite memory" is a common design, but I'm interested in looking for alternatives instead of replicating it.
