### ISSUE TITLE
Port Qt to Serenity

### ISSUE THREAD

**Issue by rburchell** [SerenityOS/serenity#152]
- [x] sysconf(_SC_PAGESIZE) fails (from pcre) -- skippable, but should be fixed
- [ ] std::wstring missing (but fixable by sharing an android define)
- [ ] qsystemdetection.h needs to know about us
- [ ] global/qnumeric_p.h:118:72: error: 'isnan' is not a member of 'std' -- missing math.h stuff?

**Comment by jsdevv** [comment]
Is this still in the works?

**Comment by MartinBriza** [comment]
Some notes from me playing around with building `qtbase` 6.1 with all modules disabled, except XML and Tools (to get `qmake`) - this means no GUI:
 - `std::wstring` can probably be disabled same as it's done with the CMake port
 - Serenity needs a `memalign` implementation, otherwise Qt fails to link
 - There's a lot of mess around shared memory (POSIX SHM api was removed) and semaphores (I don't even what's wrong in there). These can be disabled with our custom mkspec and build config
 - qmake really really wants `utimensat` and `UTIME_NOW`
 
However, I was able to get a working `qmake6` in Serenity which is pretty close to having something tangible soon-ish. If I'm bored, I'll look into how to clean this up and submit a PR with just `qtbase` with no GUI so others can build up from that.
