### ISSUE TITLE
Browser: Favicon not cleared after page change

### ISSUE THREAD

**Issue by moustafaraafat** [SerenityOS/serenity#15744]
To reproduce:
1. Open a new tab with some website like [duckduckgo](https://duckduckgo.com/)
2. Open [google](https://www.google.com/)
3. Notice the favicon is still for [duckduckgo](https://duckduckgo.com/)
Note: If the cookies acceptance message comes up, respond to it, then reproduce.

![image](https://user-images.githubusercontent.com/19346060/197275886-eb733bf5-f68d-4954-a348-a2654dc879de.png)

**Comment by HyflerSD** [comment]
Hey @moustafaraafat  i was able to reproduce the same on my end as well. I'm a newbie but i'll look at it on my end and do some debugging.

**Comment by kemzeb** [comment]
The problem still persists, here is an example following the steps mentioned by the author but starting with the GitHub domain instead:

![Screenshot 2023-02-20 210334](https://user-images.githubusercontent.com/60799661/220252258-d4abb18f-32b0-4809-b42f-9abd15354156.png)

I have tried to debug this issue but there seem to be a lot of moving parts I need to look into in order to better understand what's going on. If it helps anyone I have tried to trace what I think are the appropriate function calls, which start from `Tab.cpp`'s implementation of the `view().on_favicon_change(...)` lambda.

NOTE: "->" means the previous function is called by

`Tab::Tab(BrowserWindow&)`... Tab.cpp implements `view().on_favicon_change` lambda, which does the following:
- Sets its search bar favicon to the new favicon
- Calls its own `on_favicon_change` lambda so that `BrowserWindow` can implement it to set the tab favicon

->
`OutOfProcessWebView::notify_server_did_change_favicon(...)`
->
`WebContentClient::did_change_favicon(...)`

End of trace...

... however, I did also find this in my build directory
(in Build/x86_64/Userland/Services/WebContent/WebContentClientEndpoint.h) ->
`WebContentClientStub::handle(...)`... it calls a pure virtual function `WebContentClientStub:did_change_favicon(...)`

Not entirely sure about the last function `handle()` as it exists in the build directory and it doesn't call the previously mentioned function (`WebContentClient::did_change_favicon()`) but rather uses the class `WebContentClientStub` where it has a pure virtual function with the same signature `did_change_favicon(...)`.

Hopefully this helps out in some way! I plan to continue investigating this issue when I get the time.
