### ISSUE TITLE
Terminal(?): Pressing Ctrl+C in `top` exits the Terminal app

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#16306]
To reproduce, run `top` and press Ctrl+C. The terminal app should not exit, but it does :thinking:

**Comment by karolba** [comment]
I think some interesting info: I've been implementing my own shell for fun and came across the same kind of bug - erroneously exiting on `ctrl-c` in `top`, `htop`.

After some exploring it looks like the cause is a lack of job control/process groups in the Serenity shell (and in mine): that's what is supposed to enable `ctrl-c` to work correctly on Unices.

The GNU libc manual seems to have a useful explanation of what a shell should really do when interactively launching a process: https://www.gnu.org/software/libc/manual/html_node/Implementing-a-Shell.html
