### ISSUE TITLE
LibWeb: display: inline <input> element inside a table layout causes assertion failure

### ISSUE THREAD

**Issue by nortti0** [SerenityOS/serenity#17166]
A page that has an `<input>` element with a `display: inline` style inside a container with a table layout (either a table or a collection of divs with table layout set using CSS) causes the content process of Ladybird to crash with

> WebContent: /home/nortti/src/serenity/Userland/Libraries/LibWeb/Layout/InlineFormattingContext.cpp:126: void Web::Layout::InlineFormattingContext::dimension_box_on_line(const Web::Layout::Box&, Web::Layout::LayoutMode): Assertion `!box.display().is_flow_inside()' failed.

Minimal test case:

    <!DOCTYPE html>
    <html>
    	<head>
    		<meta charset="utf-8">
    	</head>
    	<body>
    		<table>
    			<tr>
    				<td>
    					<input style="display: inline" type="text">
    				</td>
    			</tr>
    		</table>
    	</body>
    </html>

**Comment by eggpi** [comment]
I've been looking at this, and although I haven't fully figured it out yet, here's some notes that can help.

First, I think we can simplify the test case further; all we need is a `display: inline` input element under a block element, so I can trigger the same assertion with:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    </head>
    <body>
        <input style="display: inline" type="text" />
    </body>
</html>
```

The issue seems to be that HTMLInputElement always [creates a BlockContainer for layout](https://github.com/SerenityOS/serenity/blob/9ed4fe7049561aafb5c8a1177aeac90aad214823/Userland/Libraries/LibWeb/HTML/HTMLInputElement.cpp#L74), regardless of its `display` property. If, instead, we do something like my patch d9deea959a8b5b620e100b5f6ac4420825a985d4 to actually take the display into account, the crash is gone.

That is probably not the whole story though, due to two issues.

**First issue:** The inline input element is not visible at all in Ladybird. I've confirmed the test case does render an input box in Firefox and Chrome.

Here's the layout tree for the above test case, with my patch:

```
InitialContainingBlock <#document> at (0,0) content-size 798x554 [0+0+0 798 0+0+0] [0+0+0 554 0+0+0] children: not-inline
  BlockContainer <html> at (0,0) content-size 798x18 [0+0+0 798 0+0+0] [0+0+0 18 0+0+0] children: not-inline
    BlockContainer <(anonymous)> at (0,0) content-size 798x0 [0+0+0 798 0+0+0] [0+0+0 0 0+0+0] children: inline
      TextNode <#text> @0x00007fa145ba9838
    BlockContainer <body> at (8,8) content-size 782x2 [8+0+0 782 0+0+8] [8+0+0 2 0+0+8] children: not-inline
      BlockContainer <(anonymous)> at (8,8) content-size 782x0 [0+0+0 782 0+0+0] [0+0+0 0 0+0+0] children: inline
        TextNode <#text> @0x00007fa145ba98b8
        InlineNode <input> @0x00007fa147310c38
      BlockContainer <#shadow-root> at (8,8) content-size 0x0 [0+0+0 0 0+0+0] [0+0+0 0 0+0+0] children: not-inline
      BlockContainer <div> at (10,9) content-size 778x0 [0+0+2 778 2+0+0] [0+0+1 0 1+0+0] children: inline
        TextNode <#text> @0x00007fa145ba9938
      BlockContainer <(anonymous)> at (8,10) content-size 782x0 [0+0+0 782 0+0+0] [0+0+0 0 0+0+0] children: inline
        TextNode <#text> @0x00007fa145ba99b8
```
and here's the layout tree with `display: block` on the input element instead, which renders fine:

```
InitialContainingBlock <#document> at (0,0) content-size 798x554 [0+0+0 798 0+0+0] [0+0+0 554 0+0+0] children: not-inline
  BlockContainer <html> at (0,0) content-size 798x34 [0+0+0 798 0+0+0] [0+0+0 34 0+0+0] children: not-inline
    BlockContainer <(anonymous)> at (0,0) content-size 798x0 [0+0+0 798 0+0+0] [0+0+0 0 0+0+0] children: inline
      TextNode <#text> @0x00007fa145baa038
    BlockContainer <body> at (8,8) content-size 782x18 [8+0+0 782 0+0+8] [8+0+0 18 0+0+8] children: not-inline
      BlockContainer <(anonymous)> at (8,8) content-size 782x0 [0+0+0 782 0+0+0] [0+0+0 0 0+0+0] children: inline
        TextNode <#text> @0x00007fa145baa0b8
      BlockContainer <input> at (9,9) content-size 120x16 [0+1+0 120 0+1+660] [0+1+0 16 0+1+0] children: not-inline
        BlockContainer <#shadow-root> at (9,9) content-size 0x0 [0+0+0 0 0+0+0] [0+0+0 0 0+0+0] children: not-inline
        BlockContainer <div> at (11,10) content-size 116x0 [0+0+2 116 2+0+0] [0+0+1 0 1+0+0] children: inline
          TextNode <#text> @0x00007fa145baa138
      BlockContainer <(anonymous)> at (8,26) content-size 782x0 [0+0+0 782 0+0+0] [0+0+0 0 0+0+0] children: inline
        TextNode <#text> @0x00007fa145baa1b8
```

I'm guessing this has something to do with how the `<div>` under `#shadow-root` is not a child of the `<input>` (and doesn't inherit its border?) in the inline case.

**Second issue:** We probably also want to take `display` into account for other types of input than just `text`. I haven't looked into this so far.

**Comment by kalenikaliaksandr** [comment]
The issue is no longer reproducible on build from master.
