### ISSUE TITLE
Ladybird: Adding support for Solaris/Illumos

### ISSUE THREAD

**Issue by nipos** [SerenityOS/serenity#17555]
After fixing/adding support for FreeBSD,OpenBSD and NetBSD,I'd like to add support for Solaris/Illumos,which is the OS that I use on my primary computer.
Unlike the BSDs,support for Solaris is currently non-existent in the Serenity codebase so I have some questions before I start:
First of all,is there any chance to get that merged?
Both proprietary Solaris and the open-source Illumos project are actively maintained,but they have a rather small user base so I don't know if it's relevant here,but it works good for me and I want to have Ladybird there.
If I can add it,is it enough to have AK_OS_SOLARIS universally or should proprietary Solaris and Illumos be handled separately?
They are 99% identical and both define __sun for identification,but since OpenSolaris was discontinued,they have been developed independently and may get more differences in future.
If they need to be handled separately,I can only support Illumos as I don't own a paid Solaris license,but it's very likely that the same code will work on both.
Should Solaris/Illumos also identify as AK_OS_BSD_GENERIC?
Solaris is based on original Unix source code,but the BSDs were forked from that code base more than 10 years earlier,so I'm not sure  how much they still have in common.
Solaris is likely more similar to BSD than to Linux,but still it may need special handling in a few cases.
On the other hand,all other BSDs are independent projects as well,and all have their differences.
It would be nice if you could answer my questions and maybe explain the relevant decisions before I start working on porting it,so that I prevent wasting my time on stuff that needs to be done in other ways or not at all.

**Comment by kleinesfilmroellchen** [comment]
> Unlike the BSDs,support for Solaris is currently non-existent in the Serenity codebase so I have some questions before I start: First of all,is there any chance to get that merged?

We have so far not rejected support for any platform. There's basically two important considerations:
- If the platform support adds too much complexity to the SerenityOS libraries (especially LibCore and AK), it'll not happen. Even though nobody has worked on it to completion, this would for example place a significant burden on Windows compatibility.
- After platform support is initially implemented, the only people maintaining the platform support are the people that care about the platform. (Some exceptions apply to MacOS and Linux since these are widely used by a lot of developers.) So if you want to use this platform going forward, you'll have to put in the work of keeping it working.
- There's only CI testing for Linux and macOS, so at any point, any other platform may break, and such breakage, even if known beforehand, does not prevent PRs from getting merged.

As far as I know, Solaris is a UNIX system, so the first point will not be particularly relevant, but you have to be aware of the other two.

> Both proprietary Solaris and the open-source Illumos project are actively maintained,but they have a rather small user base so I don't know if it's relevant here,but it works good for me and I want to have Ladybird there.

User base considerations don't apply to SerenityOS :^) (see FAQ)

> If I can add it,is it enough to have AK_OS_SOLARIS universally or should proprietary Solaris and Illumos be handled separately? They are 99% identical and both define __sun for identification,but since OpenSolaris was discontinued,they have been developed independently and may get more differences in future. If they need to be handled separately,I can only support Illumos as I don't own a paid Solaris license,but it's very likely that the same code will work on both.

If you can't even test Solaris (and mostly care about Illumos), we should only need Illumos support. The definition can still be called `AK_OS_SOLARIS` since that will be familiar to at least some people.

> Should Solaris/Illumos also identify as AK_OS_BSD_GENERIC? Solaris is based on original Unix source code,but the BSDs were forked from that code base more than 10 years earlier,so I'm not sure how much they still have in common.

If Illumos can use some or most of our BSD support, that would be ideal, since it means less adaptation to the new platform. You will have to figure this out yourself of course.

Overall I see no problem with you going ahead with adding platform support if you keep what I've mentioned in mind. Especially try to change as little as possible of our platform support, and reuse platform support wherever possible.

**Comment by nipos** [comment]
Thank you very much for clarification.
I'll start working on it soon,but don't expect immediate results (I'm not that experienced with C++ yet).
Of course I'll keep maintaining it afterwards.

**Comment by ADKaster** [comment]
If the changes are limited to the existing places that have checks for BSD variants, that's fine. But if we start needing fully custom implementations for Solaris/Illumos then it becomes a question of how much maintenance will be required to fully support the platform for e.g. the Ladybird Browser.

Thanks for the time and effort you've put into making our *BSD support better. I would recommend that for adding support for a new Unix like Solaris/Illumos, a single PR with many commits would make it a lot easier for maintainers to judge how much maintenance it will be to keep that support working in the future.

There's definitely more ways we can unify our platform ifdef usage in AK and LibCore to make maintenance easier, so if you see any more ways to make it easier to support common Unix platforms in the future that would be much appreciated as well!

**Comment by ADKaster** [comment]
> We have so far not rejected support for any platform. 

This is not true. I started work on Windows support and it was rejected because the maintenance burden is unknown but expected to be high. Essentially the feedback was "show everyone a fully working Ladybird binary and then we can talk". I suspect Solaris will be less work than Windows.

**Comment by kleinesfilmroellchen** [comment]
> > We have so far not rejected support for any platform.
> 
> This is not true. I started work on Windows support and it was rejected because the maintenance burden is unknown but expected to be high. Essentially the feedback was "show everyone a fully working Ladybird binary and then we can talk". I suspect Solaris will be less work than Windows.

My mistake, I didn't know Windows support got this far along.

**Comment by ADKaster** [comment]
Fixed by 17623
