### ISSUE TITLE
LibJS: Syntax error (unexpected token DoublePipe)

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#18087]
LibJS doesn't like this:

```js
0 ?? 0 ? 0 : 0 || 0
```

```
[SyntaxError] Unexpected token DoublePipe. Expected Semicolon (line: 1, column: 16)
```

The source string above is a reduction from the `vscode.dev` source code.

**Comment by AbdelAzizMohamedMousa** [comment]
The ?? operator is the nullish coalescing operator in JavaScript and was introduced in ECMAScript 2020. It returns the value of its left-hand side operand if it's not null or undefined, otherwise it returns the value of its right-hand side operand. The || operator is the logical OR operator which is commonly used for short-circuit evaluation or as a default value fallback.

In the expression 0 ?? 0 ? 0 : 0 || 0, the ?? operator has higher precedence than the ? : operator and the || operator. So the expression is evaluated as (0 ?? 0) ? 0 : (0 || 0), which first evaluates the left-hand side of ?? as 0 since it's not null or undefined, then evaluates the conditional operator ? : as 0, and finally evaluates the right-hand side of || as 0 since it's falsy.

The error occurs because the ?? operator is not supported in the version of JavaScript that LibJS implements. To fix the error, you can replace the ?? operator with an equivalent expression using the != null operator, like this:
`0 != null ? 0 : (0 || 0)
`
This expression first checks if 0 is not null or undefined, then evaluates the conditional operator ? : as 0, and finally evaluates the right-hand side of || as 0 since it's falsy.
