### ISSUE TITLE
LibWeb: Fetch's Body#text() does not handle invalid UTF-8

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#18913]
String::from_utf8 expects the bytes to already be valid UTF-8, but they can invalid.
https://github.com/SerenityOS/serenity/blob/0f0d16bbecc4374e7b00be101c60623da300c40a/Userland/Libraries/LibWeb/Fetch/Body.cpp#L140

For example, `seenthis.se` calls `.text()` on GIF web beacons before immediately discarding them:
![image](https://github.com/SerenityOS/serenity/assets/25595356/ab91b85d-d7a1-45ab-a471-eee812adc0d0)
```
bytes: GIF89a����!�,L;
WebContent: /home/lukew/Desktop/serenity-project/serenity/Userland/Libraries/LibWeb/Fetch/Body.cpp:144: WebIDL::ExceptionOr<JS::Value> Web::Fetch::package_data(JS::Realm &, AK::ByteBuffer, Web::Fetch::PackageDataType, const Optional<MimeSniff::MimeType> &): Assertion `_temporary_result.error().code() == ENOMEM' failed.
```

**Comment by trflynn89** [comment]
Fix should be very similar to the fix for #18432. The `UTF-8 decode` spec step mentioned on that line is meant to `Process a queue with an instance of UTF-8's decoder], ioQueue, output, and "replacement"`. That is, use `TextCodec::convert_input_to_utf8_using_given_decoder_unless_there_is_a_byte_order_mark` (rolls off the tounge)
