### ISSUE TITLE
Browser: Layout on xkcd.com

### ISSUE THREAD

**Issue by dlemos** [SerenityOS/serenity#19067]
Main content is shifted to the right as shown by the screenshot.
![image](https://github.com/SerenityOS/serenity/assets/596733/2cadc605-d67c-44ab-a70c-670df0bd0e95)

**Comment by shannonbooth** [comment]
I've narrowed this down to the following HTML:

```
<html><head>
</head>
<body>
<div style="margin-left:-400px">Some content inside div</div>
</body></html>
```

It seems that the problem is related to margin-left when it is negative in the div. Everything works fine if the margin is positive. I'm not very familiar with the code around here, but my guess is somewhere in BlockFormattingContext.

Trying to investigate more...
