### ISSUE TITLE
Kernel: Moving/Renaming file that begins with dash turns it into a directory

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#19366]
Steps to reproduce:

1. Create the file: `touch -- --foo`
2. List the directory: `ls -l` and notice that the file `--foo`is showing up as expected
4. Rename the file to not begin with a dash: `mv -- --foo foo
5. List the directory again: `ls -l` and notice that the file `foo`is now showing up as a directory

![Screenshot from 2023-06-12 11-23-35](https://github.com/SerenityOS/serenity/assets/10320822/71bed787-08fb-4d1f-aa15-80b276f61ebd)

**Comment by circl-lastname** [comment]
Weird!

**Comment by fdellwing** [comment]
I can't reproduce that on the latest commit. From your screenshot it also seems, that you run into a `mv` quirk and not a bug:

In your first screenshot `ls -l` you can see a file `--foo` and a directory `foo`. If you now run `mv -- --foo foo`, like your did, it will move the file `--foo` into the folder `foo`. That is the expected behaviour.

**Comment by tomuta** [comment]
> I can't reproduce that on the latest commit. From your screenshot it also seems, that you run into a `mv` quirk and not a bug:
> 
> In your first screenshot `ls -l` you can see a file `--foo` and a directory `foo`. If you now run `mv -- --foo foo`, like your did, it will move the file `--foo` into the folder `foo`. That is the expected behaviour.

Huh I think you are right. Don't know why but I evidently messed up somehow.

**Comment by tomuta** [comment]
Closing as invalid
