### ISSUE TITLE
Bootloop in Qemu

### ISSUE THREAD

**Issue by ForLoveOfCats** [SerenityOS/serenity#2108]
For a while now (I am not sure what commit this started in as I check out the latest changes very infrequently) Serenity has refused to correctly boot leading to Qemu continually rebooting.

I am on Manjaro Linux with a clean build of current master (adb4accab3668e60a6998c4b492d1cf7be11f9d1) and Qemu reports to be of version 4.2.0. I disabled auto rebooting in the run script in order to get [this](https://gist.github.com/ForLoveOfCats/9e254c45f9bd5c5b36e1b298af460ec5) console log. Please let me know how else I may provide additional information. Cheers!

**Comment by awesomekling** [comment]
Hmm, interesting. What kind of host machine is this running on? It looks to be a little bit older based on this:

```
[Kernel]: x86: SSE support enabled
[Kernel]: x86: WP support enabled
[Kernel]: x86: PGE support enabled
[Kernel]: x86: NX support enabled
[Kernel]: x86: SMEP support not detected
[Kernel]: x86: SMAP support not detected
[Kernel]: x86: RDTSC support restricted
[Kernel]: x86: No RDRAND support detected. Randomness will be shitty
```

**Comment by Dexesttp** [comment]
Something similar briefly happened to me a week ago - after pulling master, qemu started to enter a reboot loop on start.

While trying to look into it, I added an extra `klog() << "test";` in init.cpp line 111 and that "solved" the issue allowing for a full boot.

Even after removing the line it didn't reappear, and it hasn't come back yet. I thought it was a config issue on my side, but maybe you can try adding that extra klog() as well and see if it's related ?

**Comment by sunverwerth** [comment]
@Dexesttp sounds more like the recompilation fixed it. Not necessarily the extra log.

**Comment by ForLoveOfCats** [comment]
Yes the host CPU is on the older side of things. It is a [Core 2 Quad Q8400](https://ark.intel.com/content/www/us/en/ark/products/38512/intel-core-2-quad-processor-q8400-4m-cache-2-66-ghz-1333-mhz-fsb.html)

**Comment by Dexesttp** [comment]
> 
> 
> @Dexesttp sounds more like the recompilation fixed it. Not necessarily the extra log.

I'm pretty sure it wasn't just a recompilation issue, since when trying to debug it I had to move the log all over the file (at the very top didn't work but it showed up in the console, at the bottom it didn't show up, and it only started booting at that specific place).

It was a weird overall, but seeing how this issue seems to be linked to the CPU it was probably unrelated.

**Comment by StavroMuellerBeta** [comment]
I am having the same issue on a dual Xeon 5150 system - the same processor architecture (if a bit older). The boot log is also very similar to ForLoveOfCats's and shows the same snippet that awesomekling posted. I am on build 6b674db on Solus 4.1 and am also using Qemu 4.2. I tried recompiling with ./makeall.sh and that did not fix the issue. This seems to be an issue linked to Intel's Core architecture.

**Comment by awesomekling** [comment]
This appears to be happening in `setup_low_pseudo_identity_mapping()`

That code is basically reorganizing the page tables under itself while running. A mildly dangerous endeavor!

I think the best fix here would be to organize the page tables correctly in `boot.S` instead of doing it one way there and then another way later in `MemoryManager`.

**Comment by ForLoveOfCats** [comment]
I can confirm that the issue has been resolved and Serenity now correctly boots and runs in Qemu on my system
