### ISSUE TITLE
Ladybird/AppKit: Address bar text unreadable with some `<meta name="theme-color">` values

### ISSUE THREAD

**Issue by warpdesign** [SerenityOS/serenity#21394]
In dark mode, the address bar text is black over... a dark background: this make it unreadable:

![Capture d’écran 2023-10-10 à 09 12 45](https://github.com/SerenityOS/serenity/assets/199648/44412649-e349-42b9-af0b-d57e381f826c)

**Comment by warpdesign** [comment]
OS is in auto (light) mode but I set GitHub's Dark theme in the site's preferences:

![image](https://github.com/SerenityOS/serenity/assets/199648/b14d7fc6-f514-4b23-9480-6473dc029b8e)

Chrome correctly uses light mode for the window decorations:

![Capture d’écran 2023-10-10 à 16 42 59](https://github.com/SerenityOS/serenity/assets/199648/eb59bcae-f88c-4b4e-a7e6-62559984e7cc)

**Comment by trflynn89** [comment]
Because Chrome (on desktop) doesn't really support the `<meta name="theme-color">` attribute (it does on Android). We very recently started supporting it in https://github.com/SerenityOS/serenity/pull/21150.

CC @juniorrantila

**Comment by bplaat** [comment]
I think it is better to use a color algorithm to flip the browser bar foreground color, or to dim down the lightness when using system dark mode. Because the reverse of this issue (using a site with `<meta name="theme-color" content="#ffffff">` with dark theme) also results in unreadable UI:

![Screenshot 2023-10-18 at 20 30 58](https://github.com/SerenityOS/serenity/assets/19894029/56d181f5-0392-44a3-b7c2-91ad1d3be689)
