### ISSUE TITLE
LibWeb: WebContent process can freeze when calling history.back()

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#21495]
Pressing the `history.back()` button on this page causes it to spin forever on the following code: <https://gigantic-honored-octagon.glitch.me/subpage.html>
https://github.com/SerenityOS/serenity/blob/f8763c16b29f98fd664b667b713cabeffbe5c19b/Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp#L380-L385

## Funding

- We're currently trying [Polar.sh](https://polar.sh/SerenityOS) where you can help fund the work on this issue.
- Contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/SerenityOS/serenity/issues/21495">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/SerenityOS/serenity/issues/21495/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/SerenityOS/serenity/issues/21495/pledge.svg">
</picture>
</a>

**Comment by aduerig** [comment]
I investigated this a bit and found if you make the following code changes, the history.back() on the example page linked above works and navigates back. Code changes:
https://github.com/SerenityOS/serenity/blob/c990db091340487191dbf9cdb0fc0390a13bd953/Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp#L361
to:
```
queue_global_task(Task::Source::NavigationAndTraversal, navigable->active_document()->window(), [after_document_populated]() mutable {
                                 after_document_populated();
```

And similarly:
https://github.com/SerenityOS/serenity/blob/c990db091340487191dbf9cdb0fc0390a13bd953/Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp#L420
to:
```
queue_global_task(Task::Source::NavigationAndTraversal, navigable->active_document()->window(), [&, target_entry, navigable, displayed_document, update_only = changing_navigable_continuation.update_only, script_history_length, script_history_index] {
```

I don't think this is quite the correct solution however, because it is simply not what the spec says: "given navigable's active window". I expect using `navigable->active_document()->window()` instead of `active_window()` might cause issues with other nuances of navigables. 

My reasoning on why the above changes produce the correct behavior is just because it convinces the EventLoop to actually run the Task. A document's Task must be "fully" active to run:
https://github.com/SerenityOS/serenity/blob/bbfde63f79b62080ade37051fc11a61ca132184f/Userland/Libraries/LibWeb/HTML/EventLoop/Task.cpp#L32 

My thinking is somehow the active_document() and active_browsing_context() somehow get out of wack. One theory I had is that I thought maybe `active_document() == active_window()->associated_document()` should always be true, but that becomes false right after this line:
https://github.com/SerenityOS/serenity/blob/c990db091340487191dbf9cdb0fc0390a13bd953/Userland/Libraries/LibWeb/HTML/Navigable.cpp#L1046C7-L1046C7

Treat my explanations with a grain of salt though, because I've never read of the HTML spec or any of LibWeb before. Writing this down because I feel like this might be a good hint, but I can't quite put it together.

**Comment by aduerig** [comment]
I did some more reading / digging. Ultimately [this is the task never ends up running, this is what causes the deadlock.](https://github.com/SerenityOS/serenity/blob/c990db091340487191dbf9cdb0fc0390a13bd953/Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp#L361).

This task DOES get queued, it just never runs. It is queued after `populate_session_history_entry_document()` executes with [`target_entry`](https://github.com/SerenityOS/serenity/blob/c990db091340487191dbf9cdb0fc0390a13bd953/Userland/Libraries/LibWeb/HTML/TraversableNavigable.cpp#L297), which is `active_session_history_entry()` in this callpath. Since `populate_session_history_entry_document()` is intended to change the passed `SessionHistoryEntry`, this ends up changing the `active_session_history_entry()`, which therefore [changes the result of `navigable->active_document()`](https://github.com/SerenityOS/serenity/blob/c990db091340487191dbf9cdb0fc0390a13bd953/Userland/Libraries/LibWeb/HTML/Navigable.cpp#L199). The event loop will only run a task if the associated document is fully_active(), and since `make_active` has not yet run on the result of `navigable->active_document()`. It will be run after the callback, but since it isn't run yet, deadlock occurs.

The real oddity to me is that since `populate_session_history_entry_document` changes the passed `SessionHistoryEntry` without ever running `make_active`, it feels that this function should never be passed the `active_session_history_entry()`, but it is in this case because the `current == active`.

[Which is the normal case since the spec reads](https://html.spec.whatwg.org/multipage/document-sequences.html#navigables) "The current session history entry and the active session history entry are usually the same".

I'm having real trouble figuring out the intended way that the spec wants this to work. I'm not sure if we should temporarily allow the event loop to run with `null` instead of the partially active Document with a FIXME: [not what the spec says](https://html.spec.whatwg.org/multipage/browsing-the-web.html#updating-the-traversable). This would prevent the deadlock and produces the correct behavior.

**Comment by kalenikaliaksandr** [comment]
Related spec bug https://github.com/whatwg/html/pull/9901#issuecomment-1790112168

**Comment by aduerig** [comment]
> Related spec bug [whatwg/html#9901 (comment)](https://github.com/whatwg/html/pull/9901#issuecomment-1790112168)

Ah okay, those are exactly the 2 spots I had to change the event loop queueing to fix the behavior. Thanks for linking. Sounds like the best move is to wait on the spec then.

**Comment by kalenikaliaksandr** [comment]
no longer reproducible
