### ISSUE TITLE
Browser: Add a way to create a new tab from gui

### ISSUE THREAD

**Issue by 8infy** [SerenityOS/serenity#2163]
It's been bothering me too much that serenity's browser doesnt have something like this:
![image](https://user-images.githubusercontent.com/34326714/81442021-7d744c00-917b-11ea-9242-1f4483016aef.png)
I know there's a keyboard shortcut for this, but I have no clue what it is and i'm used to creating tabs this way, and I think a lot of people are, too! Would be great to have this.

**Comment by bugaevc** [comment]
Let's not encourage people to create many tabs.

There's the main menu item, the shortcut, and the context menu item. Adding another way to create moar tabs right on the tabstrip is going to make it easier to open more tabs for sure, but again, is that something we would want to encourage?

**Comment by bcoles** [comment]
> Let's not encourage people to create many tabs.

... why?

**Comment by bugaevc** [comment]
Because that creates a situation where tabs are used to keep anything remotely interesting open, instead of bookmarks. Tabs are meant to be used for doing several things at once. You know all those memes about having do much tabs open (and how it feels closing them)? Well, that's what happens when you make opening new tabs so convenient people start using that for "read it later"/"bookmark it" needs, instead of the proper mechanisms.

If I had it my way, I'd say we shouldn't have tabs on the first place, and if somebody wants to do several things at once, they should just open multiple windows of the browser.

...but as @awesomekling said in his video where he added tabs, "some people like single-tab, or at least like the idea of single-tab until they actually try it" — and he has a point 😆. Maybe we could hide the tab strip by default until you open a second tab, like Safari does it?

**Comment by 8infy** [comment]
> Let's not encourage people to create many tabs.
> 
> There's the main menu item, the shortcut, and the context menu item. Adding another way to create moar tabs right on the tabstrip is going to make it easier to open more tabs for sure, but again, is that something we would want to encourage?

Why don't we just let people create as many tabs as they want? Not having this button makes the user experience worse, so it feels like a nobrainer, almost every browser I've ever used had it.

**Comment by 8infy** [comment]
![image](https://user-images.githubusercontent.com/34326714/81467485-91529900-91e1-11ea-8312-1f3e055b973b.png)
Here's 5 different browsers I have on my computer. Every single one has this button.

**Comment by awesomekling** [comment]
https://github.com/SerenityOS/serenity/blob/master/CONTRIBUTING.md#issue-policy
>Unlike many other software projects, SerenityOS is not concerned with gaining the largest possible userbase. Its target audience is its own developers. As such, we have limited interest in feature requests from non-contributors.

**Comment by bugaevc** [comment]
> Why don't we just let people create as many tabs as they want? Not having this button makes the user experience worse

We do let people create many tabs, but we shouldn't *encourage* that by putting the new tab button front-and-center. And I'm arguing not [shepherding](https://nibblestew.blogspot.com/2020/03/its-not-what-programming-languages-do.html) people into opening a new tab for *everything* makes for a much better user experience. If anything, we should be promoting bookmarks more.

> Here's 5 different browsers I have on my computer. Every single one has this button.

Those are 2020 browsers, but we live in 1995.

**Comment by 8infy** [comment]
> Those are 2020 browsers, but we live in 1995.
Fair enough I guess 😄
