### ISSUE TITLE
LibWeb: Mouse events (hit testing?) does not account for overflowed scroll offsets

### ISSUE THREAD

**Issue by trflynn89** [SerenityOS/serenity#22068]
As seen here:

https://github.com/SerenityOS/serenity/assets/5600524/d8090c32-c1be-43f8-b214-9271fe901783

The HTML from that example:
```html
<html>
<head>
    <style type="text/css">
        .container {
            border: 1px solid black;
            height: 200px;
            overflow: scroll;
        }
        p {
            margin: 0;
        }
        p:hover {
            background-color: yellow;
        }
    </style>
</head>
<body>
    <div class=container>
        <p>Line 1</p><p>Line 2</p><p>Line 3</p><p>Line 4</p><p>Line 5</p>
        <p>Line 6</p><p>Line 7</p><p>Line 8</p><p>Line 9</p><p>Line 10</p>
        <p>Line 11</p><p>Line 12</p><p>Line 13</p><p>Line 14</p><p>Line 15</p>
        <p>Line 16</p><p>Line 17</p><p>Line 18</p><p>Line 19</p><p>Line 20</p>
    </div>
</body>
</html>

```

**Comment by ebanner** [comment]
I'm looking at this 👀

It's suspected the crux of the issue is this FIXME (credit to @trflynn89)

https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibWeb/Painting/StackingContext.cpp#L391

I'm currently looking at the overflow_x() and overflow_y() properties and they don't seem to change from `Visible` to `Scroll`... 🤔
