### ISSUE TITLE
Dithering to a limited color palette

### ISSUE THREAD

**Issue by peteroupc** [SerenityOS/serenity#22841]
Support displaying a limited number of unique colors on the screen, such as 2, 16, or 256, by dithering to the colors in the palette.

**Comment by circl-lastname** [comment]
Does this relate to an ability of the graphics processing stack ie Pixel Paint or displaying on screen itself?

**Comment by peteroupc** [comment]
This issue relates to the entire on-screen display.  Alternatively, if feasible, the dithering can be implemented window-by-window as long as the entire screen ends up using only the colors in the palette.

**Comment by AtkinsSJ** [comment]
What's the use case for this?

**Comment by peteroupc** [comment]
- To prepare the screen frame buffer for transfer to a VGA or SVGA display which is set to 16-color or 256-color mode.
- Displaying the operating system in a limited-color palette, such as the Windows 16-color palette or the Web safe palette, is nostalgic for some people.  Indeed, for many modern displays, it's no longer possible to set the display to 16-color or 256-color mode or, if it still is, that option is no longer exposed by the operating system or desktop environment's GUI.

**Comment by AtkinsSJ** [comment]
I'm not familiar enough with hardware to really give an opinion on this, but we don't accept feature requests from non-contributors. Generally, if you want something done, you need to be willing to give it a go yourself. However I'd recommend discussing this on Discord before you start working on it, because it sounds like it would be quite involved, and supporting outdated hardware is a non-goal of the project. But also someone there might be able to give you some pointers.

**Comment by peteroupc** [comment]
This issue does not ask to support more display hardware than it already does.

However, I see there is a JavaScript extension for the [Cinnamon](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/desaturate-all%40hkoosha), [GNOME](https://github.com/laerne/desaturate_all), and [KDE](https://store.kde.org/p/1263836) desktop environments that changes the entire screen's colors to grayscale, suggesting that this issue could be implemented as a screen-wide effect (at the desktop environment level) that dithers the screen to 16 or 256 colors.  The Cinnamon and GNOME screen-wide effect frameworks appear to be flexible enough to support screen-wide color changes and screen buffer transformations.  If SerenityOS already supports a similar framework for such screen-wide effects as Cinnamon and GNOME, then this issue is already resolved.

**Comment by LucasChollet** [comment]
I don't think you got Sam's point, the issue is not particularly _what_ you're asking, but more that you _are_ asking.
Let's emphasize it: we just don't accept feature requests from non-contributors. You're welcome to implement it yourself. And make sure it fits the project goal on discord first.

Are you willing to contribute to the project and implement the features that you requested in both issues you created?

**Comment by peteroupc** [comment]
Maybe, if the apps and libraries for this project were made into separate repositories (to make them more reusable), but even that suggestion might not be accepted here, so I will close this issue.
