### ISSUE TITLE
LibPDF: Support opening large documents

### ISSUE THREAD

**Issue by mattco98** [SerenityOS/serenity#23028]
I recently discovered https://github.com/Lucas-C/undying-dusk, a "video game" in PDF form with over 200k pages and thought it might be fun to see how LibPDF handles it. Unsurprisingly, it hangs for about 10 seconds and OOMs while trying to parse the entire page tree at once. As [this FIXME states](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibPDF/Document.h#L164-L169), we shouldn't need to parse the page tree at document startup, only when attempting to load a page for the first time. This will also require some outline tree changes, as the outline destinations depend on converting an indirect object reference to a page into a page number.

**Comment by nico** [comment]
It seems to be huge pdfs week :D

Are you use the page tree is a problem? The file quickly and without problems for me:

```
 % time Build/lagom/bin/pdf --render out.png ~/Downloads/undying-dusk-pdf-only/undying-dusk.pdf --page 10000
Build/lagom/bin/pdf --render out.png  --page 10000  0.25s user 0.02s system 95% cpu 0.281 total
```

It also opens quickly in MacPDF and going through it is no problem:

<img width="612" alt="Screenshot 2024-01-31 at 9 16 50 AM" src="https://github.com/SerenityOS/serenity/assets/3487/613b9d35-b328-448d-a8a7-32d804287367">

In related news, someone mentioned https://larsch.github.io/2021/04/12/this-pdf-file-has-2-million-pages.html on Discord. The file there is invalid, but after running it through `mutool clean`, it opens and works fine.

And someone else mentioned https://mpfirearmspublicstore.blob.core.windows.net/firearms-reference-table/frt-traf-eng.pdf which also has over 100k pages, and it too works fine in MacPDF.

My guess (which I haven't verified) is that the problem might instead be that GUI::Model doesn't do on-demand line loading and PDFViewer doesn't work great due to that. (…but undying-dusk seems to not have an outline, so maybe not.)

Anyways, LibPDF itself seems to handle hundreds of thousands of pages pretty well already as far as I can tell.

**Comment by nico** [comment]
As for memory use:

```
% /usr/bin/time -lh Build/lagom/bin/pdf --render out.png ~/Downloads/undying-dusk-pdf-only/undying-dusk.pdf --page 10000 2>&1 | grep mem
                   0  average shared memory size
            16958656  peak memory footprint
```

So about 16 MB, or 80 bytes per page.

**Comment by mattco98** [comment]
I ran it inside of Serenity, I didn't realize there was a way to run LibPDF through Lagom without using MacPDF. Might have to give it another try. Regardless though, it's probably still a good idea to load the page tree lazily (or at least remove that FIXME if it's determined to really not be an issue at all).

**Comment by mattco98** [comment]
Yeah you're right, looks like it's not the page tree. I just assumed it was

**Comment by nico** [comment]
Did you find out what else causes it?
