### ISSUE TITLE
LibCore: Expose ArgsParser options to Shell somehow

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#2357]
Moving the discussion from #2345 to here.

@bugaevc @alimpfard

**Comment by alimpfard** [comment]
Thank you for making us un-hijack that poor PR

**Comment by Dexesttp** [comment]
I was thinking of doing this, but got stuck trying to summarize the discussion :^)

## Idea

It would be nice if pressing `program <tab>` in the shell would propose the proper autocompletion arguments. Since we already define the allowed arguments using `ArgsParser`, linking the two mechanisms together sounds like a good idea.

Following a discussion on #2345 and on IRC, there is a few things to consider to link Shell and ArgsParser.

Here are the list of features to handle :
- Values accepted and handled by ArgsParser should be sent to the shell.
- The custom choices should be autocompleted properly (e.g. files should trigger file autocompletion / path search)
- Autocompletion should also support complex arguments / custom handlers (think `git push <tab>` which should return a list of remote repositories only known by git, or `git status --<tab>` vs `git push --<tab>` which should return a different list of options)

## Implementation Proposals 

The proposed ideas were :
- Storing the data in a custom `.arguments` ELF section.
    - Advantages : There is no need to execute the program, bypassing a lot of complexity to handle non-argsparser programs
    - Inconvenient : This would require an extra interaction between ArgsParser and the compiler to generate the custom ELF section, and 
    - Inconvenient : This would make dynamic arguments either impossible or complex to handle, depending of the implementation of the custom section.
- Having a special argument which allows dumping available / possible arguments 
    - Advantages : This can re-use the exisiting ArgsParser code
    - Inconvenient : Programs aren't able to use the special argument for their own behaviour. Proposed options to handle this were to just accept the limitation for a specific argument (like `--help` today), use a long argument that nobody would want to use, and to use a non-ASCII character in the argument that can't be sent by the user during normal use of the shell.
    - Inconvenient : Programs which do not implement ArgsParser should be properly handled by the Shell interaction. The proposed options to handle applications were :
        - A custom ELF section, similar to the first proposed idea, but with only the flags to bypass the contents inconvenient
        - A custom symbol in the ELF, this would allow to generate it in an easier way and possibly to do compile-time typechecking using "static_assert magic".
       - Running the program with no pledge and with a timeout, limiting the side-effects that the program might have. This bypasses the need for a custom mechanism to identify the program, but might add limitations for what the complex args / custom targets might be
        - Whatever we do, the way to support this will be some kind of hack and probably won't be elegant.


## Existing implementations

Because it's a good idea to see what's out there, here are how other shells do it :
- `bash` : [the `complete` builtin](https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html) and the [`/etc/bash_completion.d/` folder](https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion.html)
- (I'm currently researching how fish / zsh does it, but it seems very similar to the bash way)

**Comment by bugaevc** [comment]
> Programs which do not implement ArgsParser should be properly handled by the Shell interaction.

Personally I don't care about programs that don't use `Core::ArgsParser`. If we're able to execute their bash completion scripts, good, but I wouldn't worry a second if we can't. But it's extremely important that we don't crash, etc. when processing those programs, we should be just unable to autocomplete their arguments.

> limiting the side-effects that the program might have.

"Limiting" is not strong enough of a word; it really means that the only thing the program could do is produce some output.

> but might add limitations for what the complex args / custom targets might be

Mmm, has that been brought up? Could you provide an example?

**Comment by bugaevc** [comment]
And to make it clear, we still have to do that sandboxing even if the program indicates it supports `Core::ArgsParser` — it could be lying to us, or implemented improperly, so it does something (like WindowServer connection) first and parses arguments later, and so on.

**Comment by alimpfard** [comment]
> If we're able to execute their bash completion scripts, good

That's probably not the intent of that; rather, "we should not blow up or execute random programs"

> Could you provide an example

The one thing I can immediately think of would be git trying to resolve fs paths

> we still have to do that sandboxing

That's a given; we'd rather be safe.

**Comment by Dexesttp** [comment]
> Mmm, has that been brought up? Could you provide an example?

This hasn't been brought up, but that seems like a logical extension to the static custom section argument.

By limiting the call to no pledges, then you can't do anything else than outputting data.
The main issue would be for listing files in a specific directory (e.g. when calling `keymap <tab>`, it will want to list the files in `/res/keymaps/`) or reading a configuration file (e.g. when calling the future `serenity-git remote <tab>` command, it will need to read the `.git/config` folder).

There's an obvious workaround with that, which is to have two "modes" : one which just says "I'm an argsparser program / I'm not an argsparser program", and one which actually provides the autocompletion. This could be done via either two different custom arguments or a combined custom argument.

**Comment by Dexesttp** [comment]
(I'm also updating the summary comment as we discuss things, so we can try to have everything we agree on in a single post. So, don't worry if the quotes aren't relevant anyore :) )

**Comment by bugaevc** [comment]
> The main issue would be for listing files in a specific directory (e.g. when calling keymap <tab>, it will want to list the files in /res/keymaps/) or reading a configuration file (e.g. when calling the future serenity-git remote <tab> command, it will need to parse the .git/config file).

That sounds a bit far-fetched, as `Core::ArgsParser` currently has no way to know that your arguments/options are meant to be file paths, let alone file paths relative to some fixed directory. But if we want that, then it would be easy to allow `rpath` in addition to `stdio` :slightly_smiling_face:

**Comment by alimpfard** [comment]
> currently has no way to know that your arguments/options are meant to be file paths

oh gosh, then let's have that :^)

**Comment by ADKaster** [comment]
Assuming shared libraries exist...

What if you link a shared library that wants to do some library-specific command line parsing? The contents of the `.command_args` elf section of the shared library wouldn't be available until load-time. well after the shell has executed the binary. Or are we envisioning that only the main executable would ever register command line arguments? 

If only the main executable should be interacting w/Core::ARgsParser, you could probably "easily" add a special program header using the OS reserved p_type range:

```
#define PT_LOOS 0x60000000   /* reserved range for OS */
#define PT_HIOS 0x6fffffff   /*  specific segment types */
```

For example, Linux uses two values in that range for special GNU exception frame headers and for marking whether the stack should be executable or not.

https://refspecs.linuxbase.org/LSB_3.0.0/LSB-PDA/LSB-PDA/progheader.html

The program headers should always be within the first page of the executable (an assumption the kernel currently makes) and the existence of this PHDR could indicate to the shell that it should dig into the ELF file further to find the 'args data'.

Regarding the problem of dynamic args... bash_completion makes that difficult too right?

**Comment by alimpfard** [comment]
Possibly silly idea regarding suggestions,

what if we have the programs provide their own suggestions?
e.g. via some `--provide-suggestions-for <option> --<option> <hint>` and an interface like `ArgsParser::Option::suggest(StringView hint)`

this would let us handle dynamic stuff too.

assuming we have a way to detect that a program uses ArgsParser anyway.

**Comment by bugaevc** [comment]
Sure, that makes sense. Haven't this been suggested yet?

**Comment by alimpfard** [comment]
I didn't notice it if it was.
At least, I don't see it in the summary above, so might as well have it here for documentation purposes.

**Comment by Dexesttp** [comment]
That was actually the main argument for me, in favor of using the application itself to give argument completion data. That suggestion seemed to make argsparser the most flexible, and justified the difficulty of implementing it this way. But, after re-reading everything I actually never explained that... So yeah. Updated :^)

**Comment by BenWiederhake** [comment]
> assuming we have a way to detect that a program uses ArgsParser anyway. @alimpfard 

How about defining/requiring a very specific symbol? (Not a *section*, but a *symbol*.) In that case, `ArgsParser.cpp` defines the symbol `int program_provides_interactive_suggestions_serenity;`, which can later be detected by parsing the ELF file. If it exists, we know we can safely call the program with `--provide-suggestions-for`, or whatever scheme you prefer.

Advantages:
- Everything that uses ArgsParser would be automatically compatible with it, just like `--help` automatically works.
- Detection is very reliable: No false negatives, and false positives are extremely unlikely.
- Does not need any special interaction with the compiler. All magic is contained in `ArgsParser.cpp`.
- Other implementations are easily possible, they just need to define a symbol (trivial) and support the command-line argument (necessary anyway).

Inconvenient:
- Doesn't work if ArgsParser is loaded as a dynamic library. Everything else can still be made dynamic though.
- The actual symbol either contains some C++-ish mangling, or we need some `export "C"`.
- The Shell would need to do some inspection of the executable file: parsing the ELF, checking all public symbols.
- Optimizing compilers *may* end up pruning the symbol entirely. That would surprise me a lot though.
- Doesn't work on scripts (shell/lua/python/etc.).

**Comment by bugaevc** [comment]
> In that case, `ArgsParser.cpp` defines the symbol `int program_provides_interactive_suggestions_serenity;`

But that provides absolutely no indication the program actually uses `ArgsParser` to parse its arguments; it only means the program links against LibCore.

**Comment by BenWiederhake** [comment]
> It only means the program links against LibCore.

Oh! Good point, I overlooked that.

How about splitting off ArgsParser into `LibArgsParser`? That would solve that problem. Of course, if something links against LibArgsParser without using it, then all arguments against program-providing-their-own-suggestions apply, just like for all other such proposals.

**Comment by bugaevc** [comment]
Sorry, but I don't think that's a good idea 🙁 — for a variety of reasons, let me name just a few:
* This whole feature (and the changes required to get there) should be non-intrusive — it should require little [changes] of the system to support it. Adding another special argument to `ArgsParser` is non-intrusive, but splitting it off to a separate library is anything but.
* Since almost every executable on the system uses `ArgsParser` (or at least they should be!), we'll either have to explicitly link each one to LibArgsParser, make it automatic (like currently all the userland executables automatically link to LibCore), or make some larger library like LibCore depend on it. The former one is tedious, the two latter ones defeat the entire purpose of splitting it off.
* Even now, people tend to want to skip using `ArgsParser` for simple utilities; because it's tempting to quickly write
  ```cpp
  if (argc < 2) {
      printf("Usage: foo bar\n");
      return 1;
  }
  use(argv[1]);
  ```
  and get on with the program logic. We want everything, even simplest utilities, to use `ArgsParser` — but requiring an explicit action to link against it would decrease its appeal for quick & simple utilities by a lot.

Myself, I still believe we shouldn't overthink this, and just sandboxing/pledging the program and invoking it with a special option should be enough. If the program doesn't recognize the special option, it'll just exit with an error instead of emitting valid JSON — provided we, again, sandbox it so that it cannot do anything else.

**Comment by alimpfard** [comment]
I've made another attempt at implementing this, and this time it's quite nice (https://github.com/SerenityOS/serenity/pull/13212), the only remaining concern is limiting what the executed command can do via _at least_ `unveil("/", "rx");` and somehow allowing it to go past the initial unveils that most applications have

**Comment by kleinesfilmroellchen** [comment]
I consider this implemented, while there's work to be done this issue doesn't have to be open anymore.
