### ISSUE TITLE
Ladybird: cannot scroll on warpdesign.fr

### ISSUE THREAD

**Issue by warpdesign** [SerenityOS/serenity#23599]
Scrolling doesn't work on [warpdesign.fr](https://warpdesign.fr): the scrollbar is visible on the right but trackpad gestures and drag/dropping the scrollbar does nothing.

Also, there are endless `Can't keep up...` messages in the terminal:

https://github.com/SerenityOS/serenity/assets/199648/5a3c2bc2-c2fd-4b73-8fe0-40d352191a65

**Comment by DanShaders** [comment]
Hmm, this "Can't keep up" spam might be a separate issue. Can you figure out which timer causes it?

Since I don't think there is a time-travel debugger for MacOS, it probably won't be as straightforward as I wished it would be but you can do something like this:

1. Connect to WebContent with gdb (or whichever debugger there is on macos)
2. Break [here](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibCore/EventLoopImplementationUnix.cpp#L187) on an offending timer
3. Figure out what is `strong_owner`
4. Break [here](https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibCore/ThreadEventQueue.cpp#L98) when `reciever` is the same as the `strong_owner` from the previous step
5. Step into a few times and at some point you will fall through to the handler of that timer and then it should be obvious to understand the purpose of the timer.
