### ISSUE TITLE
REGRESSION: AK: Crash in base64 decoding when loading ECMA262 spec in Ladybird

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#23689]
Repro that can be appended to TestBase64.cpp

```cpp
TEST_CASE(decode_base64)
{
    auto input = "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMC42MDUiIGhlaWdodD0iMTUuNTU1Ij48cGF0aCBmaWxsPSIjODg5IiBkPSJtMi44MjggMTUuNTU1IDcuNzc3LTcuNzc5TDIuODI4IDAgMCAyLjgyOGw0Ljk0OSA0Ljk0OEwwIDEyLjcyN2wyLjgyOCAyLjgyOHoiLz48L3N2Zz4"sv;
    MUST(decode_base64(input));
}
```

Regressed with 81ad6de41be4826072881899e105d7182eb5dbc2

cc @trflynn89

**Comment by tcl3** [comment]
This oss-fuzz issue appears to produce a similar crash: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=67565.

**Comment by trflynn89** [comment]
Looking at this, it seems to be because the input is invalid (it's length is not a multiple of 4). Do we want to reject these outright? The web has "forgiving base64" via `atob` - not sure we need AK's impl to be so forgiving.

Related - commit f2663f477fc010ce6450b759d342228bfa403714 added support for skipping whitespace. This makes it tricky/slow to know the exact output length. That commit mentions it's only for web things, which should also now not be an issue since web uses our forgiving impl. Any objection if that's removed?
