### ISSUE TITLE
LibWeb: Support server-sent events

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#23847]
After logging in to https://polar.sh/ I get this error message:

`'EventSource' is not defined`

Seems like we need to implement [server-sent events](https://html.spec.whatwg.org/multipage/server-sent-events.html) from the HTML specification!

![image](https://github.com/SerenityOS/serenity/assets/5954907/7c62350e-1dbd-466b-b90c-f92f699fcc04)

## Funding

- We're currently trying [Polar.sh](https://polar.sh/SerenityOS) where you can help fund the work on this issue.
- Contributor(s) receive the funding once the issue is completed & confirmed.

<a href="https://polar.sh/SerenityOS/serenity/issues/23847">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/SerenityOS/serenity/issues/23847/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/SerenityOS/serenity/issues/23847/pledge.svg">
</picture>
</a>

**Comment by trflynn89** [comment]
I have the bulk of this implemented here:
https://github.com/trflynn89/serenity/tree/event_source

And I've written a test server here, since this only works with HTTP/HTTPS requests due to CORS:
https://github.com/trflynn89/sse-demo

The problem is that we currently cannot receive partial responses from RequestServer. The SSE response basically never completes by design, but continuously streams data. @alimpfard any suggestion for handling that? I can see the events streaming in here, but `request_done` stays `false`:
https://github.com/SerenityOS/serenity/blob/93ba99f14a4aa70161610d1246d3be5b660ba536/Userland/Libraries/LibProtocol/Request.cpp#L71

**Comment by awesomekling** [comment]
Thank you @trflynn89 for contributing to close this issue! ⭐

The rewards from this issue, totaling $200, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._
