### ISSUE TITLE
LibWeb: Deformed text on brave.com

### ISSUE THREAD

**Issue by theonlyasdk** [SerenityOS/serenity#24252]
#### How it should look like (screenshot from Chrome):
![image](https://github.com/SerenityOS/serenity/assets/168300808/fcbbd45d-cc40-459b-ae7b-a5f284640b47)
#### How it looks like in Ladybird:
![image](https://github.com/SerenityOS/serenity/assets/168300808/6c504e6b-8624-4119-99dd-75d6ab00a111)

### Steps to reproduce:

1. Go to `brave.com`
2. Scroll down to the **Advanced Features** section
3. See deformed text under 3rd card

**Comment by trnxdev** [comment]
I don't think it's the text, but rather something else, because the bluriness depends on the zoom (Ctrl + or Ctrl -)
![image](https://github.com/SerenityOS/serenity/assets/94789999/c85c038e-1b0d-4454-ae32-80f62a6d128a) (90%)
![image](https://github.com/SerenityOS/serenity/assets/94789999/5bdeb831-bb9e-41bf-ae7b-1d6e412d1fe6) (100%)
![image](https://github.com/SerenityOS/serenity/assets/94789999/da3cc767-e837-434d-8493-1e06c778a9a0) (110%)

**Comment by theonlyasdk** [comment]
Hmm, if that's the case then it is probably a misplaced div with a blurred background?

**Comment by trnxdev** [comment]
Uhhh
![image](https://github.com/SerenityOS/serenity/assets/94789999/3d34d950-bc47-4b8b-9751-bb6b983ae7dc)

**Comment by theonlyasdk** [comment]
Hmm, I assume the inspector text is also written in HTML? Let's wait until someone who works in this area looks into this issue

**Comment by Hendiadyoin1** [comment]
It seems to me that it's this ::after pseudo element, but I can't quite tell where it comes from
![grafik](https://github.com/SerenityOS/serenity/assets/37629766/6693f87b-8632-45c8-a615-60f2faa6a679)
