### ISSUE TITLE
How to build LibJS as a standalone executable?

### ISSUE THREAD

**Issue by guest271314** [SerenityOS/serenity#24751]

**Comment by guest271314** [comment]
I found this  

> How can I try it?
>
> - Integrated into esvu and eshost (Thanks Idan!)

and this https://news.ycombinator.com/item?id=30859279.

Running `js` in repl mode right now. Looking forward to testing.

It would still be helpful to have build instructions specifically for LibJS. Thanks.

**Comment by ADKaster** [comment]
Following the regular build instructions and running `./Meta/serenity.sh run lagom js` will build the `js` REPL binary from source, and execute it. But as you have discovered, we do publish a GitHub artifact for each master build that's picked up by esvu. 

However, a few weeks ago we moved the main development for LibJS to github.com/ladybirdbrowser/ladybird. As such, esvu is picking up the artifact from that repository instead of from Serenity.
