### ISSUE TITLE
Kernel: Implement something like OpenBSD's pledge()

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#249]
This is downright reasonable:

https://man.openbsd.org/pledge.2

Let's implement it, or something similar in Serenity :)

**Comment by Jookia** [comment]
pledge looks good, but I question some of its design choices: execpromises being separate and not a subset of promises, and the promises themselves being a bit too low level or specific.

Personal quick opinions:

Good: stdio, tmppath, inet, unix, proc, exec, prot_exec, id, unveil, tty
Too low level: rpath, wpath, cpath, dpath, fattr, sendfd, recvfd
Too specific: chown, flock, dns, settime, ps, vminfo, tape, pf, audio, video, bpf

'error' seems problematic for programs that don't check syscall return values against ENOSYS.

**Comment by christopherdumas** [comment]
If we end up building a better version of pledge that could be a cool claim-to-fame (at least in some communities) for Serenity. I don't have the time/ability right now, but if someone could make a design doc for this that would be great.

**Comment by pimpale** [comment]
Perhaps we could use it as the foundation for a capabilities based system. By embedding something like this into the file system or program header, we could enforce pledges on programs without any need to modify program code. 

OpenBSD's pledge is somewhat coarse grained, encompassing large groups of functions, so it wouldn't be applicable for everything, especially on the more specific side (such as if you wanted to pledge to use one port only, or pledge to use one file only, or any other combination) 

However, this coarse grained nature could have benefits. Since there are only 31 types of pledges, we could theoretically assign each pledge a bit (with the 32nd bit representing no pledge, or all permissions available). That allows us to fit it into a very simple flags structure taking up only 4 bytes.

We could then put this structure associated with the executable, so that whenever it is run, it takes on these pledges by default, without any work on the program developer's part. 

A possible location for this struct that may be of interest is extended file attributes. The ext2 file system theoretically supports these, so it wouldn't break compatibility to use these xattrs to store the struct.

Another, more radical, idea would be to modify the ELF header structure to add on this field. It would allow the transfer of these pledges simply by copying the file, without worrying about the underlying file system. Depending on implementation, a patch to GCC may be necessary.

**Comment by christopherdumas** [comment]
I worked with @pimpale on this idea, I think it's pretty good but it would require quite a bit of work. I haven't worked much on the kernel yet though, so this might be something I'd like to at least start the work on. I'd prefer if we went the xattrs route, but that depends on how far along our ext2 implementation is. In theory, if it already has xattrs, getting these options to the kernel should require only fairly minimal work on the binary loader (which I don't know the location of lol), although actually making the permissions system would clearly be more difficult.

**Comment by Jookia** [comment]
I think there's a mix of thinking here between entering restricted modes of execution and limiting what a process can do. The former would be something like 'let me open a secret at the start of the application, then forbid myself from re-opening it by restricting what I can do'. The latter would be something like capabilities of what an executable can do outright, or enforcing strict security policies using something like a filesystem firewall. pledge+unveil seems to be built to allow you to do both of these things.

**Comment by awesomekling** [comment]
Right, so this bug is specifically about implementing a mechanism whereby a process opts in to new limitations at runtime.

**Comment by christopherdumas** [comment]
That's a good point, should I create another issue to suggest this capabilities based system?

**Comment by bugaevc** [comment]
I'm a big fan of capabilities, but I'm unsure if they're something Serenity should have. It was my understanding that Serenity tries to stick to classical Unix design (for low-level userspace and syscalls, that is) instead of trying to introduce something more innovative like a microkernel, Plan 9 features (namespacing, FS in userspace, union mounts, network transparency), and, well, capability-based security. `pledge()` sounds like a reasonable extension of Unix, while full-blown capabilities (of which again I'm a fan of) sound like they go against Serenity's intended design.

That being said, there is another natural Unix extension that gets fds most of the way towards being capabilities: `SCM_RIGHTS`. I would like to see Serenity support that, and that would also make it possible to remove the ad-hoc "shared buffers" support from the kernel.

**Comment by bugaevc** [comment]
> Perhaps we could use it as the foundation for a capabilities based system. By embedding something like this into the file system or program header, we could enforce pledges on programs without any need to modify program code.

Oh, you're talking about the other kind of capabilities. Sorry then, disregard the first paragraph above :smile:

**Comment by Jookia** [comment]
FreeBSD's Capsicum would be a very interesting way to introduce capability-based security. Something lighter like seccomp but with sending file descriptors would be cool too.

**Comment by christopherdumas** [comment]
@bugaevc I suppose capabilities aren't in like with traditional UNIX, so that's a point against them, plus it would be a lot of work. Re: `SCM_RIGHTS`, it seems extremely limited and barely useful (it only deals with file access for sockets), so we should probably end up having it just for compatibility but I would hardly call it a capabilities system. My first instinct is to say that if we're going to do capabilities-related stuff, we should just do it right.

**Comment by christopherdumas** [comment]
@bugeavc whoops! And I just wrote a reply too. lol no worries.

**Comment by christopherdumas** [comment]
@Jookia I don't know what that is, could you elaborate on the pros and cons of that vs. externally inforcing a pledge?

**Comment by Jookia** [comment]
Here's a good paper on it: https://papers.freebsd.org/2010/rwatson-capsicum.files/rwatson-capsicum-paper.pdf It extends the design of Unix to add capabilities.

**Comment by christopherdumas** [comment]
Cool, thanks.

**Comment by awesomekling** [comment]
> I'm a big fan of capabilities, but I'm unsure if they're something Serenity should have. It was my understanding that Serenity tries to stick to classical Unix design (for low-level userspace and syscalls, that is) instead of trying to introduce something more innovative like a microkernel, Plan 9 features (namespacing, FS in userspace, union mounts, network transparency), and, well, capability-based security. `pledge()` sounds like a reasonable extension of Unix, while full-blown capabilities (of which again I'm a fan of) sound like they go against Serenity's intended design.

@bugaevc has the right idea. Kernel-wise, Serenity aims to be a simple and understandable implementation of the classic Unix philosophy.

**Comment by awesomekling** [comment]
`pledge()` is in
