### ISSUE TITLE
Piano: Notes missing in exported audio

### ISSUE THREAD

**Issue by willmcpherson2** [SerenityOS/serenity#2578]
Open Piano and fill the roll with C-D-C-D..., then export. Play the audio with `aplay`. Some notes will be missing.
Again, I don't remember this bug existing since the last time I worked on Piano, so I'm assuming this is a regression. I would `checkout` some old commits but switching between build systems is a bit of a pain...

**Comment by willmcpherson2** [comment]
@Petelliott 
Any info on this? I've got no idea where to even start looking

**Comment by Petelliott** [comment]
I did notice 2 things when I was looking at this:
1) The notes are completely missing (like all zeros in hexeditor) rather than just quiet or something.
2) The pathological case seems to be 2 of the same note, one at the start and one within three slots from the end.

What I never understood is what is different about playing the music vs. writing it to a file. They looked the same to me.
