### ISSUE TITLE
Kernel: /proc/PID/stack, /proc/PID/regs broken

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#2678]
cc @tomuta 

These broke with the SMP changes. They were relying on up-to-date register information in Thread::tss().

Note that the current process can still get its own stack trace by opening /proc/PID/stack, but other processes cannot be inspected. Easily noticed in SystemMonitor, by trying to look at stacks for processes other than SystemMonitor itself.

**Comment by tomuta** [comment]
Dang, let me see what I can figure out

**Comment by tomuta** [comment]
The problem is that the TSS structure was previously updated automatically by the CPU on each context switch. Since we don't use that hardware feature anymore, the only purpose is to set up a thread and to store and restore the eip/esp on a context switch. It probably should be renamed at this point, because it's not really the TSS anymore. The user mode registers are now only on the trap frame on the kernel stack, so we probably need to look there to get that information. And we need to hold the scheduler lock while doing so, possibly reusing `Thread::get_register_dump_from_stack`. The kernel mode registers (not all, though) would be last pushed to the kernel stack by `Processor::switch_context`.

So I for /proc/*/regs we can only really get the user mode registers, but I think for /proc/*/stack we can walk the kernel and user stack (since ebp/esp for kernel mode is saved by `Processor::switch_context`.

Is this how these should be working? I'm not sure if it's possible to get accurate general purpose registers of the kernel mode environment without triggering an interrupt while that thread is running.

**Comment by awesomekling** [comment]
I think we can get rid of `/proc/PID/regs` entirely since we have `ptrace()` now anyway.
The stacks are still very useful :)

**Comment by tomuta** [comment]
Removing it makes it a bit easier :) I'll look into the backtraces later today
