### ISSUE TITLE
Kernel: Mysterious process hangs after SMP changes

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#2693]
cc @tomuta 

I keep seeing random process hangs after the SMP changes.
One slightly unreliable way to reproduce:

1. (Re)boot the system.
2. Run `ls | ls` in the terminal.
3. If control returns to the shell, goto 1. Otherwise you have reproduced the bug.

**Comment by tomuta** [comment]
Do you have any stack traces? I can't seem to be able to reproduce it :(

**Comment by tomuta** [comment]
Oh just as I wrote it I managed to reproduce one using Browser. Let me see what I can figure out.

**Comment by awesomekling** [comment]
Hunch: Perhaps we are doing a context switch at a bad time after `exec()` and we're missing some logic to suppress context switches there.

**Comment by tomuta** [comment]
Hm, not sure if this is really what's going on. While I can see a context switch happen during a fork sometimes, it doesn't look like it clobbers registers as they match when it gets scheduled again, which makes sense because technically it may clobber them but it left off at the same spot anyway when switching out. It seems like what sometimes happens is that threads get stuck in `Queued` state somehow and never seem to get out of it.

**Comment by tomuta** [comment]
I enhanced the `Thread::wait_on` to store the wait reason, and changed `Scheduler`'s `SCHEDULER_RUNNABLE_DEBUG` logging a bit, when this happens it seems like the processes get stuck in `Queued` state due to `Inode`. Not sure how or why, but this is what's getting logged while in this condition:

```
[colonel(0:0)]: Scheduler[0]: Switch to colonel(0:0) @ 0008:c011eff0
[colonel(0:0)]: Non-runnables:
[colonel(0:0)]:   Queued       (futex) AudioServer(14:21) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    ClipboardHistory.MenuApplet(10:10) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    Audio.MenuApplet(11:11) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    UserName.MenuApplet(18:18) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    DHCPClient(17:17) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    AudioServer(14:14) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    SystemMenu(16:16) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (FinalizerTask) FinalizerTask(3:3) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    SystemServer(4:4) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    LookupServer(40:40) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (PATAChannel) ProtocolServer(38:38) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (NetworkTask) NetworkTask(5:5) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (FS) Browser(37:37) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    Taskbar(20:20) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (FS) ResourceGraph.MenuApplet(12:12) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (Inode) ResourceGraph.MenuApplet(19:19) @ 0008:c011eff0
[colonel(0:0)]:   Waiting      Shell(22:22) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (Inode) Shell(42:42) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (Inode) Shell(41:41) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (FS) SyncTask(2:2) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    Clipboard(9:9) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    Clock.MenuApplet(15:15) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    Terminal(7:7) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    FileManager(8:8) @ 0008:c011eff0
[colonel(0:0)]:   Selecting    WindowServer(13:13) @ 0008:c011eff0
[colonel(0:0)]: Runnables:
```
These are the two `ls` instances that are stuck and don't ever seem to get out of it:
```
[colonel(0:0)]:   Queued       (Inode) Shell(42:42) @ 0008:c011eff0
[colonel(0:0)]:   Queued       (Inode) Shell(41:41) @ 0008:c011eff0
```
Seems like everything disk related is somehow stuck, `ProtocolServer` is waiting on `PATAChannel` and other stuff is waiting on the `Lock` named `"FS"`. The `Browser` also happens to be locked up waiting for `Lock` named `"FS"`...

I wonder if there's still something wrong with `PATAChannel`, it certainly has given me a lot of grief so far :(

**Comment by tomuta** [comment]
I think I traced it to a problem with `Lock`, `WaitQueue` and `Thread::wait_on`.

**Comment by tomuta** [comment]
I don't think it's related, but I seem to be losing my Terminal frequently while trying to replicate this `ls | ls` issue when something else (e.g. Browser) is under heavy load. Seems unrelated to this issue, though:
```
[Shell(354:354)]: CPU[0] NP(error) fault at invalid address V0xedededfb
[Shell(354:354)]: Unrecoverable page fault, read from address V0xedededfb
[Shell(354:354)]: Note: Address V0xedededfb looks like it may be recently free()'d memory
[Shell(354:354)]: CRASH: CPU #0 Page Fault. Ring 3.
[Shell(354:354)]: exception code: 0004 (isr: 0000
[Shell(354:354)]:   pc=001b:08072037 flags=0246
[Shell(354:354)]:  stk=0023:00e026e8
[Shell(354:354)]:   ds=0023 es=0023 fs=0023 gs=002b
[Shell(354:354)]: eax=00000000 ebx=edededfb ecx=00000000 edx=edededfb
[Shell(354:354)]: ebp=00e026e8 esp=c5df8fe8 esi=0808cb01 edi=00000000
[Shell(354:354)]: cr0=80010013 cr2=edededfb cr3=03287000 cr4=00300ee4
[Shell(354:354)]: code: 80 3c 02 00 74 03 40 eb
[Shell(354:354)]: 0x08072037  strlen +8

[Shell(354:354)]: 0xc015e103  _ZN6Kernel7Process5crashEijb +1013
[Shell(354:354)]: 0xc011d712  illegal_instruction_handler +0
[Shell(354:354)]: 0xc011f8c8  page_fault_handler +945
[Shell(354:354)]: 0xc011c421  page_fault_asm_entry +38
[Shell(354:354)]: 0x0806a692  vfprintf +546
[Shell(354:354)]: 0x0806bc4b  fprintf +21
[Shell(354:354)]: 0x08050724  _ZN5Shell12custom_eventERN4Core11CustomEventE +184
[Shell(354:354)]: 0x0805a840  _ZN4Core6Object14dispatch_eventERNS_5EventEPS0_ +74
[Shell(354:354)]: 0x0805489f  _ZN4Core9EventLoop4pumpENS0_8WaitModeE +307
[Shell(354:354)]: 0x08054a1d  _ZN4Core9EventLoop4execEv +43
[Shell(354:354)]: 0x08048977  main +1382
[Shell(354:354)]: 0x08048c2e  _start +94
```
On the bright side, I think I have the changes needed to fix this, or at least it seems a lot better now.

**Comment by awesomekling** [comment]
Yeah that shell issue is clearly separate. :)

What's the kernel fix?

**Comment by tomuta** [comment]
Well I thought I had it fixed but then ran into it again. Then I made another small change which uncovered another set of problems. The hang, when it happens, is caused by the fact that the Finalizer never finalizes it. But how it gets there is more complicated. Still trying to get it work with my latest changes. Problematic is certain cases where threads are dying, initial threads etc, how they affect the scheduler lock and critical sections.

**Comment by nico** [comment]
I can reproduce this very reliably. Most of the time the system doesn't make it far enough to bring up Terminal. Even if it does, WindowServer eventually stops running (usually fairly quickly after boot).

I have fairly fast processors; maybe that exacerbates the issue.

I get this even if I change run.sh to say `-smp 1` instead of the default `-smp 2`. Maybe futzing with that number makes it repro better for you though (`-smp 20` makes boot usually not complete over here).

**Comment by tomuta** [comment]
OK I think I got it working now, at least with a lot of logging. Let me clean up my changes and see if they work without all the logging as well, and then I'll create a merge request so you can try if it resolves these problems.

And yes, a faster CPU probably makes it more likely I think.

**Comment by tomuta** [comment]
So I just need to resolve this hang, I think the other pieces I have resolved now but the hang still persists. But I think I now know why. There's a race condition with the `g_finalizer_has_work` variable and the `g_finalizer_wait_queue`. Basically, when this hang happens it's because the Finalizer is currently busy in `Thread::finalize_dying_threads`, so we flip the `g_finalizer_has_work` to `true` and call `WaitQueue::wake_all`, but because the `FinalizerTask` isn't yet in `Thread::wait_on` the `WaitQueue::wake_all` has nobody to wake. So, then the FinalizerTask finally finishes and calls `Thread::wait_on`, but now there's nobody calling `WaitQueue::wake_all` anymore, because it's already flagged as having been notified.

**Comment by tomuta** [comment]
It's almost like the `WaitQueue::wake_*` APIs would need to flag that a wake was requested, so that next time `Thread::wake_on` is called, it immediately performs the requested wake? Thoughts?

**Comment by tomuta** [comment]
Enhancing the `WaitQueue` seems to have solved this problem, though the other changes are also necessary. But that seems to have been the last piece of the puzzle. Let me clean up and then I'll create a merge request with my changes.
