### ISSUE TITLE
Libraries are completely rebuilt when a .cpp file in a dependency changes

### ISSUE THREAD

**Issue by Petelliott** [SerenityOS/serenity#2877]
For instance, if I change `Libraries/LibCore/File.cpp` all l.cpp files in all libraries/applications that depend on it are rebuilt.

**Comment by alimpfard** [comment]
rebuilt, or just re-linked?
the later is to be expected, we statically link everything as shared object loading is still a WIP.

**Comment by Petelliott** [comment]
each cpp file in the library Is rebuilt, not just relinked.

**Comment by alimpfard** [comment]
I guess I never noticed because ccache :shrug:

**Comment by bugaevc** [comment]
> For instance, if I change `Libraries/LibCore/File.cpp` all l.cpp files in all libraries/applications that depend on it are rebuilt.

That's not true. To see it for yourself, try touching a file in LibGUI instead, you'll see that GUI apps get relinked, but no other .cpp files are recompiled. Now, LibCore is a bit special 'cause it's used by code generators, so changing LibCore will regenerate those files/headers, and cause everything that includes those headers (but not *all cpp files in all libraries/applications*) to be recompiled.

So this kind of dependency tracking between code generators & generated code is not only not a bug, but a very cool & desirable feature of CMake. See also: https://github.com/SerenityOS/serenity/pull/2519

**Comment by nico** [comment]
Ninja (and I think Make) have a 'restat' feature where they stat the output of a build command after it ran, and if the build command didn't touch the output file, then it cancels the build actions down that path. That means if the code generators read the output file (if it exists) and exited early if what they were to write is identical to what's already there, then that optimization could fire and most of these compiles would get canceled if the output of the code generators didn't change since the last build.
