### ISSUE TITLE
Shell assumes that stdin should be a tty

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#2989]
Examples:

1. `Shell -c ls < /dev/null` This runs ls fine, but it first complains that "ttyname_r: Not a TTY". It probably just shouldn't complain.
2. `Shell -c 'echo ls | Shell'`dies with "Good-bye!: Not a TTY" the first time I run it, then the next I run it it prints the output in (1) instead and breaks the Terminal session.

(The background is that ninja runs subprocesses in `sh -c some_command` with stdin replaced with /dev/null.)

**Comment by alimpfard** [comment]
This might also be a LibLine issue, since it assumes that stdin/out are connected to a tty, so it goes and asks for the cursor position.
But with the stdin replaced with some pipe that has `ls\n` in it, it'd just read that stuff and save it for later, get an EOF, then everything goes downhill from there.
