### ISSUE TITLE
ctrl-z and `bg` print in Shell both print "killpg: No such process"

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#3083]
1. Start any GUI app in terminal (`te`, `br`)
2. Hit Ctrl-Z
3. Type `bg`

Expected: Does its thing.
Actual: After 2, prints "killpg(job): No such process". After 3, prints "killpg: No such process".

@alimpfard Sorry about being such an enthusiastic Shell user.

**Comment by alimpfard** [comment]
Surprise surprise, bisect leads to 7bdf54c.

@BenWiederhake it seems your fix found its first bug, or your fix itself has a bug

**Comment by alimpfard** [comment]
It seems that `setpgid()` required the session id to be set (correctly, I assume?) now, and so a call to `setsid()` fixes this.

**Comment by BenWiederhake** [comment]
Are you sure the SID is the cause of it? So far, all Shell subprocesses ran under the same SID, which is "correct" and should not need to change.

Also, you're not checking the return values of `setsid` and `setpgid`, which very much can fail. For example, `setpgid` *will* fail when you call it immediately after a successful `setsid`, but also `setsid` assigns a new pgid automatically if successful. It's difficult to argue what's happening when all return codes are dropped. ^^'

**Comment by alimpfard** [comment]
Hmm...I'll add some checks, let's see

**Comment by alimpfard** [comment]
`setsid()` runs without issues, but `setpgid()` fails with `EPERM`.

note that `setpgid()` failed with `EPERM` before the addition of `setsid()` as well.

it seems that `setsid()` does what I need `setpgid()` to do anyway, so I guess that `setpgid()` call is not required.

**Comment by BenWiederhake** [comment]
> setsid() runs without any issues, but setpgid() fails with EPERM.

As predicted.

> note that setpgid() failed with EPERM before the addition of setsid() as well.

That original failure is the actual bug.

> it seems that setsid() does what I need setpgid() to do anyway, so I guess that setpgid() call is not required.

Running separate "pipes" as separate sessions doesn't fit the original spirit, but that's fine.

However, this *will* cause problems for things like `foo | bar`, when both foo and bar are supposed to write to the same stderr at any point. If they have different SIDs, then they have different PGIDs, so depending on what you pass to `tcsetpgrp`, only one of them can write to stderr. Or do both foo and bar still run in the same PGID?

**Comment by alimpfard** [comment]
I believe every atomic command gets its own session now, I'm not entirely sure if the current abstraction can handle setting the same pgid for all commands in a pipeline.
Will handle that later, I guess. that bug was there from the start anyway

**Comment by BenWiederhake** [comment]
> I'm not entirely sure if the current abstraction can handle setting the same pgid for all commands in a pipeline.

How do you do job control then? All commands in a pipeline need to be stopped/continued/terminated/killed. That's what process groups were intended for: `killpg(job.pgid)`
Of course you can also remember the individual pgids in a `foo | bar | baz | quux` pipeline, but that sounds unnecessarily complicated given that this feature already exists :P

**Comment by alimpfard** [comment]
Sorry to disappoint (again) but currently, job control does not handle pipelines (or even `&&`) correctly...

**Comment by alimpfard** [comment]
I cannot, for the life of me, figure out how this should work,

imagine `a | b`:
- (parent) fork for `a`
- (parent) somehow move `a` to a new process group?
    - `setpgrp()` `EPERM`'s in the parent - (why?)
- (parent) set terminal pgrp to `a`'s pgrp
- (parent) fork for `b`
- (parent) somehow move `b` to `a`'s process group?

**Comment by alimpfard** [comment]
`Process::get_sid_from_pgid()` would return `-1` if the process group is empty, and `setpgid()` would fail.

I'm about 99% sure this is not intended.

**Comment by BenWiederhake** [comment]
So I believe the "intended" way this is supposed to work is the following (I reconstructed this after reading all the manpages about setsid, setpgid, etc., and before touching the Kernel):
- In a command like `foo | bar | baz`, all processes should be in the same process group.
- Job control can then work by a single call to killpg. (Also, it makes it easy to use `tcsetpgrp`.)
- setpgid can be invoked by the parent or the child (the sid and uid stuff "just works" here). Note that this only works if you *don't* call setsid! Otherwise, you'd be trying to move a process across the magical session boundary, which apparently is a big no-no. Maybe that is the reason for the EPERM you saw? Also, `Process::get_sid_from_pgid()` should *never* return -1 for an actual pgid that is currently in use (technically "pgid of a non-empty process group"), at least that's my current understanding of the code.

So the flow *can* be something like this (I try to keep it as general as possible, but there are other ways to do it):
- The Shell may call setsid() during startup. (I recommend it does so if and only if it's running interactively.)
- For each pipeline (`foo | bar | baz`), a single pgid is generated somehow. A very efficient way to do this is forking and calling `setpgid(0, 0)`.
- Note that the pgid is inherited across `fork()`. So if the "pipeline process" just forks into the subprocesses, you don't need to call `setpgid` again.

If that is too incompatible with how `Shell` currently works: There's always a different way to do it. But if the parent tries to set the pgid, then you have a race between exec and setpgid. That is only rarely a problem, but … at least it's weird. So you would need another step of synchronization, and … ugh. That's why I suggest the child to do the setpgid'ing: Fewer points of failure, simpler control flow.

Of course, it's very much possible that you've found a bug how the Kernel handles those calls. If so, please include:
- getpid, getpgid, getsid *before* the setXXX call
- which syscall, which errno
- getpid, getpgid, getsid *after* the setXXX call
This makes it easier to determine which cornercase of setpgid we're talking about :P

**Comment by alimpfard** [comment]
- For the `setpgid()` bug, please see https://github.com/SerenityOS/serenity/pull/3085#discussion_r468510548 where `Process::get_sid_from_pgid()` would (rightly) return -1 if the pg doesn't exist (yet), but it would be created via the very syscall that's checking for it

- For calling `setpgid()` in the child, there's always going to be a communication/synchronisation step required, if we call it in the parent, we have to wait in the child, if we call it in the child, we'd have to somehow tell the parent what that pgid was

**Comment by nico** [comment]
Re second point: Maybe the shell could fork for a pipeline, the (single) child could setpgid() and then fork for each child in the pipeline, each already having the right process group now?

**Comment by alimpfard** [comment]
Ideally, that would happen, but a pipeline isn't even detectable at that point in execution.
by the time a `Command` gets created, we only have a kinda-sorta stringed tree representing pipelines (and not even in order).

**Comment by BenWiederhake** [comment]
- If the children call `setpgid(0, given_pgid)`, then they need to somehow wait until the `setpgid(0,0)` that creates the PGID has finished.
- If the shell does it, then the shall has to wait until the PGID actually exists.

**Comment by nico** [comment]
Fixed, right?

**Comment by alimpfard** [comment]
Should be~
