### ISSUE TITLE
LIBC_PROFILE_MALLOC=1 causes kernel to assert

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#3182]
1. `export LIBC_PROFILE_MALLOC=1` (in a terminal in serenity)
2. Run any command that mallocs

Expected: Command creates a json file called perfcore.XXX in the current directory.
Actual: `[disasm(23:23)]: ASSERTION FAILED: Kernel::is_user_range(VirtualAddress(src_ptr), n)` in `[disasm(23:23)]: 0xc015dc7a  Kernel::PerformanceEventBuffer::append(int, unsigned int, unsigned int) +230`

That line was touched recently(ish) in 16783bd14d5284542205a50c441562c19174f101 so maybe that's related (@tomuta).

**Comment by nico** [comment]
16783bd looks unrelated on second look.

**Comment by tomuta** [comment]
The problem is this:

https://github.com/SerenityOS/serenity/blob/b0aa8115c2c1d240edc75bbd5263f7dc2ca3d28b/Kernel/PerformanceEventBuffer.cpp#L71

The second argument to `copy_from_user` (source pointer) is a kernel pointer, causing the assertion to fail. While I did touch this line in that commit, I didn't really change that part. Not sure how this could have ever worked the way it is right now. Not sure what the code is meant to do, but if it's supposed to copy the code where eip points to then it probably should look like this:
```
copy_from_user(&eip, (FlatPtr*)current_thread->get_register_dump_from_stack().eip);
```
Not sure if that's what is supposed to be done, but it solves the `ASSERT` being triggered.

**Comment by awesomekling** [comment]
`copy_from_user` used to not assert. So it was just a kernel-to-kernel copy all along, with SMAP disabled lol.
