### ISSUE TITLE
ProtocolServer: Spins when downloading a resource from ajax.googleapis.com over HTTP

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3197]
For example: [JQuery](http://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js)

This is because for some reason, we do not send a fin ack to them:
![Wireshark_iq7Z3oGUa4](https://user-images.githubusercontent.com/25595356/90437231-eef05e80-e0c9-11ea-8b3f-597eb6b12d69.png)

The stack from system monitor says that protocol server is spinning waiting for an event:
![vmplayer_fMGlpcndVh](https://user-images.githubusercontent.com/25595356/90438624-2bbd5500-e0cc-11ea-89cb-da24e817c3f9.png)

However, getting a 404 works, so it's not just because it's ajax.googleapis.com.

It works over HTTPS, so no problem there.

**Comment by tomuta** [comment]
The problem is that after it reads the terminating chunk 0 size, `can_read_line` keeps failing here (`m_state` is in `State::AfterChunkedEncodingTrailer`):

https://github.com/SerenityOS/serenity/blob/c711d34276ca0caa37fbef5983ebbb6af1a5fc96/Libraries/LibHTTP/Job.cpp#L121

The server doesn't close the connection, and the client doesn't either because it's stuck in this endless "loop" of having data but being unable to read another line. The reason we can't read another line is because we read the very last empty line here already:

https://github.com/SerenityOS/serenity/blob/c711d34276ca0caa37fbef5983ebbb6af1a5fc96/Libraries/LibHTTP/Job.cpp#L269

Now this code assumes there are no trailing headers (which in this case there aren't), but the naming of `State::AfterChunkedEncodingTrailer` seems to suggest that it probably shouldn't make any assumptions on being able to read any further data. It seems that this state is a little misleading as it would probably be better to replace it with a state `State::Trailers`, which would continue to read lines until an empty line, at which point the transfer would be complete. Then rather than [discarding that line](https://github.com/SerenityOS/serenity/blob/c711d34276ca0caa37fbef5983ebbb6af1a5fc96/Libraries/LibHTTP/Job.cpp#L273), it would just switch the state to `State::Trailers`, which would then be able to read the remaining lines and finish the transfer when encountering the empty line.
