### ISSUE TITLE
Regression: Ctrl-D treated as EOD instead of delete-char during editing

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#3421]
1. Enter "asf"
2. Hit ctrl-a to jump to start of line
3. Hit ctrl-d

expected: "a" is deleted
actual: shell closes

@alimpfard

**Comment by alimpfard** [comment]
This is surprising to me, I doubt it's a regression.
that behaviour has been there since...forever ago, I guess we just never tried ^D with stuff in the buffer and the cursor at the start?

https://github.com/SerenityOS/serenity/blob/18ff9c3fc29a3bd41f6f12d4f209e85ec114ec96/Libraries/LibLine/Editor.cpp#L741

**Comment by nico** [comment]
Hm, in ad8e7849383cf2b72d0470de62716746afebaf18 it basically looked like it looks after 39d14c22d18bc0a32b98c2ba377a17e988107e25 , so I think it worked fine back then. Looks like this regressed in 32839d40e34412786df0943d9a063be50a6eabc7.

Thanks for the fix!

**Comment by alimpfard** [comment]
Oh yeah, I see the regression in 32839d4. wonder what else that commit broke...
