### ISSUE TITLE
CoreIPCClient: ASSERTION FAILED on boot

### ISSUE THREAD

**Issue by rhin123** [SerenityOS/serenity#348]
Sometimes when I boot-up serenity this error occurs, causing serenity to freeze on boot. I'm really sure how to re-create this error so I'm kinda at a loss...
`CSocket{0x0106d03a} connecting to /tmp/wsportal...
USERSPACE(10) ASSERTION FAILED: false
/home/ryan/Documents/serenity/Libraries/LibCore/CoreIPCClient.h:151 in bool IPC::Client::Connection<ServerMessage, ClientMessage>::post_message_to_server(const ClientMessage&, const AK::ByteBuffer&&) [with ServerMessage = WSAPI_ServerMessage; ClientMessage = WSAPI_ClientMessage]
`

**Comment by rburchell** [comment]
That would mean that a client failed in writing to WindowServer failed for some reason. The real reason is likely further up in the boot log (likely WindowServer crashing, or something worse).

How often do you think you are hitting this? 1/10 boots? 3/10?

That having been said, there's been a bunch of fixes in the kernel recently, so it might be worth seeing if a more recent build has the same problem.

**Comment by rhin123** [comment]
It's around 1/25 of the time. I'll try to sync up with the latest patch and see if anything changes.

**Comment by rburchell** [comment]
Can you please try #355 if you still have issues?

**Comment by rburchell** [comment]
Sorry, I wasn't looking at the source of the assert :) I think this should now be fixed through #356.
