### ISSUE TITLE
Kernel::IRQHandler: change_irq_number disables interrupts, but uses change_interrupt_number which expects interrupts to be enabled

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#3531]
IRQHandler::change_irq_number:
https://github.com/SerenityOS/serenity/blob/07d4b41bac1330804ad2bb4cd7656e5c8ca14717/Kernel/Interrupts/IRQHandler.cpp#L79-L84

GenericInterruptHandler::change_interrupt_number:
https://github.com/SerenityOS/serenity/blob/07d4b41bac1330804ad2bb4cd7656e5c8ca14717/Kernel/Interrupts/GenericInterruptHandler.cpp#L57-L64

IRQHandler::change_irq_number is only used in one place right now:
https://github.com/SerenityOS/serenity/blob/07d4b41bac1330804ad2bb4cd7656e5c8ca14717/Kernel/Devices/SB16.cpp#L166-L173

This issue never came up because SB16::set_irq_line is seemingly never called.
Also, since this uses change_irq_number, it has an extra interrupt disabler.
Plus, the only place where GenericInterruptHandler::change_interrupt_number is seemingly called right now is IRQHandler::change_irq_number.

**Comment by supercomputer7** [comment]
Although `SB16::set_irq_line()` is never called, we can still use it later in event of IRQ sharing balancing so it's useful.
About the bug - you're right, it should be `ASSERT_INTERRUPTS_DISABLED`. Don't remember why, but I was mistaken when I used `ASSERT_INTERRUPTS_ENABLED` here. 
The idea is that `GenericInterruptHandler::change_interrupt_number` doesn't need to bother with how to disable interrupts, it just need to know that they're disabled, hence I put the assertion in the start of the method.
Also, the double usage of `InterruptDisabler` is quite reasonable here - the IRQ Handler ensures that interrupts are disabled because it's certainly not a good idea to leave this for upper levels of the kernel code (if someone forgets about that, think what will happen). Then, the SB16 driver needs to set the IRQ register in the card with the correct bitmask, therefore it has to disable interrupts, otherwise - an interrupt could be fired from the new IRQ line, but no IRQ handler is set to handle it, which could be, a severe crash for the system when it happens.
Will work on a fix now, thank you for this bug report!
