### ISSUE TITLE
Browser: Disallow local URLs in XMLHttpRequest

### ISSUE THREAD

**Issue by xTibor** [SerenityOS/serenity#3632]
I hope I'm not as controversial with this one as the port blacklisting one.

**Reproduction:**
```
<!DOCTYPE html>
<html>
<head>
<script>
function reqListener () {
    document.getElementById("logs").innerText = this.responseText;
}

var oReq = new XMLHttpRequest();
oReq.addEventListener("load", reqListener);
oReq.open("GET", "file:///etc/passwd");
oReq.send();
</script>
</head>
<body>
    <pre id="logs"></pre>
</body>
</html>
```

![Screenshot_20200928_171902](https://user-images.githubusercontent.com/1627292/94451693-0170b400-01af-11eb-8abf-d6e476ea62b3.png)

**Comment by bcoles** [comment]
Dupe of #1615. Related #1616

**Comment by xTibor** [comment]
Does making requests for local files from `file:/` URLs considered same origin? If so, there's a slight difference between #1615 and this.

**Comment by bcoles** [comment]
> 
> 
> Does making requests for local files from `file:/` URLs considered same origin? If so, there's a slight difference between #1615 and this.

In the context of SOP, an origin is defined as a combination of URI scheme, host name, and port number. The URL scheme is part of the origin, although `file://` is special.

> If so, there's a slight difference between #1615 and this.

The same issue related to file theft is described in https://github.com/SerenityOS/serenity/issues/1615#issuecomment-610782263

**Comment by xTibor** [comment]
I looked further into this. `file://` is not a special case, it's undefined behavior according to the specs (by not having meaningful hostname/port). Closing this in favor however you want to handle this is #1615.

**Comment by bcoles** [comment]
> 
> 
> > Does making requests for local files from `file:/` URLs considered same origin? If so, there's a slight difference between #1615 and this.
> 
> In the context of SOP, an origin is defined as a combination of URI scheme, host name, and port number. The URL scheme is part of the origin, although `file://` is special.
> 
> > If so, there's a slight difference between #1615 and this.
> 
> The same issue related to file theft is described in [#1615 (comment)](https://github.com/SerenityOS/serenity/issues/1615#issuecomment-610782263)

None the less, URLs with schemes such as `file:` and `data:` are special.

There's value in tracking this in a separate issue to #1615, although any implemented mitigation should be performed with the SOP model in mind as part of the SOP implementation, rather than an ad-hoc patch.

I believe the approach taken by all modern web browsers is to disallow URLs with a `file://*` origin from accessing any other `file://` URL. That is, the SOP model should permit `file:///home/anon/test.html` to access `file:///home/anon/test.html` but no other `file://` URLs.

Likewise, no URL should ever be able to access a `file://` URL unless it is also a `file://` URL.

**Comment by bcoles** [comment]
> 
> 
> I looked further into this. `file://` is not a special case, it's undefined behavior according to the specs (by not having meaningful hostname/port). Closing this in favor however you want to handle this is #1615.

undefined behavior = special case
