### ISSUE TITLE
LibGUI: TableViews scroll to the wrong place when trying to bring newly selected index into view

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#3825]
not-particularly-annoying repro:
- Open `FileManager` and select a file/directory that's partially hidden
- See the view scroll

very-annoying repro:
- Open Spreadsheet and click on `J0` (which is partially off the window)
- See the view scroll _a lot_
- Try the same with `H0` (which is completely visible)
- See the view scroll anyway

**Comment by tomuta** [comment]
I added some log statements to `ScrollableWidget::scroll_into_view` and it looks like `visible_content_rect == [0,0 568x358]`, but `rect == [40,0 960x18]` which seems to be the entire row rather than just the cell.

I'm not sure what you're seeing in `FileManager`, it seemed to work as expected for the cases I tried. Screen recording maybe?

**Comment by alimpfard** [comment]
It seems I was a bit too late in noticing the notification :P

re FileManager: I suppose I just linked the two unrelated behaviours together because I thought it was an `AbstractView` thing.
although the scroll kinda feels weird when clicking on an item, but that's probably just me not being used to the GUI ways lol
