### ISSUE TITLE
Breakout: Some odd ball behavior

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#4015]
I know it's not perfect yet, so I captured a few odd moments ;-) At the end looks like I got into some infinite setup.

![breakout_pad_edge](https://user-images.githubusercontent.com/10320822/98604362-c16a1a00-22a0-11eb-9aec-860cc9e52a1b.gif)

**Comment by bcoles** [comment]
There's issues with the bat+ball clipping. It is possible to have the ball disappear into the bat, then when you move the bat sideways you can cause the ball to be spat back out with upwards direction. If you don't move the bat, the ball will roll out the side and cause game over.

> At the end looks like I got into some infinite setup.

Due to the initial starting trajectory of the ball it possible to almost soft lock the game. Once all bricks in the top left corner are cleared, if a game reset occurs, the ball will be initialized with a position and trajectory that forces the player into the right corner. It is possible, but not easy, to break out of the soft lock by exploiting clipping issues with the bat.

This can be resolved by randomizing the initial starting trajectory of the ball upon each board reset. Making the game board more rectangularish may also help.

**Comment by alimpfard** [comment]
Am I the only one who thought the paddle's movement speed affects the ball's trajectory?

**Comment by linusg** [comment]
> Am I the only one who thought the paddle's movement speed affects the ball's trajectory?

No.

**Comment by bcoles** [comment]
Resetting the paddle was fixed in 844c2e1f3b7efddd427f055fa9dd1cd543aa0741
Paddle collision+velocity physics updated in 959038d410ea0fbc9c592f6cb7a5dce763768c39

**Comment by linusg** [comment]
@awesomekling @tomuta seems like this issue can bee closed :)

**Comment by tomuta** [comment]
Probably, although I think there still is some odd behavior how the ball bounces back from the paddle. Either the paddle should be drawn rounded appropriately, or it doesn't feel "natural". But it's not consistent, sometimes it seems like it bounces off as I would expect, other times it bounces in same direction where it came from, despite the fact that arrived at a ~45 angle. Maybe I can capture a video of such a moment. Maybe it's working as designed, but I find it a little confusing. But again, doesn't seem to happen consistently.

**Comment by bcoles** [comment]
Most of the egregious ball behavior has been resolved, although there are still some issues.

I've created #4422 to randomize the initial ball trajectory and velocity.

**Comment by damienfir** [comment]
I have fixed some collision problem between the bat and the ball in #9938. The ball shouldn't get stuck in the bat anymore.
There is more to improve, but it depends how realistic we want this game's physics to be.

**Comment by AtkinsSJ** [comment]
Breakout is gone. Closing.
