### ISSUE TITLE
QEMU: '-soundhw pcspk' is deprecated, please set a backend using '-machine pcspk-audiodev=<name>' instead

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#4093]
Not sure how urgent this is or when/if this will be removed from QEMU, but I noticed this warning when starting Serenity (via `ninja run`):

```
qemu-system-i386: warning: '-soundhw pcspk' is deprecated, please set a backend using '-machine pcspk-audiodev=<name>' instead
```

```
$ qemu-system-i386 --version 
QEMU emulator version 5.1.0 (qemu-5.1.0-5.fc33)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
```

**Comment by tomuta** [comment]
Doesn't sound like support for it will be removed, it seems like they merely [changed how it needs to be specified](https://www.qemu.org/docs/master/system/deprecated.html#creating-sound-card-devices-using-soundhw-since-5-1) on the command line.

**Comment by auronandace** [comment]
This seems to affect Piano. When set to '-soundhw pcspk' in Meta/run.sh Piano produces static and always consumes 100% cpu. But if I set it to '-audiodev id=pa,driver=pa' then Piano produces sound as intended and no longer consumes 100% cpu. This is when using QEMU 5.2.0.

**Comment by auronandace** [comment]
Just wanted to update this issue:

The cpu now only tops out at ~70% when Piano is open. I think the improvement might be because of the recent merge with noise changes in #6535 so the performance has improved.

The situation remains the same though. With `-soundhw pcspk` in Meta/run.sh Piano still is at high cpu and the notes are still static rather than the sound they should be.

If I replace `-soundhw pcspk` with `audiodev id=pa,driver=pa` (since I'm using pulseaudio in linux) in Meta/run.sh then Piano works as intended. Low cpu usage and proper sounding notes.

**Comment by auronandace** [comment]
Just wanted to update this issue:

Now that Meta/run.sh uses the following 2 lines:

`-machine pcspk-audiodev=snd0`
`-device sb16,audiodev=snd0`

Piano functions properly. Normal CPU usage and the sound is as intended.

**Comment by linusg** [comment]
Regressed in c73c40a, getting this warning again (QEMU 5.2.0). cc @gunnarbeutner
