### ISSUE TITLE
Spreadsheet: CSV support

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#4136]
The spreadsheet currently only handles its own json format but it would be handy to be able to export and import DOS and UNIX formatted csv files.

**Comment by alimpfard** [comment]
Hmm...I guess we __are__ at a place where we can think about supporting other formats.
CSV (and whatever-separated-values in general) is an interesting format, since the reader has to guess the type/kind of data it's reading - to what extent do we want to do this? knowing that Excel overdid the whole guess-the-data-type thing and that whole gene name fiasco happened...

**Comment by asynts** [comment]
Maybe it would be better to only use it for import/export. Everything could be imported as text unless explicitly changed by the user later.

**Comment by alimpfard** [comment]
Well...no guessing is certainly a valid option; one which I like.
