### ISSUE TITLE
GFilePicker should allow double click to select

### ISSUE THREAD

**Issue by rburchell** [SerenityOS/serenity#43]
I guess this might mean another concept rather than just activation. Perhaps selection (single click, arrows) vs activation (double click/enter key)? Either way, it would make it much nicer to use.

**Comment by danboid** [comment]
Double clicking on a file in GFP does what I expect it to currently, replace the existing file name with the double clicked one.

Can this be closed @rburchell ?

**Comment by danboid** [comment]
I agree that double-clicking on a file in a GFP 'Load File' window or left  clicking and then hitting ENTER should open the without making you click 'Open' too. 

In the case of 'Save As' I'd prefer it as-is where it just replaces the current file name only rather than trying to save to the double-clicked file name; at which point it should ask for confirmation to overwrite the file but I suppose instantly trying to save to the file on double click would be more consistent with the desired open behaviour.

What do you think @rhin123 and @awesomekling ?

**Comment by awesomekling** [comment]
Yeah, those seem like good behaviors @danboid, we should implement them :)

**Comment by danboid** [comment]
I think this can be closed now.

**Comment by awesomekling** [comment]
Dandy!
