### ISSUE TITLE
Kernel: Cannot send signal to self

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#4336]
Consider the following program:

send-signal-to-self.cpp
```c++

#include <signal.h>
#include <stdio.h>
#include <unistd.h>

volatile sig_atomic_t saved_signal = -1;
volatile bool got_signal = false;

static void my_handler(int sig)
{
    saved_signal = sig;
    got_signal = true;
}

int main()
{
    if (SIG_ERR == signal(SIGUSR1, my_handler)) {
        perror("signal");
        return 1;
    }

    sleep(1);

    if (0 != kill(getpid(), SIGUSR1)) {
        perror("kill");
        return 2;
    }

    sleep(1);

    if (!got_signal) {
        fprintf(stderr, "Where's my signal, bro?\n");
        return 3;
    }

    printf("Got signal %d\n", saved_signal);

    return 0;
}
```

In serenity, this prints "Where's my signal, bro?"
![signal-to-self](https://user-images.githubusercontent.com/8388494/101268667-2b9ca000-3723-11eb-88a4-ede868ee182f.png)

On Ubuntu 20.04, it prints, "Got signal 10".
```
andrew@DESKTOP-QQ5PM6D:~/testing$ g++ send-signal-to-self.cpp -o send-signal-to-self
andrew@DESKTOP-QQ5PM6D:~/testing$ ./send-signal-to-self 
Got signal 10
andrew@DESKTOP-QQ5PM6D:~/testing$ 
```

**Comment by ADKaster** [comment]
cc @tomuta  perhaps? Not sure who's touched signal handling recently.

**Comment by tomuta** [comment]
I'll take a look this weekend I hope. Thanks for the sample code :)

**Comment by DrewStratford** [comment]
Looks like this is happening because `dispatch_one_pending_signal` is only being called during `Scheduler::context_switch`; the thread probably won't cause a context_switch, so the signal won't be dispatched.

We could solve this by moving signal dispatching to the end of the interrupt handler, just before we re-enter userspace. This would have the added benefit of removing the need for `send_urgent_signal_to_self`, which was always a bit hackish.
