### ISSUE TITLE
Feature request: AK: Convert string to long long

### ISSUE THREAD

**Issue by ccapitalK** [SerenityOS/serenity#4377]
It would be nice for there to be an equivalent of `String::to_int()` for 64 bit types.

**Comment by asynts** [comment]
There are several (backend) implementations of this in the code base:

https://github.com/SerenityOS/serenity/blob/a2879f53c80b5b20b8cafd76176447ee0ca8f959/AK/PrintfImplementation.h#L142-L181
https://github.com/SerenityOS/serenity/blob/a2879f53c80b5b20b8cafd76176447ee0ca8f959/AK/Format.h#L137-L158

I think these implementations should be joined (especially the `print_hex` should go.)

Back when I did the format stuff I skipped over this because I wasn't sure how to approach this. These methods have to be callable very early during boot process (`dbgln` uses it) and thus `StringBuilder` with heap allocations can't be used.

Personally, I would prefer an implementation that more resembles the format stuff but more generic. However, I am conflicted about whether the builder class should be a template parameter or if it's sufficient to put a inline buffer into `StringBuilder`?

**Comment by alimpfard** [comment]
fwiw, `StringBuilder` does have an inline buffer - I believe 128 bytes?

**Comment by ccapitalK** [comment]
Ah, I was talking more about going from String -> int64_t, not int64_t -> String. `AK::String::to_int()` does this for 32-bit types, but it doesn't for 64-bit integers which makes parsing 64-bit integers a bit more cumbersome than it should be. I do agree that there may be value in unifying formatting/parsing methods a bit more.
