### ISSUE TITLE
Chess: pieces are overly big

### ISSUE THREAD

**Issue by tomuta** [SerenityOS/serenity#4385]
This seems like it changed recently, but to me it doesn't look as nice anymore. It feels like the chess pieces are too big. It seems like they previously had some margin.

![Screenshot from 2020-12-11 11-23-19](https://user-images.githubusercontent.com/10320822/101940333-9296da80-3ba3-11eb-86b1-5f1b2e3250dd.png)

**Comment by linusg** [comment]
I believe it looked like that since the very beginning (https://github.com/SerenityOS/serenity/pull/3099). The pieces only have margin if it's included in the images itself - you might have seen the `test` piece set where that's the case to some extend.

**Comment by tomuta** [comment]
I guess you're right, I seem to have been accustomed to this set (went back some 1000 commits or so to 6331d45a6f0a111b483a5c4b84cc24926bc9205d):
![Screenshot from 2020-12-11 22-07-16](https://user-images.githubusercontent.com/10320822/101975891-4b3d3800-3bfd-11eb-8aea-2f186fc0cde2.png)

Which, to me, looks better because it has a margin around the pieces.

**Comment by AnicJov** [comment]
I agree that the pieces are too big. How about we just have a set with scaled down pieces, and have that as a default? Like so:
![image](https://user-images.githubusercontent.com/25593018/102443366-d9af2080-4026-11eb-97f9-47fed3e82c94.png)

What do you think?

**Comment by tomuta** [comment]
> I agree that the pieces are too big. How about we just have a set with scaled down pieces, and have that as a default? Like so:
> 
> ![image](https://user-images.githubusercontent.com/25593018/102443366-d9af2080-4026-11eb-97f9-47fed3e82c94.png)
> 
> What do you think?

So beautiful!!!

**Comment by linusg** [comment]
I also had a look at fixing this - I think we basically have these options:

1. Keep the current tile size, keep the current piece images and just scale them down to add a margin
   - Pro: Minimal effort required
   - Con: Looks a bit disappointing due to how LibGfx scales images currently
2. Keep the current tile size, scale down all piece images using software that will produce higher quality results.
   - Pro: Looks great (with the default size, resizing the window/widget already suffers from the scaling quality issue mentioned in 1)
   - Con: Higher effort required
3. Increase the current tile size (e.g. by 10/10 for 5px margin), keep the current piece images, add margin and therefore increase the default board size.
   - Pro: Minimal effort required
   - Con: Board will be noticeably larger by default

Which one sounds best?

---

Screenshot of options 1 and 3, with a 5px margin on all sides of each tile:

![image](https://user-images.githubusercontent.com/19366641/102554635-162d5b80-40bd-11eb-926d-7147ae70c3de.png)

![image](https://user-images.githubusercontent.com/19366641/102554508-e716ea00-40bc-11eb-9eb8-b5c6f2adcdbe.png)

**Comment by AnicJov** [comment]
> ![image](https://user-images.githubusercontent.com/25593018/102443366-d9af2080-4026-11eb-97f9-47fed3e82c94.png)
I did this with method 2 that you described. I think it works best for the time being, at least until we get some better scaling options for images.
If no one has any complaints about the change I'll replace the stelar7 set pieces with the ones with margins and I'll create a PR once I get to my pc.
I'll keep the old images locally so we can use those once we have the better scaling. (And I might look into that once I get some down time)

**Comment by tomuta** [comment]
I know @awesomekling doesn't really like vector graphics (yet), but it would be really nice if we kept original images in some editable format other than pixel-based bitmaps. Just recently I had to mock with cursors and the lack of original editable artwork was not exactly ideal...

**Comment by BenWiederhake** [comment]
:+1: Option 3

**Comment by LucasChollet** [comment]
Looks resolved to me!
![Chess](https://github.com/SerenityOS/serenity/assets/26030965/cef131be-96a9-4692-af7a-c9b2965e373e)
