### ISSUE TITLE
How long did it take you to create this?

### ISSUE THREAD

**Issue by gerald-dotcom** [SerenityOS/serenity#4447]

**Comment by awesomekling** [comment]
Hello there! This is a bug tracker, not a discussion forum :)

You can find the discussion forum under https://github.com/SerenityOS/serenity/discussions although for shorter or more informal questions, the IRC channel usually works better.

To answer your question since we're already here, the first commit in this repository was on October 10th, 2018, so a bit over 2 years so far. You can read more about the history of the project in the [1st](http://serenityos.org/happy/1st/) and [2nd](http://serenityos.org/happy/2nd/) birthday celebration posts!
