### ISSUE TITLE
iso release

### ISSUE THREAD

**Issue by dodobyte** [SerenityOS/serenity#448]
why no iso release?

**Comment by awesomekling** [comment]
Because this system is nowhere near release-ready.
There is no installer and very little hardware support.
Also we don't support the ISO9660 filesystem, so we couldn't read the filesystem if we were inside an ISO :)

We'll get there eventually though, but for now, you'll have to build Serenity manually if you want to try it out in QEMU.

**Comment by dodobyte** [comment]
how about an image, surely if xv6 can do it, you can do it too.

**Comment by awesomekling** [comment]
Of course I could, but it's not something that benefits me in any way, so I'm not going spend time on it.

**Comment by TheodorWORKFLOW** [comment]
Hello ! One tutorial link to install in qemu ?

**Comment by botchGNU** [comment]
now that 2 years have passed, maybe reconsider an iso release?

**Comment by denisgolius** [comment]
> a-bit-longer-than-2 year aniversary of there not being an iso reoleasetadatadatada

`A samurai has no goal, only path, and samurai’s path is death`
