### ISSUE TITLE
Userland: useradd / userdel do not use /etc/shadow

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#4884]
`useradd` and `userdel` utilities were not updated to use `/etc/shadow`. #3993

As such:

* `useradd` continues to write password hashes to the `/etc/passwd` file rather than `/etc/shadow`
* `userdel` does not remove users and their associated password hashes from `/etc/shadow`

![image](https://user-images.githubusercontent.com/434827/104124597-c8e39780-53a5-11eb-8072-e4ce15750d20.png)

**Comment by bblenard** [comment]
I started poking at this a bit and had `useradd` working but while implementing this in `userdel` I was wondering to myself `Core::Account` should be responsible for managing entries in `/etc/passwd` and `/etc/shadow`. That way member functions like `add()` or `delete()` could carry out the actual modification of those files instead of having each utility parse and modify them on their own.

I'm not sure if it is good design to do that though so I would like input. Along that same vein I was wondering what the point of having `Core::Account::Account` a private member was

*disclaimer* I am not good at c++ so if I'm plain wrong on what I'm talking about let me know :)
