### ISSUE TITLE
Opening too many programs causes the entire operating system to crash

### ISSUE THREAD

**Issue by xeons** [SerenityOS/serenity#498]
Problem: Opening too many programs causes the operating system to completely lock up and crash due to running out of memory.

Steps to reproduce Open 4+ copies of the chan viewer program.

Expected behavior: Operating system itself should have some reserved memory or something that can't be exhausted by programs in userland. Possibly implement some threshold that will prevent any new programs from being launched when memory is almost exhausted. Is there currently any type of paging file or virtual memory system in place?

```
NetworkTask(4) kmalloc(): PANIC! Out of memory (sucks, dude)
sum_free=0, real_size=28

```

**Comment by bugaevc** [comment]
I was thinking we should maybe unwind the stack and return `ENOMEM` from the current syscall when we OOM. That, or OOM-kill the current process (we still need to unwind the stack to drop all the guards).

**Comment by awesomekling** [comment]
IMO we should move whatever takes up all the kmalloc memory to some other kind of allocation instead.

Then instead of unwinding kernel stacks, it would be better to allow kmalloc to grow dynamically on demand.

ENOMEM for small allocations is goofy and unhelpful. Let’s not die from a thousand paper cuts :)

**Comment by bugaevc** [comment]
Speaking of which, why doesn't kmalloc dynamically grow now, and use the same mechanism, taking and releasing pages, as `KBuffer`?

**Comment by bugaevc** [comment]
> IMO we should move whatever takes up all the kmalloc memory to some other kind of allocation instead.

If only there was some tooling to inspect and profile kmalloc allocations! But my impression was, other than buffers and JSON stuff that's now dealt with, kmalloc heap is taken up by many small housekeeping allocations that you cannot just get rid of. If kmalloc could grow dynamically, this wouldn't be a problem; but otherwise it's yeah, death from a thousand paper cuts.

> ENOMEM for small allocations is goofy and unhelpful.

I'm not saying it's good, but we're kind of living on borrowed time already; the heap is almost full right after launching. You open a few ChanViewers and *of course* it's going to OOM. And it's better to kick one process than halt the whole system. Again this wouldn't be a problem if kmalloc heap could grow dynamically, why doesn't it?

**Comment by awesomekling** [comment]
The kmalloc heap doesn’t grow dynamically because nobody implemented it yet :)

The (crappy) block cache in DiskBackedFS eats up a lot of kmalloc memory. We should definitely build a better disk cache. Region accounting is not cheap though so it’s not a matter of just switching to KBuffer since that will kill performance. (gcc helloworld.c) is a great test case for this.

**Comment by awesomekling** [comment]
This should be a lot better now, but it's still possible to run out of memory.

**Comment by awesomekling** [comment]
This keeps improving over time. I can now easily run 20 copies of the `ChanViewer` program.
Gonna close this bug and we can open new ones as we run into new versions of the problem :)
