### ISSUE TITLE
Run...->Browse... crashes Run with "has not pledged thread"

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#5015]
Subject says it all.

Maybe just needs to pledge thread :)

@nvella

**Comment by nvella** [comment]
Interesting... this must be due to a very recent change 😄 I'll get onto it this evening 👍

**Comment by nvella** [comment]
Having troubles trying to reproduce this one on master (as of 98637bd54.) "Browse" button opens file picker and sets address box contents as expected, although it does fail to redraw the textbox occasionally.

**Comment by linusg** [comment]
@nvella This happens when viewing a directory with an image that doesn't have a cached thumbnail yet, which causes the start of a new thumbnail creation thread. Otherwise it's not starting that thread and works fine. The solution is indeed just pledging `thread`, at least until #1057 is implemented. See #1454 and #4121.

**Comment by nvella** [comment]
Ah, got it! 👍 Will get a PR in tonight, and probably fix the text box update glitch whilst I'm at it 😃
