### ISSUE TITLE
Windows can no longer be moved higher than top of screen

### ISSUE THREAD

**Issue by nico** [SerenityOS/serenity#5105]
I used to very frequently move windows slightly off screen by super-dragging them up. It looks like it's now impossible to move a window higher than a y pos of 0. However, the window title bar still moves behind the system menu bar.

If the motivation is to prevent users from accidentally getting windows into a state where they can no longer move them back, they shouldn't be allowed behind the menu bar.

If the motivation is to make it impossible for windows to move completely off screen, they should be allowed to go higher than currently, just not completely off screen.

Maybe moving by super-drag should allow the larger range (since someone who knows that shortcut can get windows back as long as any pixels of a window are still draggable)?

This regression makes working on hidpi harder.

@BenWiederhake

**Comment by BenWiederhake** [comment]
I forgot about super-dragging in Serenity, because that key is already assigned in my window manager to, uh, drag windows. I'll test around with super-drags this time around ^^

> the window title bar still moves behind the system menu bar.

The intention was to show "look, the window titlebar is slightly disappearing, you would get in trouble if I wouldn't stop you here", and stop the movement when the titlebar is just partially obscured but still grabbable.

> If the motivation is to prevent users from accidentally getting windows into a state where they can no longer move them back, they shouldn't be allowed behind the menu bar.

Does the titlebar vanish completely behind the menu bar? Weird, I tested precisely this, can you tell me the steps to reproduce this?

> Maybe moving by super-drag should allow the larger range (since someone who knows that shortcut can get windows back as long as any pixels of a window are still draggable)?

Sounds like a good idea! I'm afraid it'll take several days until I can do that.

> This regression makes working on hidpi harder.

I'm very sorry to hear that :/

Out of curiosity: What's the usecase of pushing a window through the top edge? And why does this interfere with work on hidpi?

**Comment by nico** [comment]
> Does the titlebar vanish completely behind the menu bar? Weird, I tested precisely this, can you tell me the steps to reproduce this?

It does. Repro: Super-drag window as high as you can. It goes up to y=0, where the window's title bar is completely hidden.

> Out of curiosity: What's the usecase of pushing a window through the top edge? And why does this interfere with work on hidpi?

I do most testing in 640x480 (`chres 640 480 2`) and many windows don't completely fit the screen in that resolution, So I push them off the screen to the top to see their bottom bits. (Most of the time, `LibGfxScaleDemo`.)

**Comment by BenWiederhake** [comment]
That makes sense. As a quick workaround, You could change `Window::normalize_rect()` to be a no-op. That of course enables all the issues again that I sought to fix, but in the meantime you can push the windows around again. I hope I'm fast enough that you don't need to push this workaround to master.
