### ISSUE TITLE
LibGUI: About dialog no longer shows small window title icon

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#5177]
The `About` dialog no longer shows small window title icon for some applications (but still works for some applications such as `Browser` and `Terminal`.

![image](https://user-images.githubusercontent.com/434827/106355237-cb089880-634a-11eb-93ca-68e8c3035b3c.png)

![image](https://user-images.githubusercontent.com/434827/106355264-ebd0ee00-634a-11eb-9425-4d9cda6f1db2.png)

**Comment by linusg** [comment]
Some fixed in #5179, three remaining ones with this issue: HackStudio, HexEditor, TextEditor. They all use the pattern where a widget for the whole window is constructed, like this:

https://github.com/SerenityOS/serenity/blob/cc8b3c92ba1c7ee3581fa2f13ade696766dd7215/Userland/Applications/TextEditor/main.cpp#L58-L61

And then use `window()` for the about dialog:

https://github.com/SerenityOS/serenity/blob/aa8cb35b90899b0f7badd53b89d8bbda2d2b2cae/Userland/Applications/TextEditor/TextEditorWidget.cpp#L494

...which is `nullptr` at that time, as the widget is first constructed and then added to the window:

https://github.com/SerenityOS/serenity/blob/6dc2c38fd0457ee59f3080199c34abcce043d8b8/Userland/Libraries/LibGUI/Window.h#L135-L141
