### ISSUE TITLE
Kernel: Memory checks for syscall arguments happen way too late

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#5198]
Let's look at `sys$stat`: It calls `Process::get_syscall_path_argument`, which calls `copy_string_from_user` (not a `Process` method!), which assumes that the pointer has already been validated, and can be crashed easily due to `ASSERT(is_user)`.

Let's look at any other syscall which takes a `Syscall::SC_*_params`: It calls `copy_from_user(&params, user_params)` (not a `Process` method!), which can again be crashed easily due to `ASSERT(is_user)`.

As a proof of concept, I wrote #5197.

In order to validate a pointer, we need to know that the memory is actually mapped by the calling process, so I'm not sure how this is even able to work under normal circumstances.

Here's a rough guess:
- Even though we left Userspace, the TLB still contains mappings for the userspace program, and *only* the userspace program.
- Thus, all accesses are automatically validated by the TLB; no need for the Kernel to implement anything.
- … except the check that the pointers are actually in the user range.
- Therefore, the fix is to return `false` in `copy_{from,to}_user`, and let the the respective caller return `EFAULT`.
- Also, let `copy_string_from_user` to return a null string.

**Comment by tomuta** [comment]
The `copy_from/to_user` functions should *not* be part of `Process`. Take a look at that `ASSERT(is_user)`:
https://github.com/SerenityOS/serenity/blob/da7b21dc06d733c30eb9912b9b64e82b02f31671/Kernel/StdLib.cpp#L39
We can just remove this assert. I left it in there initially to.... catch bugs, but I think our stuff has matured enough by now that we can simply remove it.

Yes, the TLB contains the mappings of the userspace program. Including the kernel. When CR3 is updated, only the userspace portion gets flushed because the kernel pages are marked as global.
The Kernel actually *must* implement these functions (btw, Linux has them, too). We leverage the MMU for access violations, e.g. pages that aren't mapped or where permissions are violaged (e.g. writing to a read-only page). These will trigger page faults just like in user mode, and page faults triggered from ring 0 result in a kernel panic (unless it's a fault that is permitted, such as zero/inode/ etc fault or a fault triggered by `copy_from/to_user`).

**Comment by tomuta** [comment]
Bottom line, aside from the `copy_from-user` returning a null string if the pointer is `nullptr` I believe those APIs are implemented as intended. Removing the `ASSERT(is_user)` should fix those crashes (though I haven't tried).

**Comment by tomuta** [comment]
I am hesitent changing `copy_string_from_user` to do that because all code is already expected to check for `Optional<String>::has_value` and I feel like it would be rather risky expecting every caller to also check for a null string. I am open to changing it to return a 0-length string in that case.

**Comment by BenWiederhake** [comment]
Which code are you looking at? I only see `String copy_string_from_user(const char* user_str, size_t user_str_size)`, without `Optional`.

**Comment by tomuta** [comment]
Oh yeah you're right. I originally had it as an `Optional<String>` but @awesomekling educated me that the `String` itself has the concept of a null-string already. So I changed it to return a null-string when it fails instead.

**Comment by tomuta** [comment]
I'm open to add a 
```c++
if (!user_str)
    return {};
```
to the beginning of `copy_string_from_user` but I feel like no code in libc/etc should do that, and then we'd have to once again turn it into an `Optional<String>` or `KResultOr<String>` because then there'd be no way to distinguish between an `EFAULT` and a `nullptr` being passed in.

**Comment by tomuta** [comment]
We _could_ make it return a `bool` as you stated, but I kind of like as it is right now. Or do we have legitimate use cases of `nullptr` strings?

**Comment by tomuta** [comment]
Nothing stops you from doing something like:
```c++
String str = copy_string_from_user(userspace_ptr, ...);
if (str.is_null() && userspace_ptr != nullptr)
    return EFAULT;
```
in the rare case where a user space pointer is allowed to be `nullptr`

**Comment by tomuta** [comment]
I updated my first comment to hopefully explain a little better of how this mechanism works.

**Comment by BenWiederhake** [comment]
I looked at all the places that call `copy_string_from_user`, and indeed: There is no legitimate user of `nullptr`, and all of them do `if (str.is_null()) return EFAULT;`.

I'll remove the asserts accordingly, and also extend the syscall fuzzer to see what happens :)
