### ISSUE TITLE
Meta: File filters set by lint-clang-format are ignored when run as part of precommit hook

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#5252]
E.g. the file `Kernel/Arch/i386/CPU.cpp` is not ignored as it ought to be, and it is formatted as a side-effect.
I dunno why this was being filtered out from the clang-format lint, but the lint filter doesn't apply to the precommit hook.

The file itself will be dealt with if the patch in #4986 is merged.

(probably) cc @linusg and @BenWiederhake

_Originally posted by @alimpfard in https://github.com/SerenityOS/serenity/pull/4986#discussion_r571618498_

**Comment by BenWiederhake** [comment]
A short history:
- I wrote the initial version of the linter, which ran on *all* files. I excluded `CPU.cpp` because back then, clang-format produced a lot of weirdly-formatted assembly. Even when it wasn't wrong, the diff would have become unreasonably large.
- Someone (linusg?) changed the linter to accept the set of files from `argv` – and overlooked the sleight of hand trick I did to avoid reformatting `CPU.cpp`
- Then you ran into the exact issue that triggers this weirdness.

I'm not sure how to do this. I see at least these options:
- `grep -Fv CPU.cpp` on the given files or something? Sounds brittle and overly convoluted.
- Wrap `CPU.cpp` in a giant `// clang-format: off`
- Sprinkle `CPU.cpp` with a few well-placed `// clang-format: off`s
- Sprinkle `CPU.cpp` with very few `// clang-format: off`s and reformat the rest

**Comment by linusg** [comment]
> Someone (linusg?) changed the linter to accept the set of files from argv

yes...

> and overlooked the sleight of hand trick I did to avoid reformatting CPU.cpp

yes! :smile: 

> Sprinkle CPU.cpp with a few well-placed // clang-format: offs
> Sprinkle CPU.cpp with very few // clang-format: offs and reformat the rest

Personally I'd prefer either of those options, but the people actually working on this file on a regular basis should have the final say :)

**Comment by awesomekling** [comment]
Slap it with the `// clang-format: off` stick IMO

**Comment by alimpfard** [comment]
Then my changes to CPU.cpp in #4986 are fine, I suppose 
The other files aren't touched in that PR, so I'll avoid messing with them, I think

**Comment by IdanHo** [comment]
This is fixed already
