### ISSUE TITLE
Kernel: load-invalid-value on bool in sys$stat

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#5316]
Found with fuzz-syscalls.

Trace:
```
fuzz-syscalls(34): #8205: Calling stat(0x4c6f9000, 0xbffff000, 0x00000000) with 0x4c6f9000 containing [0x4c6f9000, 0x0000000d, 0x7b4c998b, 0x0000000d, 0xbffff000, 0x4c6f9000, 0xc0000000, 0xc0000000, 0x4c6f9000]
[#0 H(34:34)]: KUBSAN: load-invalid-value: 'bool' (8-bit)
[#0 H(34:34)]: KUBSAN: at ../Kernel/Syscalls/stat.cpp, line 56, column: 99
[#0 H(34:34)]: 0xc022302a  print_location +0xfe
[#0 H(34:34)]: 0xc02008cb  Kernel::Process::sys$stat(AK::Userspace<Kernel::Syscall::SC_stat_params const*>) +0x1b7
[#0 H(34:34)]: 0xc01ccda8  syscall_handler +0xa87
[#0 H(34:34)]: 0xc01cc2e9  syscall_asm_entry +0x31
```

**Comment by tomuta** [comment]
Hm... I don't see anything wrong there?

**Comment by BenWiederhake** [comment]
@tomuta: For `int`-like types, or in low-optimized code for bools, yes. However, the compiler might say "Well, it's already a `bool`!", and optimize the `!!` away. Hence this is a problem, because now the non-0-1-bool propagates further and further and might wreck havoc.

**Comment by tomuta** [comment]
@BenWiederhake Sure that makes sense. So the solution is to do `!!params.follow_symlinks` when the input can't be trusted,  correct?

**Comment by BenWiederhake** [comment]
I'm not sure what the solution is, otherwise there would already be a PR from me :P

But trying to do `!!` on a bool is already too late. I guess `Syscall.h` must define it as an `int`, and then `sys$whatever` just casts it to bool, and the compiler knows on its own that it needs to do some bitfiddling.

**Comment by tomuta** [comment]
Why would `!!` be too late? Whatever the value is, after `!!` it should be either `0` or `1`.

**Comment by tomuta** [comment]
Oh I see, it would be too late if kubsan wouldn't recognize this as a "sanitation" technique ;)

**Comment by bugaevc** [comment]
> I'm not sure what the solution is

Perhaps `!!*reinterpret_cast<u8*>(&params.follow_symlinks)` would do the trick?

**Comment by BenWiederhake** [comment]
Uhhh

Technically: "Maybe, as long as the compiler does *not* understand what's going on, so possibly it requires a cast to `volatile u8*` instead of just `u8`, and we would have to keep an eye on what the compiler is actually doing with this code".

Practically: "No, why would you prefer this abomination over code that explicitly says what's going on, i.e. user-supplied `int` being cast to `bool`" :P

**Comment by awesomekling** [comment]
How about we just don't use `bool` in `SC_foo` structs?

**Comment by tomuta** [comment]
Did anyone actually try if `!!params.follow_symlinks` makes it happy?

**Comment by BenWiederhake** [comment]
- This can be reproduced by `syscall -o stat [ "Desktop" 7 buf 2 ] | hexdump `.
- `!!params.follow_symlinks` doesn't change anything. Told you so :P
- Changing it to `int` works as expected.

I'm preparing a PR already. :)
