### ISSUE TITLE
Kernel: Move code into more subdirectories

### ISSUE THREAD

**Issue by Hendiadyoin1** [SerenityOS/serenity#5354]
When opening the Kernel folder, you pretty much get hit by a wall of files, many of wich on similar topics, and most of the time not the thing you are looking for.  

Like Thread alone has 5 files (Thread.h/cpp, ThreadBlocker.cpp, ThreadTracer.h/cpp) or *Buffers have all in all 9 files (2*DoubleBuffer, 3*KBuffer, 2*PerformanceEventBuffer, 2*UserOrKernelBuffer) and with the integration of  #5351 the sanitation library will grow to 4 files, which will be rarely sought after.

Therefore maybe moving these files each in their dedicated folder may increase navigatability of the code.

The problem, that would occur would be that that may break a lot of pullrequest, that have to be fixed individually

**Comment by tomuta** [comment]
If you volunteer to rebase #5184 for me...

**Comment by linusg** [comment]
> most of the time not the thing you are looking for.

Well, what *are* you looking for? :smile:

FWIW, [`Userland/Libraries/LibJS/Runtime`](https://github.com/SerenityOS/serenity/tree/master/Userland/Libraries/LibJS/Runtime) has 149 files in it (usually 6 per object - `Foo.{cpp,h}`, `FooConstructor.{cpp,h}` and `FooPrototype.{cpp,h}`) - that's more than twice as much as the number of files directly in `Kernel/` , but it's been working just fine :)

Since many editors provide search-like functionality for opening files anyway (as opposed to navigating the file tree manually), I don't think this is an actual problem in practice...
