### ISSUE TITLE
PixelPaint: cursor display issue after loading .pp file

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#5375]
Create a .pp file with PixelPaint, close PixelPaint and then open your .pp file. The Serenity cursor now has a black background instead of being transparent when the cursor is over the PP editing area.

**Comment by linusg** [comment]
![image](https://user-images.githubusercontent.com/19366641/108098904-3a3cf700-7084-11eb-8d00-9d4457f9175b.png)

**Comment by tomuta** [comment]
Probably the same issue as #5055. The LibGfx Demo also exhibits an alpha related problem, weird white line on the right to the cursor:

![Screenshot from 2021-02-16 15-07-02](https://user-images.githubusercontent.com/10320822/108127738-ecff5c00-7068-11eb-8338-dd95862663c0.png)

**Comment by tomuta** [comment]
Because window shadows exhibit the same problem as #5055 I'm pretty sure this is just a duplicate.

![Screenshot from 2021-02-16 15-10-13](https://user-images.githubusercontent.com/10320822/108127876-2637cc00-7069-11eb-8711-15d5e5e97c3b.png)

And if you set display scale to 200% the problem is gone.

**Comment by linusg** [comment]
Cool, that looks indeed identical - closing as duplicate.
