### ISSUE TITLE
CI: CCache output should be cached across test runs

### ISSUE THREAD

**Issue by IdanHo** [SerenityOS/serenity#5561]
Since pulls usually change just a small subset of serenity we could probably speed up CI quite a bit by caching the ccache folder across runs (using something similar to our toolchain caching) and only building the changed sources.

**Comment by BenWiederhake** [comment]
Dibs! :)

**Comment by alimpfard** [comment]
@BenWiederhake I've always wanted to do what I'm about to do.
Revert if you so wish lol

**Comment by bgianfo** [comment]
8n the past month I've had to clean out ccache on my local dev machine after pulling master to get a clean build. I'm worried about those same types of issues hitting the CI builds if we ccached across ci builds. Am I too paranoid?

**Comment by alimpfard** [comment]
@bgianfo I've also had to do that once (after a toolchain change), but it doesn't seem to have happened since.
Even so, we can probably nuke the cache on CI if the toolchain changes (or whatever other case it may be) - _if_ we see ccache being weird.

**Comment by IdanHo** [comment]
maybe we can just set some kind of expiry timeout for the cache? (so every x time the cache is discarded and the whole build is done from scratch) that way we can probably avoid that

**Comment by BenWiederhake** [comment]
That's not how this works.

Github Actions Caches dictate that caches are immutable. However, they provide a fall-back where a "usable starting point" for the cache can be used. Therefore, the only way to implement is like the "TODO" in `cmake.yml` suggests: Attempt to fetch the cache with a key that is always unique (e.g.. depends on the exact time and matrix), and fall back to the latest successful upload. Then it automatically uploads the cache with the new, unique key. GA automatically deletes the old caches, so we don't have to worry about that.

Therefore, `ccache` sees a continuous evolution of the `.ccache/` directory, and doesn't even suspect that fishy stuff (like running on a constantly-regenerating image) is going on.

However, it means that busting the ccache cache means that *all* ccache cache entries (what a term!) have to be cleaned. This can be fixed by having a tiny counter in the GA-cache key: Incrementing the key means the GA cache misses and does not find any acceptable cache, and starts from scratch.

So … yes, I have a good idea about how to approach that problem, and thanks for bringing it up – I totally forgot that ccache might not be 100% reliable :D
