### ISSUE TITLE
Run: gui apps don't get to command history until they are closed

### ISSUE THREAD

**Issue by diversys** [SerenityOS/serenity#5587]
https://youtu.be/M81Hy5UP2nA?t=631

**Comment by nvella** [comment]
I saw this in the monthly update 😃 This is because inputs that aren't an absolute path or URI are sent to `RunWindow::run_as_command`, which only appends the command to history once it gets back a `0` exit code from the shell, preventing us from appending invalid commands to the history. The simple fix would be to append the command to history, regardless of the exit code of the shell.
