### ISSUE TITLE
ls: Prints extra spaces after filename when piping output

### ISSUE THREAD

**Issue by alimpfard** [SerenityOS/serenity#5671]
To see the spaces, try `ls | xargs printf "'%s'\n"`:

```sh
@courage:~ $ ls | xargs printf "'%s'\n"
'Desktop       '
'Documents     '
...
'tests         '
'web-tests'    
```

(For some reason `web-tests` doesn't have extra spaces?)

**Comment by sin-ack** [comment]
This seems to be because of `do_file_system_object_short` in ls, specifically: https://github.com/SerenityOS/serenity/blob/48347fb1c7df6f9645e8b48f7bacf7e82ba33f3d/Userland/Utilities/ls.cpp#L494

Could just add an `isatty` check here or a bit before that to fix it. I assume the reason it adds the spaces is to have them aligned as a grid like coreutils ls on GNU/Linux.

**Comment by tomuta** [comment]
... or only add the spaces when printing the next column.
