### ISSUE TITLE
Kernel: kmalloc: Out of memory shortly after fresh boot

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#5724]
There seems to be a OOM bug triggerable only by some applications and only upon system startup.

On VMware this causes the CPU to fault:

```
2021-03-11T14:42:35.864+11:00| vcpu-0| I125: Vix: [vmxCommands.c:7193]: VMAutomation_HandleCLIHLTEvent. Do nothing.
2021-03-11T14:42:35.864+11:00| vcpu-0| I125: MsgHint: msg.monitorevent.halt
2021-03-11T14:42:35.864+11:00| vcpu-0| I125+ The CPU has been disabled by the guest operating system. Power off or reset the virtual machine.
2021-03-11T14:42:35.864+11:00| vcpu-0| I125+ ---------------------------------------
```

Running QEMU reveals the issue is related to OOM:

```
[(UE) Cube(27:27)]: KERNEL PANIC! :^(
[(UE) Cube(27:27)]: kmalloc: Out of memory (requested size: 28)
[(UE) Cube(27:27)]: at ../Kernel/Heap/kmalloc.cpp:247 in void* kmalloc(size_t)
[(UE) Cube(27:27)]: KERNEL PANIC! :^(
[(UE) Cube(27:27)]: kmalloc: Out of memory (requested size: 43)
[(UE) Cube(27:27)]: at ../Kernel/Heap/kmalloc.cpp:247 in void* kmalloc(size_t)
```

This appears to be related to whether programs have been opened since booting the system.

I vaguely recall a similar issue to this  along time ago. Perhaps this is a regression.

# QEMU

On QEMU, this can easily be reproduced by running `ue Cube` immediately after boot. Comparatively, running `Browser`, closing the browser, then running `ue Cube` will not trigger a fault upon a fresh boot.

# VMware

I identified this while using VMware, so most of the commentary below relates to VMware rather than QEMU. However, the issue can be reproduced in both, as per above.

On VMware, running `LibGfxDemo` or `ue LibGfxDemo` immediately after a fresh boot will result in a fault.

Waiting for a few minutes after a fresh boot then running these programs also causes a fault.

However, running `Browser`, closing the browser, then running `LibGfxDemo` will not trigger a fault upon a fresh boot.

This behavior also finds its way into emulated programs. Running some programs in `UserspaceEmulator` will trigger a fault after a fresh boot, but will work if another application (such as `Browser`) has been opened first.

The table below is not 100% repeatable. I started documenting these before I realized that the issue related to freshness of the system.

Program | UE | Status
------------ | -- | -------------
Conway | |  success
Conway (ue) | UE | fault
Cube | |  success
Cube (ue) | UE | fault
Fire | |  success
Fire (ue) | UE | fault
TextEditor | |  success
TextEditor (ue) | UE | fault
LibGfxDemo | |  fault
LibGfxDemo (ue) | UE | fault

**Comment by bcoles** [comment]
@devsh0 I presume this is the same [issue](https://pastebin.com/7BCxmxVJ) you were having with `SoundPlayer` yesterday.

**Comment by devsh0** [comment]
Lol just opened an [issue](#5725 ).

**Comment by devsh0** [comment]
A common pattern that causes this seems to be a loop where a small amount of memory is allocated and not freed for a long time. Here's a simple program to reproduce this:

```
int main()
{
    size_t size = (48 * 1000);
    dbgln("Allocating {} bytes", size);
    void* mem = nullptr;
    for (size_t i = 0; i < 10000; i++) {
        dbgln("Counting: {}", i);
        mem = malloc(size);
        // free(mem); this prevents panic.
    }
}
```

If we launch an application before starting the program above, it "stretches" some kernel allocation limit and delays the panic. In other words, the above program will most often result in a kernel panic but if we launch it after, say, browser, we will observe the count to be a greater number than what we'd see if we start it immediately following a boot. I have sampled the observed counts (before oom kicks in) when the program is launched immediately following a boot vs after opening and exiting browser:

| Immediately after boot  | Next to browser |
| ------------------| -------------------------------------------------|
| 342      | 3582
| 343     | 10034
| 2302     | 3925
| 342     | 2330
| 343     | 8411
| 359     | Map failed (system behaves normally)
| 337     | 8404
| 2315     | 1968
| 2300     | Map failed (system behaves normally)
| 341     | 3576

I suspect that applications working properly after launching another program is just us getting lucky because of this delay in oom panic. The delay allows the next program to finish doing what it's doing with memory and free it. Note that if we also free the memory we allocate inside the loop, everything behaves normally.
