### ISSUE TITLE
more: more pager accepts input but refuses to give more output

### ISSUE THREAD

**Issue by bcoles** [SerenityOS/serenity#5776]
`more` input handling is inconsistent.

Sometimes pressing `enter` progresses past the first page (ie, `cat /res/pci.ids | more`). Sometime `enter` does not progress past the first page (ie, `dmesg | more`).

Pressing `space`, `down arrow` (or any other key combination) does not progress by line nor by page.

![more](https://user-images.githubusercontent.com/434827/111056331-5b9dd100-84d2-11eb-8624-75fa77cb1596.png)

**Comment by DrewStratford** [comment]
I've had a look and this seems to be a `Shell` bug.
Basically, once the first process in a pipeline exits, `Shell` will call `restore_ios`, setting the tty's pgrp back to the shell. Because of
this, when `more` next tries to read, it will recieve a `SIGTTIN` and be stopped.

The reason `cat /res/pci.ids | more` works, is that, since it is larger than `cat`'s buffer, `cat` doesn't immediately exit.

cc @alimpfard

**Comment by alimpfard** [comment]
Apparently any sufficiently terminal-related bug is a Shell bug.

@DrewStratford thanks for the detailed report (I could add you as co-author to that commit if you want? you did do most of the detective work afterall)

**Comment by DrewStratford** [comment]
@alimpfard Nah, it's all good.
