### ISSUE TITLE
date: set time and date

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#589]
It might be a good idea to open a separate ticket for NTP support but before that we certainly at least need a way to set the date and time; mainly because a number of programs and web sites don't work if your clock isn't set correctly

Something else that might also warrant another ticket is being able to set the time and date via the desktop clock.

**Comment by supercomputer7** [comment]
Setting time and date through the terminal is a major milestone before implementing NTP support, since NTP is basically a network protocol, but If we want that the whole subsystem will work eventually then this feature is mandatory - otherwise, if NTP gets the right time, how will it adjust the clock accordingly?
We can implement some sort of setting time & date method in the kernel (or whatever process that holds responsibility for the system clock), then it will be much easier to write a shell program to allow adjustment and then on top of that an implementation of NTP support.

**Comment by bugaevc** [comment]
Implemented in https://github.com/SerenityOS/serenity/pull/1396 (though it doesn't use `Core::ArgsParser` :imp:)

**Comment by awesomekling** [comment]
Let's close this and someone will eventually argsparsify it :)
