### ISSUE TITLE
Intel Desktop D875PBZ boot errors

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#601]
I have been unable to boot the latest Serenity ( f28fa616ebb657c7b094c24524dde5349ae61da2 ) on an Intel Desktop Board D875PBZ with a 3.2 Ghz P4 CPU and 512 MB RAM, using the same 200 GB IDE disk I used for my previous bare metal install.

I can boot Linux fine on it plus I have run memtest86 and let it complete at least 2 full passes without any errors so I don't think this is a hardware issue. It's worth noting that unlike my last bare metal install, this machine uses a (NVIDIA) AGP graphics card.

I enabled the MemoryManager.cpp debug options and this is what it gave us:

```
year: 3202, month: 1, day: 1
PIC(i8259): cascading mode, vectors 0x50-0x58
PS2MouseDevice: Device not detected
SB16: sb not readyVC: Switch to 0 (0x00184170)
Starting Serenity Operating System...
MM: Kernel page directory @ 0x00004000
MM: Protect against null dereferences
MM: PDE 0 not present (requested for V0x00000000), allocating
MM: Identity map bottom 5MB
MM: PDE 1 not present (requested for V0x00400000), allocating
MM: Quickmap will use 0x00000000
MM: Multiboot mmap: base_addr = 0x000000000, length = 0x00009fc00, type = 0x1
MM: Multiboot mmap: base_addr = 0x00009fc00, length = 0x000000400, type = 0x2
MM: Multiboot mmap: base_addr = 0x0000e6000, length = 0x00001a000, type = 0x2
MM: Multiboot mmap: base_addr = 0x000100000, length = 0x01fd30000, type = 0x1
MM: considering memory at 0x00100000 - 0x1fe30000
MM: Multiboot mmap: base_addr = 0x01fe30000, length = 0x000011810, type = 0x4
MM: Multiboot mmap: base_addr = 0x01fe41810, length = 0x0000ee7f0, type = 0x1
MM: considering memory at 0x1fe41810 - 0x1ff30000
MM: Multiboot mmap: base_addr = 0x01ff30000, length = 0x000010000, type = 0x3
MM: Multiboot mmap: base_addr = 0x01ff40000, length = 0x0000b0000, type = 0x4
MM: Multiboot mmap: base_addr = 0x01fff0000, length = 0x000010000, type = 0x2
MM: Multiboot mmap: base_addr = 0x0fecf0000, length = 0x000001000, type = 0x2
MM: Multiboot mmap: base_addr = 0x0fed20000, length = 0x000080000, type = 0x2
MM: Installing page directory
MM: Paging initialized.
MM initialized.
PIT: 1000 Hz, square wave (4a9)
PCI device: bus=0 slot=0 function=0 id=8086:2578
PCI device: bus=0 slot=1 function=0 id=8086:2579
PCI device: bus=1 slot=0 function=0 id=10de:0322
PCI device: bus=0 slot=3 function=0 id=8086:257b
PCI device: bus=2 slot=1 function=0 id=8086:1019
PCI device: bus=0 slot=29 function=0 id=8086:24d2
PCI device: bus=0 slot=29 function=1 id=8086:24d4
PCI device: bus=0 slot=29 function=2 id=8086:24d7
PCI device: bus=0 slot=29 function=3 id=8086:24de
PCI device: bus=0 slot=29 function=7 id=8086:24dd
PCI device: bus=0 slot=30 function=0 id=8086:244e
PCI device: bus=0 slot=31 function=0 id=8086:24d0
PCI device: bus=0 slot=31 function=1 id=8086:24db
PCI device: bus=0 slot=31 function=3 id=8086:24d3
MM: map_region_at_address will map VMO pages 0 - 0 (VMO page count: 1)
MM: PDE 768 not present (requested for V0xc0001000), allocating
MM: allocate_supervisor_physical_page vending P0x00400000
MM: PD K0x00300e28 (Kernel) at P0x00004000 allocated page table #768 (for V0xc0001000) at P0x00400000
MM: >> map_region_at_address (PD=0x00300e28) 'Signal trampolines' V0xc0001000 => P0x00000000 (@0x00000000)
MM: allocate_user_physical_page vending P0x1fe41810
ASSERTION FAILED: (u32)pte.physical_page_base() == physical_page.paddr().get()
VM/MemoryManager.cpp:621 in u8* MemoryManager::quickmap_page(PhysicalPage&)
```

**Comment by danboid** [comment]
@deoxxa

**Comment by danboid** [comment]
I should've mentioned that the CPU used on this board is a P4 Extreme Edition which means it supports amd64 / x86-64 instructions. Maybe I'm the first to try booting Serenity bare metal on a 64 bit box?

**Comment by danboid** [comment]
It will likely be Monday before I'll be able to test this machine again. If it has any ACPI settings in the BIOS I shall try adjusting them to see if that helps.

**Comment by supercomputer7** [comment]
Even though you run in on a processor that is capable of executing 64 bit code, it doesn't work this way.... Since you boot Serenity with the BIOS (the processor jumps to the reset vector, the BIOS is invoked and probably the firmware is using Unreal mode for accessing hardware), then after BIOS loads bootsector and just before the BIOS starts exectuing - the processor goes into legacy mode (i.e. 16 bit Real mode), then the bootloader prepares the 32 bit protected mode and then it transfers control to the kernel. 
So technically speaking, you have a 64 bit processor but you only use the 32 bit protected mode without going into long mode (also called x86-64, from the amd64 architecture which is essentially an extension to x86 architecture) .
I highly doubt that anybody can find an i686 processor that actually works to try Serenity on it, so no - you are not the first one to test Serenity on capable 64 bit processor, because probably everybody else that tried installing Serenity on bare metal hardware had a capable 64 bit processor.

About ACPI - you probably have nothing do about it, probably you can't even adjust it in the BIOS (maybe you can adjust some power settings and power modes but really nothing related to ACPI memory regions of course).

Now, about why your machine failed to boot - my guess is that this is an issue alignment.
From what I read about paging, there should be some sort of alignment requirement from what I checked.
https://wiki.osdev.org/Paging#Page_Table

`MM: allocate_user_physical_page vending P0x1fe41810
`
Address 0x1fe41810 isn't 4KiB aligned obviously, so I suspect there is a fault here when trying to add this to the page table.

**Comment by deoxxa** [comment]
Looks like we just blindly trust the bootloader to give us page-aligned memory regions. We should probably trim off the start/end of any regions the bootloader gives us to make sure they're page-aligned. We'll lose several kilobytes of that sweet, sweet memory, but it'll make this problem go away.

**Comment by supercomputer7** [comment]
> Looks like we just blindly trust the bootloader to give us page-aligned memory regions. We should probably trim off the start/end of any regions the bootloader gives us to make sure they're page-aligned. We'll lose several kilobytes of that sweet, sweet memory, but it'll make this problem go away.

No need to throw the region away. We can allocate the region from 0x01fe42000 to 0x1ff30000 - which is 4KiB aligned, and it will be ok. We leave some bytes alone but at least we get some part of the region allocated for Serenity.
The physical memory manager shouldn't assume that all the regions in the memory map are 4KiB aligned, so the physical memory manager must allocate accordingly.
