### ISSUE TITLE
LibRegex: "Invalid endpoint in range expression" parse error from jQuery 3.5.1

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#6202]
From jQuery 3.5.1: https://code.jquery.com/jquery-3.5.1.js

Error:
```
WebContent(35): Throwing JavaScript exception: [SyntaxError] RegExp compile error: Error during parsing of regular expression:
    ([\0-\x1f\x7f]|^-?\d)|^-$|[^\0-\x1f\x7f-\uFFFF\w-]
             ^---- Invalid endpoint in range expression.
```

From these lines:
```js
	// CSS string/identifier serialization
	// https://drafts.csswg.org/cssom/#common-serializing-idioms
	rcssescape = /([\0-\x1f\x7f]|^-?\d)|^-$|[^\0-\x1f\x7f-\uFFFF\w-]/g,
```

**Comment by GMTA** [comment]
I was just investigating this. This regex triggers the error:
```
/[\0-\x1f]/
```
This is caused by `\0` being interpreted as the character "0", which is `\x30` and comes after `\x1f`.

In `RegexParser`, the `read_digits_as_string` method is somehow being coerced into reading the `\0` escape sequence but does not consume the "0" while parsing. Simply consuming it does not solve the issue, since the result of this method is then an empty string which is interpreted as an absent value.
