### ISSUE TITLE
AK: Stack overflow in quick_sort

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#6629]
Steps to reproduce:

1. Build the `openssh` port with symbols (add `--disable-strip` to configopts).
2. Run `ssh <some host that has sshd running>`.
3. Wait for `ssh` to crash.
4. Wait for `CrashDaemon` to crash: https://gist.githubusercontent.com/gunnarbeutner/9b88fcd3be4a111b192a8b5a580fddea/raw/dc1fa69596ebae4ec331f1a57a6c718678f94723/log

This seems to happen because the debug symbols for `ssh` have lots of `Debug::Dwarf::LineProgram::LineInfo` entries.

**Comment by awesomekling** [comment]
Sounds like we could use a non-recursive sorting algorithm.

**Comment by Maato** [comment]
It should also be possible to rewrite the dual_pivot_quicksort to guarantee a maximum stack depth in a similar way as I did for the single_pivot_quicksort [here](https://github.com/SerenityOS/serenity/commit/9068398f6b9804f4afc812d6bb3f8d16937579b3) by iterating, instead of recursing, on the largest partition.
Another issue with the dual_pivot_quicksort (as it is now) is that a sorted array is a worst case input for it.
