### ISSUE TITLE
Shell+FileManager: Cannot remove directories

### ISSUE THREAD

**Issue by xeriab** [SerenityOS/serenity#6919]
The system is unable to delete directories while using `FileManager` or even from shell using the `rm` command.

The image below is the error thrown while deleting directory through `FileManager`:

[Error Message](https://ibb.co/ftcfTsX)

The below messages are printed when trying to remove directories.
```
[#0 FileManager(30:30)]: Ext2FSInode[1:48593]::write_bytes(): Empty block list
[#0 FileManager(30:30)]: Ext2FSInode[1:48596]::write_bytes(): Empty block list
[#0 FileManager(30:30)]: Ext2FSInode[1:48602]::write_bytes(): Empty block list
[#0 FileManager(30:30)]: Ext2FSInode[1:48606]::write_bytes(): Empty block list
```

**Comment by Maato** [comment]
This happens when write_bytes gets called to write 0 bytes (after the . and .. pseudo directories have been removed). Previously this was not an issue because directories were not reduced in size properly after removing files.
Should be fixed by returning from write_bytes if the amount of bytes to write == 0.
