### ISSUE TITLE
LibLine: Hang with 80% CPU after resizing Terminal to small size

### ISSUE THREAD

**Issue by sppmacd** [SerenityOS/serenity#7006]
Reproduce
* Run Terminal
* Resize to minimal size
* See as CPU rises
The most of time spent is in the Kernel:
![image](https://user-images.githubusercontent.com/42967349/117664049-9e61e980-b1a1-11eb-897d-0cfdc37ac4bf.png)
Nothing is displayed except blinking cursor in left bottom corner of screen. The Shell isn't killed even if Terminal is closed.
![image](https://user-images.githubusercontent.com/42967349/117662115-7d989480-b19f-11eb-9188-3fa395fccc2e.png)
![image](https://user-images.githubusercontent.com/42967349/117663979-8722fc00-b1a1-11eb-8426-16d475b182d4.png)

**Comment by alimpfard** [comment]
Looks like a LibLine issue, for some reason it thinks its origin is `(size_t)-1` when you resize fast (though I can only trigger it when resizing to a larger size...?)

**Comment by alimpfard** [comment]
Ah, it's because there are more lines than can fit on the screen, and LibLine doesn't know how to deal with that...so its origin becomes negative (i.e. a really big number), so it keeps printing newlines on the next draw

**Comment by alimpfard** [comment]
Here's the culprit:
https://github.com/SerenityOS/serenity/blob/master/Userland/Libraries/LibLine/Editor.cpp#L1386

A "fix" is simple, just clamp to the terminal size and it'll be merely wrong instead of spamming newlines; but this does bring up the question, how _should_ it handle overflow?

Whatever line editor zsh is using just cuts the text off at the opposite end of where the cursor is (`< ...`):
![shot-2021-05-10_18-57-39](https://user-images.githubusercontent.com/14001776/117675453-d1b47080-b1c1-11eb-8fff-05cf6e71413d.jpg)

And I'm not sure what bash is smoking, but it must be pretty good stuff:

https://user-images.githubusercontent.com/14001776/117677490-c104fa00-b1c3-11eb-847d-3413cb5feb11.mp4

(abcdefghijklmnopqrstuvwxyzaaaaaaa... a bunch of lefts, a bunch of rights, write some aaaa, C-a, hold a)

Fish basically acts like bash:

https://user-images.githubusercontent.com/14001776/117678287-7df75680-b1c4-11eb-8694-f53d3e0c103e.mp4

**Comment by alimpfard** [comment]
#7163 changes this to a `TODO()`, so it will no longer eat CPU, but rather just crash.
I'm still not sure what the best way to handle this case is.

**Comment by linusg** [comment]
Described behaviour is no longer the case, continued in #7296.
