### ISSUE TITLE
Kernel: tmpfs corruption

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7025]
Steps to reproduce:

1. Clone the serenity Git repo into `anon`'s home directory (on the host)
2. `cp -R serenity /tmp/serenity`.
4. Observe how some of the directories (e.g. `Userland/Libraries/LibJS/Runtime`) are missing all their directory entries, including `.` and `..`

**Comment by Maato** [comment]
I think this is related to an issue in FileDescription::get_dir_entries. It allocates a non-resizable buffer to store all the entries at once. For the size of the buffer it uses the max of metadata.size or PAGE_SIZE. In the case of tmpfs, it seems that metadata.size is 0 for directories (going by the size reported by FileManager). So if the serialized version of the directory entries is larger than 4096 bytes. No entries will be returned at all.

This is also an issue in the Ext2Filesystem right now, there metadata.size returns the size on disk of a directory. But that disk size does not correspond to the size of the serialized entries, most of the time it will work since directories are always a multiple of the block size on disk (1024), so there is likely to be some padding. But in cases where there happens to be no padding at all this will fail.

**Comment by Maato** [comment]
For confirmation that this is the cause, I increase the buffer size in FileDescription::get_dir_entries to 4  times PAGE_SIZE and to 4096*4 in dirent.cpp:allocate_dirp_buffer. After doing that, the `rm -rf /tmp/serenity` step completes successfully.
