### ISSUE TITLE
GML Playground: Hovering over the auto-completion window makes it disappear

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7165]
Steps to reproduce:

1. Enter `@` in the text editor and hit Ctrl-Space.
2. Try to select one of the options from the auto-completion window that appears.

![Screenshot from 2021-05-16 09-21-35](https://user-images.githubusercontent.com/388571/118389064-6c7cd700-b628-11eb-9f97-b6c4d1adcc39.png)

The auto-completion window disappears when the mouse cursor leaves the main GML Playground window (as it should). However, this also happens when it leaves the window by moving above the auto-completion window.

**Comment by sensaiankit** [comment]
I would like to work on this issue please

**Comment by Sreelakshmi-PJ** [comment]
I'm interested, and I would like to work on this.

**Comment by maxtrussell** [comment]
@gunnarbeutner I've been looking at this one, and I have a couple thoughts.

First, this bug seems to be present in HackStudio as well, and because the the autocomplete window disappears whenever the mouse triggers the `TextEditor::leave_event` function, it will likely be present in any application using `LibGUI::TextEditor`.

I don't see a clean way around this besides not exiting the autocomplete box when the mouse leaves the text editor widget.

Obviously this is subjective, but when I use autocomplete I only expect it to close when I do things like press "Escape", close the file, or switch focus to another window. This behavior is more consistent with my experience with other text editors.

If you agree, I can open a PR to remove `m_autocomplete_window->close()` from `TextEditor::leave_event`, and instead close the autocomplete box on loss of window focus.

**Comment by Sreelakshmi-PJ** [comment]
Hi @maxtrussell ! I was able to solve the issue of the auto-completion window disappearing on hover and I'm working on the second part (to close it when the pointer leaves the playground window). I tried creating a rectangle using coordinates and dimensions of the auto-completion window and check if it has the pointer inside it after on a `TextEditor::leave_event`, but there seems to be something weird with the location of the rectangle. I also received a suggestion from Discord to try to just `show()` the auto-completion window on a mouse enter event but wasn't able to implement it.

I've been looking into the issue for the past two weeks and I'm still working on it. I would love to open a PR and I also agree with your "close the autocomplete box on loss of window focus" suggestion because it makes it simpler.

**Comment by maxtrussell** [comment]
@Sreelakshmi-PJ My thinking was that because the `show()` method of the autocomplete box requires a position, I feel like that could lead to some weirdness with the box moving around slightly when triggering the autocomplete box's enter_event. Not to mention, closing then showing seems not ideal.

I'm curious to see what you come up with!

Sorry for butting in, I was hunting for some inactive "good first issue"s, and I guess I should just be more patient :)

**Comment by Sreelakshmi-PJ** [comment]
I do agree with you and would wait for some suggestions @gunnarbeutner to proceed. Thank you for the reply and for letting me continue as I'm new here too :).

**Comment by gunnarbeutner** [comment]
I just reported this. If you want help with architectural things Discord might be a better place. :)

**Comment by sr1j** [comment]
> The auto-completion window disappears when the mouse cursor leaves the main GML Playground window (as it should)

I've opened #8005 for this.
