### ISSUE TITLE
Solitaire: Implement an action to move all eligible cards to the foundation stacks

### ISSUE THREAD

**Issue by gunnarbeutner** [SerenityOS/serenity#7251]
I vaguely remember Windows Solitaire having that when you press the `space` key.

**Comment by matthewbjones** [comment]
@gunnarbeutner in Windows XP Solitaire, the `space` key deals the next card / set of cards. I tried searching around the Internet for the "move all eligible cards to the foundation stacks" but wasn't able to turn up much, other than https://answers.microsoft.com/en-us/windows/forum/windows_7-gaming/solitaire-game-auto-finish/3677f7cb-08ac-4676-883b-71cca4a84bb2 which references once you've achieved a win state, you could right-click in any empty space to auto finish the same, but on Windows XP Solitaire I could not get this to happen (I'm assuming the reference link talks about Windows 7 Solitaire)

If you're able to find more info on what would trigger "move all eligible cards...", I could definitely implement it (I have this implemented locally using `space` but that key is reserved for other behavior)

I can also implement the `space` to deal cards functionality as well.

**Comment by gunnarbeutner** [comment]
You're right, I just tried this again with Windows 3.11's Solitaire game:

* `space` in Solitaire deals the next card and moves the mouse pointer on top of the deck's card.
* Right-clicking doesn't seem to do anything, no matter whether there's a win state or not

I don't have any other versions of Solitaire right now but I guess implementing `space` to deal cards and right-clicking to move cards to the foundation stacks would be useful IMO. What do you think?

**Comment by matthewbjones** [comment]
I think both sets of functionality is useful.

I currently have `tab` working locally to automatically move any cards into the foundation stacks that are eligible to be moved there (at any point during the gameplay). I went with `tab` because I was still trying to research the clicking in various versions of Solitaire. I wasn't able to find any version that does the special right-click, so going with the `tab` key for now.

I also currently have `space` dealing the next card or three-cards, without moving the cursor. I initially found it annoying that it would do that, but upon further consideration it may be more convenient that now your cursor is closer to being able to drag and play the drawn card (but then why not move the cursor to the drawn card for even more convenience?) Separately, I am spending most of my time trying to debug a drawing issue where dealing a card/cards using `space` causes a rendering issue with the stock stack:

<img width="207" alt="Screen Shot 2021-05-31 at 11 54 29 AM" src="https://user-images.githubusercontent.com/955163/120227730-f6bb6280-c206-11eb-8141-bd2a15a28577.png">

It's not rendering the backside of the card pile. It does, however, when using normal click functionality but when using `space` and executing the same set of code, it does not. It will re-render the pile if a card is dragged near it, etc. I'm going to continue to try my best to debug this.
