### ISSUE TITLE
Kernel: LibC headers that are included in Kernel code

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#7341]
Here's a list as of 68f76b9e3750c8f4e5e3ee8c3d346772ce6d3593

```
~/serenity$ find Kernel -type f | xargs grep "#include <LibC/" | cut -d: -f2- | sort | uniq
#include <LibC/elf.h>
#include <LibC/errno_numbers.h>
#include <LibC/fd_set.h>
#include <LibC/limits.h>
#include <LibC/mallocdefs.h>
#include <LibC/signal_numbers.h>
#include <LibC/stdarg.h>
#include <LibC/sys/arch/i386/regs.h>
#include <LibC/sys/ioctl_numbers.h>
#include <LibC/sys/prctl_numbers.h>
#include <LibC/sys/ttydefaults.h>
```

Ideally we would not be including LibC headers from the kernel, it feels unsanitary.

**Comment by MaxWipfli** [comment]
It seems like most of those are cases where we include some constants (or similar), not any code. An example can would be `LibC/mallocdefs.h`, which is used by the `CPU` as follows (the `MALLOC_SCRUB_BYTE` and `FREE_SCRUB_BYTE` macros are from `mallocdefs.h`):
https://github.com/SerenityOS/serenity/blob/d60ebbbba6429bf7f3ce58783acd8232d487d4b9/Kernel/Arch/i386/CPU.cpp#L295-L315

The obvious "solution" would be to duplicate all those constants in Kernel code, but that seems dumb. Maybe we could move them to a new directory, maybe `AK/Constants` (or a better name), and them directly from the Kernel. So instead of including `LibC/malllocdefs.h`, the `CPU` would include:
```
#include <AK/Constants/mallocdefs.h>
```
The constants in `LibC/mallocdefs.h` could the just be moved to `AK/Constants/mallocdefs.h` and included within the `LibC/mallocdefs.h`. We could then strictly forbid any "executing code" in `AK/Constants`, only allowing definitions of constants and "constant macros".

For files only containing constants, such as `LibC/sys/ttydefaults.h`, the LibC header could be a simple wrapper around the `AK/Constants` header, where as `LibC/mallocdefs.h` would still contain some code which is not used by the Kernel (all the structs, et cetera).

**Disclaimer**: This is maybe a very naïve suggestion, I don't even know if this "wrapping one header inside another one" is actually possible the way I think of it.

**Comment by alimpfard** [comment]
Sidenote, That's not all of them:
```
 find Kernel -type f | xargs grep "#\\s*include <LibC/" | cut -d: -f2- | sort | uniq
#include <LibC/elf.h>
#include <LibC/errno_numbers.h>
#    include <LibC/fd_set.h>
#include <LibC/fd_set.h>
#    include <LibC/limits.h>
#include <LibC/limits.h>
#include <LibC/mallocdefs.h>
#include <LibC/signal_numbers.h>
#include <LibC/stdarg.h>
#include <LibC/sys/arch/i386/regs.h>
#include <LibC/sys/ioctl_numbers.h>
#include <LibC/sys/prctl_numbers.h>
#include <LibC/sys/ttydefaults.h>
```

**Comment by timschumi** [comment]
There don't seem to be any remaining `LibC` includes in the kernel.
