### ISSUE TITLE
RequestServer/Browser: Loading a webpage yields `write:try again` errors.

### ISSUE THREAD

**Issue by TobyAsE** [SerenityOS/serenity#7361]
When visiting a webpage in the Browser (to repro, use the SerenityOS Github bookmark), after some time a lot of `RequestServer(xx:xx): perror(): IODevice::write: write: Try again` errors come up and the website doesn't continue to load while the CPU stays at 100%. After some time (literally a few minutes) the page continues to load.

**Comment by awesomekling** [comment]
cc @alimpfard

**Comment by alimpfard** [comment]
One of those logs per TLS request is expected behaviour, and not an issue - it's just the server closing the connection before we send the close notify (as the spec dictates).
As for the 100% CPU utilisation, that is mostly LibWeb doing LibWeb things and in the case of github, LibJS printing who-knows-how-many parse errors to WebContent's stderr.

**Comment by TobyAsE** [comment]
So this is works-as-intended and can be closed?

**Comment by alimpfard** [comment]
I believe so.
