### ISSUE TITLE
TTY: ^D does not work as expected

### ISSUE THREAD

**Issue by awesomekling** [SerenityOS/serenity#7419]
I am not able to EOF a file with ^D.

To reproduce, run `cat` and press ^D. :)

cc @BertalanD

**Comment by BertalanD** [comment]
This was a stupid mistake from me: when reading, we would report 1 byte read because of the '\0' that we use in TTY.cpp to signify EOF.

We could fix this by returning 0 when the next byte is a '\0', but that would mean that we can't have them as inputs in canonical mode. We could store the indices that we should treat specially in a separate array, or we could have a bitmask for it (that would require having a fixed size buffer like 4096 bytes).
