### ISSUE TITLE
Kernel: critical_console_out() doesn't handle newlines

### ISSUE THREAD

**Issue by linusg** [SerenityOS/serenity#7562]
As a result, multi-line assertion messages are mashed together.

**Comment by supercomputer7** [comment]
I personally call it more a "lack of feature", basically because parsing new line is done on the default print path (which is not OOM-safe), but if we have a `KStringBuilder` that can handle such situations, we can probably support new lines easily.

Or maybe, we could try to detect `\n` when printing critical strings... I'll try to work on it but I'm not sure I have a good solution for now.
