### ISSUE TITLE
Spreadsheet: Pressing Enter after Tab should return to the original column

### ISSUE THREAD

**Issue by MaxWipfli** [SerenityOS/serenity#7591]
When you press Tab to move to the right, it is expected for the selection to move back to the original column.

An example:
**In A1:** \<TAB\>
**In B1:** \<TAB\>
**In C1:** \<ENTER\>
Now you are in C2, whereas you should land in A2.

**Comment by Aditya04-code** [comment]
hey can you tell me the file name in which issue is!,

**Comment by Aditya04-code** [comment]
hey, can you tell me the file name in which the issue is! as it's my first time contributing to any open-source program.

**Comment by ADKaster** [comment]
@Aditya04-code The Spreadsheet application's source code is in `Userland/Applications/Spreadsheet/` . The issue is likely in the SpreadsheetView class. But it might be a related class, such as the SpreadsheetModel or SpreadsheetWidget. Feel free to hop in the discord to discuss possible solutions to the problem in the #development or #userland channels :)

**Comment by Aditya04-code** [comment]
> @Aditya04-code The Spreadsheet application's source code is in `Userland/Applications/Spreadsheet/` . The issue is likely in the SpreadsheetView class. But it might be a related class, such as the SpreadsheetModel or SpreadsheetWidget. Feel free to hop in the discord to discuss possible solutions to the problem in the #development or #userland channels :)

discord link ?

**Comment by ADKaster** [comment]
I would recommend reading through the project's README.md and associated documentation in Documentation/ for questions like that :)

**Comment by Aditya04-code** [comment]
Sure   Sent from Mail for Windows 10 From: Andrew KasterSent: 30 May 2021 10:14 PMTo: SerenityOS/serenityCc: Aditya04-code; MentionSubject: Re: [SerenityOS/serenity] Spreadsheet: Pressing Enter after Tab should return to the original column (#7591) @Aditya04-code The Spreadsheet application's source code is in Userland/Applications/Spreadsheet/ . The issue is likely in the SpreadsheetView class. But it might be a related class, such as the SpreadsheetModel or SpreadsheetWidget. Feel free to hop in the discord to discuss possible solutions to the problem in the #development or #userland channels :)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bcoles** [comment]
> 
> 
> When you press Tab to move to the right, it is expected for the selection to move back to the original column.
> 
> An example:
> **In A1:** <TAB>
> **In B1:** <TAB>
> **In C1:** <ENTER>
> Now you are in C2, whereas you should land in A2.

I disagree.

Landing in C2 is inline with my recollection of Microsoft Office (since 97) and Open Office and Libre Office and Kingsoft Office and ...

If users want this behavior (for enter to act as both carriage return and line feed) then a configuration option would be useful. It is nice to have options.

**Comment by MaxWipfli** [comment]
Are you sure? I just tried again on MS Office and LibreOffice. If you advance the cursor with the arrow keys, Enter puts you into the cell below, but if you use Tab, it puts you into the original column (which does not have to be the A column).

**Comment by bcoles** [comment]
> If you advance the cursor with the arrow keys, Enter puts you into the cell below, but if you use Tab, it puts you into the original column (which does not have to be the A column).

TIL
