### ISSUE TITLE
FileManager: context menu options

### ISSUE THREAD

**Issue by danboid** [SerenityOS/serenity#826]
There are currently no context menu options when clicking in the left pane but it would be nice to be able to copy/paste dirs and create new ones within the tree view pane.

When you click on some whitespace in the right pane ie not on a file, dir or icon you still get the options 'Open in TextEditor' and Properties. IMO the only option that should be available in this scenario is 'Create new directory', which is the main option missing from the right pane context menu. Unsurprisingly, choosing 'Open in TextEditor' when no files are selected doesn't do anything.

**Comment by remyabel** [comment]
I'm currently working on adding the context menu to the FileTree, but code duplication seems to be a problem. I would like to do this:

```c++
      auto selected_file_paths = [&](const GAbstractView& view, const GModel& model) {
          Vector<String> paths;
          view.selection().for_each_index([&](const GModelIndex& index) {
              auto name_index = model.index(index.row(), GDirectoryModel::Column::Name);
              auto path = model.data(name_index, GModel::Role::Custom).to_string();
              paths.append(path);
          });
          return paths;
      };
```

But you would have to add state to `GAction` or allow `GAction` to accept parameters, otherwise the code ends up looking like this:

```c++
      auto directory_view_copy_action = GCommonActions::make_copy_action([&](const GAction&) {
          auto& view = directory_view->current_view();
          auto& model = *view.model();
     // etc...
```

Essentially all the actions have to be written to be view/model-agnostic.

Thoughts?

**Comment by remyabel** [comment]
@awesomekling Thanks for the previous commit, but I don't think it solves my problem. I would think it works like this:

```c++
    auto copy_action = GCommonActions::make_copy_action([&](const GAction& action) {
        Vector<String> paths;
        auto& view = to<GAbstractView>(*action.activator());
        paths = selected_file_paths(view, *view.model());
```

(Assume I've already added code for `is<GAbstractView>`)

However, this code will not succeed because the `activator()` can tell you which button or menu activated the action, but not which view. Let me know if I'm approaching this problem the wrong way.

**Comment by remyabel** [comment]
Nevermind, I see I can do something like this:

```c++
    auto directory_view_context_menu = GMenu::construct("Directory View");
    // ...etc...
    auto copy_action = GCommonActions::make_copy_action([&](const GAction& action) {
         Vector<String> paths;
         auto& activator = *action.activator();
         auto& context = (is<GMenu>(activator)) ? to<GMenu>(activator) : *to<GButton>(activator).parent();
         if (context.name().starts_with("Directory View")) {
             paths = selected_file_paths(directory_view->current_view(), *directory_view->current_view().model());
         } else {
             paths = selected_file_paths(tree_view, *tree_view->model());
         }
```

Still feels like I'm not quite approaching this the right way. I'll report back if I have success, but suggestions welcome.

**Comment by awesomekling** [comment]
You can just compare against the menu pointer:
```cpp
if (action.activator() == directory_view_context_menu) {
    // directory view stuff
} else {
    // 
}
```

**Comment by awesomekling** [comment]
That said, what if it's activated via the global keyboard shortcut?
Then the context should be whichever view has focus..

**Comment by remyabel** [comment]
> You can just compare against the menu pointer:

Thanks.

> Then the context should be whichever view has focus..

Yeah, this feature was deceptive and not as simple as I thought it would be. I've pushed my WIP branch so you can take a look but I'm taking a break for now. 

https://github.com/remyabel/serenity/commit/9f2ab186d541b958796f5763ce3f771cb280865d

One thing I noticed is that my original approach doesn't make sense since `GDirectoryModel` and `GFileSystemModel` are different so there's still special handling required.

**Comment by remyabel** [comment]
Is this fixed now?

**Comment by danboid** [comment]
I originally suggested adding a context menu to the tree view but I'm not so sure that is really necessary or that useful now. All the other issues are fixed so I'm closing this.

**Comment by danboid** [comment]
Ooops!

I just re-read this issue and noticed that @remyabel commited support for a context menu in the tree view but that isn't working for me.

**Comment by danboid** [comment]
Maybe I should open a separate ticket but shouldn't we also show files in the tree view and not just directories?

Whaddya think @awesomekling and @remyabel ?

**Comment by remyabel** [comment]
> commited support for a context menu in the tree view but that isn't working for me.

What isn't working? You should be to right-click the directories in the tree view and a context menu will appear. I originally thought about having a context menu appear if you click *no* directory, but then I realized this logically makes no sense since you want to have a parent directory selected when creating a new one.

> Maybe I should open a separate ticket but shouldn't we also show regular files in the tree view and not just directories?

If no one already tackles it, I'll look into it.

**Comment by remyabel** [comment]
I just pulled the latest changes from master and you're correct it no longer works. Since @awesomekling made the new changes I'll defer to them.

**Comment by bugaevc** [comment]
If it's all fixed, can we close this now?

**Comment by danboid** [comment]
Yes, this is all good now.
