### ISSUE TITLE
AK/HashTable.h unlikely compilation fails in macos

### ISSUE THREAD

**Issue by w62** [SerenityOS/serenity#8261]
../.././AK/HashTable.h:271:44: error: unknown attribute 'unlikely' ignored [-Werror,-Wunknown-attributes]
            if (!m_collection_data.head) [[unlikely]] {
                                           ^
../.././AK/HashTable.h:353:44: error: unknown attribute 'unlikely' ignored [-Werror,-Wunknown-attributes]
            if (!m_collection_data.head) [[unlikely]] {
                                           ^
2 errors generated.
[112/3840]

 gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by IdanHo** [comment]
Looks like AppleClang did not implement C++20's `likely`/`unlikely` attributes yet.

**Comment by ADKaster** [comment]
Apple clang doesn't implement numerous C++20 features used in the host build of the project.

According to the chart here: https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_13.x_(since_SwiftUI_framework)_2

Apple Clang 12.0.5 is equivalent to upstream llvm 11.1.0, which does not support very much from c++20.

That's why the docs tell you to use gcc-10 or gcc-11 from homebrew rather than apple clang.

https://github.com/SerenityOS/serenity/blob/master/Documentation/BuildInstructions.md#macos-prerequisites

> As of 2020-08-06, you might need to tell the build system about your newer host compiler. Once you've built the toolchain, navigate to Build/i686/, rm -rf *, then run cmake ../.. -G Ninja -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10, then continue with ninja install as usual.
