### ISSUE TITLE
Kernel: Misaligned out of bounds reads from /dev/zero ignored

### ISSUE THREAD

**Issue by ADKaster** [SerenityOS/serenity#8352]
So here's a thinker:

In `Userland/Utilities/test_efault.cpp` we do this:
```
    int fd = open("/dev/zero", O_RDONLY);
    int rc;

    // Test a one-page mapping (4KB)
    u8* one_page = (u8*)mmap(nullptr, 4096, PROT_READ | PROT_WRITE, MAP_ANONYMOUS | MAP_PRIVATE, 0, 0);
    VERIFY(one_page);
    EXPECT_OK(read, one_page, 4096);
    EXPECT_EFAULT(read, one_page, 4097);
```

Which after the macros are stripped away is morally equivalent to

```
    int fd = open("/dev/zero", O_RDONLY);

    // Test a one-page mapping (4KB)
    u8* one_page = (u8*)mmap(nullptr, 4096, PROT_READ | PROT_WRITE, MAP_ANONYMOUS | MAP_PRIVATE, 0, 0);
    VERIFY(one_page);
    int rc = read(fd, one_page, 4096);
    if (rc < 0) {
        perror("read(one_page, 4096)");
    }
    rc = read(fd, one_page, 4096 + 1); // out of bounds *and* misaligned
    if (rc < 0 || errno != EFAULT) {
        puts("why didn't we fault?");
    }
```

The second expect fails with

`Expected EFAULT: read(0x00904000, 4097), got rc=4097, errno=0`. 

So, not only did we not fail the syscall but it claims we were able to read out of bounds!

If userspace does this, with `one_page[4096] = 42` or some such, then we get a segfault as expected.

Seems what's happening is, sys$read() is relying on the ZeroDevice to catch this size argument that's too large. But ZeroDevice just calls UserOrKernelBuffer::memset(0, 0, size); Which in turn calls memset_user(m_buffer, 0, size) which eventually calls  safe_memset(dest_ptr, 0, size, fault_at); 

So all of this is relying on safe_memset to fault at the final address in order to return EFAULT back to userspace. But! it doesn't because ... I don't know why. I can't read Tom's inline assembly :^)

cc @tomuta

**Comment by tomuta** [comment]
The inline assembly is pretty much just a copy of what we had in Kernel/StdLib.cpp and beefed up so that we can resume at specific labels in case the MMU detected a violation.

That being said, I think the problem is this line:
https://github.com/SerenityOS/serenity/blob/2ef28602ba512ca12f6dfeb61ad188eb1c899729/Kernel/Arch/x86/common/SafeMem.cpp#L151

It should read
```c++
if (n == 0)
```

Because `remainder` will always be `0` if no fault happened, it would have cut off the memset prematurely for the last `& 3` bytes. Which is what you're seeing.
