### ISSUE TITLE
Assistant: Kernel panic when launching Assistant from Assistant

### ISSUE THREAD

**Issue by lanmonster** [SerenityOS/serenity#8393]
Steps to Reproduce:
1. launch assistant (super + space)
2. search for "assistant" (no quotes)
3. launch the app result
4. panic!

**Comment by mrkaragoz** [comment]
Yeah. If I gave birth to myself I would panic too.

**Comment by awesomekling** [comment]
Turns out Assistant was loading a copy of the filetype-folder system icon for every matching path. That explains the explosive growth in memory.

I made bitmap loading lazy in 513e67e, so we don't load more icons than what we need to show on screen.

That appears to have resolved this issue, so let's close it :^)
