### ISSUE TITLE
Kernel: m_threads_for_coredump.is_empty() assertion failure in Process::die

### ISSUE THREAD

**Issue by Lubrsi** [SerenityOS/serenity#8485]
Found with stress-ng.
Command: `stress-ng --dev 1`
Trace:
```
[stress-ng(34:36)]: ASSERTION FAILED: m_threads_for_coredump.is_empty()
[stress-ng(34:36)]: ../../Kernel/Process.cpp:629 in void Kernel::Process::die()
[#0 stress-ng(34:36)]: 0xc0716859  abort +0x17e
[#0 stress-ng(34:36)]: 0xc07166bb  _abort +0x0
[#0 stress-ng(34:36)]: 0xc04ee705  Kernel::Process::die() +0x3af
[#0 stress-ng(34:36)]: 0xc04ef5f8  Kernel::Process::crash(int, unsigned int, bool) +0x5d4
[#0 stress-ng(34:36)]: 0xc0718b2c  illegal_instruction_handler +0x0
[#0 stress-ng(34:36)]: 0xc07196bc  page_fault_handler +0xa1f
[#0 stress-ng(34:36)]: 0xc071693e  page_fault_asm_entry +0x26
```

**Comment by hieronymusma** [comment]
This issue can be reproduced by creating an application that spawns two threads. Both threads must trigger a page fault (e.g. dereferencing a null pointer).

As far as I'm understood, the problem is following:
After the first page fault `Process::die()` is called and all threads are added to `m_threads_for_coredump`. Then a context switch is triggered in `Thread::die_if_needed()` in order to tear down the process. But this context switch schedules the other thread which triggers `Process::die()` again. Then the assertion fails because `m_threads_for_coredump` is not empty.

Does anybody know, how we can avoid that? If someone can give me a hint I'd be glad to help. :)

**Comment by tomuta** [comment]
It's possible that #8728 also fixed this issue.

**Comment by hieronymusma** [comment]
Unfortunately not, I've tried it again with your changes...

What should be the best way to avoid this bug? Should we check with a flag if a process has already crashed and then don't call `Process::die()` again?
