### ISSUE TITLE
Tweaks required to build on macOS

### ISSUE THREAD

**Issue by VKoskiv** [SerenityOS/serenity#927]
I got it to build fairly easily under the latest macOS `(Catalina 10.15.2)`, but a few little details need fixing:

- ~AK is built using `-Werror`, so it fails to build because there are unused parameters in `AK/SinglyLinkedList.h`. I'm going to file a PR to remedy this, it's a simple fix.~ **Resolved by 5d1acdda**

- The build system forgets to compile IPC for `Servers/ProtocolServer`. I'm not entirely sure why, my `make`-fu is very weak still. The workaround currently is to simply: `cd Servers/ProtocolServer && make`, and then re-run `makeall.sh`, and it works.

**Comment by Pagghiu** [comment]
I have been experiencing the ProtocolServer IPC issue as well.
The reason is that `Browser` depends on ProtocolServer but there is no dependency specified for it in the makefile.

**Comment by Pagghiu** [comment]
I think commit b1a8ca211f8c6fad9408e8b82bba52bbc93868ff does not fix the second issue here reported, as my comment was not accurate enough 👀 .
The makefile dependency should be added to `LibHTML`, used by `Browser`, because the build fails when compiling `ResourceLoader.cpp`, that is part of the first library.

**Comment by arraystock** [comment]
Now we just need [flock](https://github.com/discoteq/flock) 😉

**Comment by Pagghiu** [comment]
Done, tested and sent a PR #951 😄

**Comment by awesomekling** [comment]
It's my understanding that the macOS build has been working for some time. Closing this.
