### ISSUE TITLE
Error after building on Ubuntu20.04

### ISSUE THREAD

**Issue by DenverDaveH** [SerenityOS/serenity#9523]
Hello,
After making sure I had all prerequisites installed on Focal, I build the tool chain and then this:

sudo ./Meta/serenity.sh run
CMake Error: The source directory "/home/me/serenity/Build/i686" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
dave@dave-VirtualBox:~/serenity$

Thoughts? I did some searching here and via DDG and found nothing specific to Serenity.
Thanks

**Comment by ADKaster** [comment]
Where did you run that script from?

Two things to keep in mind, 1) you really don't want to run the build as `sudo` because then all your files will be owned by root. and 2) the ./Meta/serenity.sh script should be run from `/home/me/serenity`... which it looks like it's done? The fact that it's choosing /home/me/serenity/Build/i686 as the *source* directory is very suspicious. running `cmake -S /home/me/serenity -B /home/me/serenity/Build/i686` should get your script in the place it's supposed to be?

**Comment by DenverDaveH** [comment]
Hello,
Thank you for the update. 
I did a chown to my non root user and did the rebuilod-toolchain and that went off with 0 errors.
So now I am address your cmake command and am getting this error:
cmake -S /home/me/serenity -B /home/me/serenity/Build/i686
CMake Error: The source directory "/home/me/serenity/Build/i686" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

What did I do wrong?

**Comment by DenverDaveH** [comment]
I think I found the issue:
~/serenity/Build/i686$ ls
Root
dave@dave-VirtualBox:~/serenity/Build/i686$ 
Going to delete the serenity dir structure and redownload it and then start without using sudo and see what that does.

**Comment by DenverDaveH** [comment]
Still getting the error. So at my /home/me root dir I did a find for CMakeLists.txt and found a bunch of them in:
/serenity/Userland
/serenity/Tests/
/serenity/CMakeLists.txt
/serenity/AK
/serenity/Toolchain/
/serenity/Meta/Lagom/
/serenity/Meta/CMake/
/serenity/Kernel/

FYI to get the code I am running this command:
git clone https://github.com/SerenityOS/serenity.git

Thanks!

**Comment by DenverDaveH** [comment]
cmake -S /home/me/serenity -B /home/me/serenity/Build/i686
CMake Error: The source directory "/home/me/serenity/Build/i686" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Should I just download the source via git command and not rebuild the toolchain? and then run your cmake command?

**Comment by DenverDaveH** [comment]
Ok I copied the CMakeLists.txt file from the /home/me/serenity folder to the i686 with this result:
cmake -S /home/me/serenity -B /home/me/serenity/Build/i686
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:12 (message):
  A GCC version less than 10.2 was detected (7.5.0), this is unsupported.

  Please re-read the build instructions documentation, and upgrade your host
  compiler.



-- Configuring incomplete, errors occurred!
See also "/home/dave/serenity/Build/i686/CMakeFiles/CMakeOutput.log".

So it seems that the system default gcc compiler is being picked up even though I did install v10 per the build instructions.  
I am looking at changing the default compiler to 10 from 7. If you know of a quick way, feel free as I feel this is the root of my issue.
Thanks

**Comment by DenverDaveH** [comment]
Well we have a new error after setting the gcc/g++ compiler to the 10x version:
~/serenity$ Meta/serenity.sh run
CMake Error: Error: generator : Ninja
Does not match the generator used previously: Unix Makefiles
Either remove the CMakeCache.txt file and CMakeFiles directory or choose a different binary directory.
I renamed the files and ran the run command and got the same error.

Thanks

**Comment by ADKaster** [comment]
Hey @DenverDaveH  can you post your CMake version and such in the #build-problems channel in discord? I'm thinking there's some context missing here and it's much easier in that environment. 

You should not move the CMake files at all.

Since your host gcc is so old, you'll need to pass the -DCMAKE_CXX_COMPILER and -DCMAKE_C_COMPILER flags. But... Meta/serenity.sh is really supposed to discover the right gcc version for you so any errors in that detection logic would be worth a PR.

If you configure with the Makefile generator you need to rm your CMakeCache.txt and CMakeFiles/ directories in order to use the Ninja generator (and reconfigure with -GNinja)

**Comment by ADKaster** [comment]
Resolved this one in discord, seems deleting Build/i686 and re-running serenity.sh got the job done.
