### ISSUE TITLE
JS: WeakSet tests spuriously cause CI failures

### ISSUE THREAD

**Issue by BenWiederhake** [SerenityOS/serenity#9931]
We have pretty flaky CI, so let's try to reduce that a bit.

A [non-JS PR](https://github.com/SerenityOS/serenity/pull/9928#issuecomment-916835849) fails CI, due to a [JS test failure in WeakSet](https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=1707&view=logs&j=42f0633d-9ac7-51d1-0d17-9c28359eb2e8&t=0b0ab1d1-26b7-5e80-1cb6-e2436a5557c7&l=416). Here is [another example for `Clang_x86_64`](https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=1682&view=logs&j=42f0633d-9ac7-51d1-0d17-9c28359eb2e8&t=0b0ab1d1-26b7-5e80-1cb6-e2436a5557c7&l=416), and an [example on `Clang_i686`](https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=1597&view=logs&j=2ebe0bba-9b6a-54a9-e644-67b37013ad1f&t=db9c34f3-6624-5520-9c97-fca3483150ca&l=418).

Logs point at an actual logic error, not just platform flakiness:
```
 FAIL  builtins/WeakMap/WeakMap.prototype.set.js
     ❌ Suite:  <top-level>
         Test:   automatic removal of garbage-collected values (failed):
                 ExpectationError: toBe: expected _0_, got _1_
```

Since I don't know enough about JS garbage collection, I hope this motivates some JS people to care about this issue.

Flaky CI is worse than no CI, in my opinion, because it teaches people to ignore CI results.

CC @linusg

**Comment by BenWiederhake** [comment]
Turns out, @davidot is already on it, with #9878 and continuing fixes.

**Comment by davidot** [comment]
This should have been fixed in 43b17f27a31f160eb2c92ed51bcc78b1efd93042.
And I have not seen it for PR with that commit.
Except for Clang_x86_64 which seems to consistently fail on master currently.

https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=1699&view=logs&j=42f0633d-9ac7-51d1-0d17-9c28359eb2e8&t=0b0ab1d1-26b7-5e80-1cb6-e2436a5557c7

https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=1698&view=logs&j=42f0633d-9ac7-51d1-0d17-9c28359eb2e8&t=0b0ab1d1-26b7-5e80-1cb6-e2436a5557c7

https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=1692&view=logs&j=42f0633d-9ac7-51d1-0d17-9c28359eb2e8&t=0b0ab1d1-26b7-5e80-1cb6-e2436a5557c7

Every commit from 1864b2b82856b332e323cdf167708abee9667040 up to 706323beb1d336f57c84e9d04ca12d541a82dcd8 seems to have this failure

And all the Clang_i686 also seem to suffer an exact identical failure in all those commits so maybe there is a clang problem?

**Comment by davidot** [comment]
And I can't reproduce it locally on Clang_x86_64. So I currently think it is some clang CI failure thing perhaps?

**Comment by davidot** [comment]
And it seems to have fixed itself?
https://dev.azure.com/SerenityOS/SerenityOS/_build/results?buildId=1722&view=logs&j=42f0633d-9ac7-51d1-0d17-9c28359eb2e8&t=d0ad3fed-0535-4130-b14e-d379ce616dfb

And more runs are passing now

**Comment by IdanHo** [comment]
As we discussed on discord, this might have just been a weird caching issue, as it seems all new runs are passing.

**Comment by BenWiederhake** [comment]
Since this doesn't seem to be occurring anymore, I'll go ahead and close this. Let's see whether this causes the issue to re-appear :D
