### ISSUE TITLE
PixelPaint: The box, ellipse and line tools are drawn with an offset of half a pixel in image space

### ISSUE THREAD

**Issue by Granddave** [SerenityOS/serenity#9970]
As seen below:

Preview (mouse pressed):
![1](https://user-images.githubusercontent.com/13297896/132954650-6345e117-a88e-4c40-b289-ea797c2fe521.png)

Drawn (mouse released):
![2](https://user-images.githubusercontent.com/13297896/132954651-e82046c1-e0d7-4de7-9db2-3abdfbdb95bd.png)

**Comment by mustafaquraish** [comment]
This is caused by 54394531, where Andreas made this change on purpose. Let's discuss this with him, and once we come to an agreement I'll revert it if necessary. There's a lot of other places in the code using this as well, so I don't want to just change it willy-nilly, especially considering it was changed *specifically* for PixelPaint.

My guess is that earlier without a grid it was hard to say where the pixels were actually starting so "centering" the inflated rect (with the thickness) around the cursor seemed better. Note that this issue only happens when the thickness of the tools is an odd number anyway.
